[스프링 - 협업 미션] 와일더(강규한) 미션 제출합니다.
woowacourse/atdd-subway-fare pull request #11
Opened 2021-05-28 09:38 UTC by lns13301

안녕하세요 지노! 만나서 반가워요. 😁
이번 미션 리뷰 잘부탁드립니다.

이번 미션은 기능 구현 보다는 소통하는 것에 초점을 맞추고 진행했습니다.
프론트의 요구사항을 요청 받고 적절한 api 를 설계하는 경험을 했는데, 재미있었습니다.
특히 백엔드끼리 두 팀이 함께 미션을 진행하면서 소통하는 색다른 경험도 좋았습니다.
이상하게 하루가 지나면 DNS 서버가 고장나는(?) 현상이 발견되면서 미션 진행 중에 docker, nginx 설정을 처음부터 다시하는 경험을 여러 번 했습니다. 덕분에 공부가 되었네요. 🤣

부족한 부분 피드백 해주시면 적극 반영하도록 하겠습니다!

프론트 주소 : https://recipe-searcher-3210.web.app/
백엔드 주소 : https://wilder-subway.kro.kr/
API Docs : https://wilder-subway.kro.kr/swagger-ui.html#/

2021-05-30 08:29 UTC, hyunssooo requested changes
안녕하세요 와일더 :)
미션 빠르게 잘 진행해주셨네요!👍
제가 늦었지만..😭
늦은 점 정말 죄송하고 몇 가지 코멘트 남겼습니다! 확인 부탁 드릴게요!

2021-05-30 08:29 UTC, hyunssooo commented on src/main/java/wooteco/subway/line/dto/SectionResponse.java
> +    int distance;
접근제어자가 없네요. 🤔

2021-05-30 08:29 UTC, hyunssooo commented on src/main/java/wooteco/subway/path/application/FarePrincipalFinder.java
> +public class FarePrincipalFinder {
bean으로 등록될 필요가 있을까요??

2021-05-30 08:29 UTC, hyunssooo commented on src/main/java/wooteco/subway/line/dto/SectionEntity.java
> +    final Long id;
이 dto는 실제로 사용하지는 않고 있네요! dao에서 dto를 반환하지 않고 존재 여부만 확인해도 괜찮을 것 같아요 :)

2021-05-30 08:29 UTC, hyunssooo commented on src/main/java/wooteco/subway/member/dto/MemberResponse.java
> +
사용하지 않는 import는 제거하는 것이 좋습니다. :)

2021-05-30 08:29 UTC, hyunssooo commented on src/main/java/wooteco/subway/member/ui/MemberController.java
> +        return ResponseEntity.ok().build();
validation 👍
`@RequestParam` 은 생략도 가능합니다 :)

2021-05-30 08:29 UTC, hyunssooo commented on src/main/java/wooteco/subway/line/domain/Line.java
> +    }
아래에 이미 `getStations()` 가 있지 않나요??

2021-05-30 08:29 UTC, hyunssooo commented on src/main/java/wooteco/subway/line/ui/LineController.java
> +        return ResponseEntity.ok(MapResponse.listOf(lines));
swagger를 사용하니 `@ApiOperation` 를 찾아보고 적용해 볼 수도 있겠네요!

2021-05-30 08:29 UTC, hyunssooo commented on src/main/java/wooteco/subway/path/domain/SubwayPath.java
> +    }
기존 코드에 대한 테스트는 모두 작성하지 못하더라도 새로 작성된 코드들은 테스트가 필요하지 않을까요? 🤔
최소한으로 핵심 비즈니스를 담고 있는 코드들은 테스트가 필수라고 생각해요. 
와일더 생각은 어떤가요?? 

```suggestion
    public double calculateFare(FarePrincipal farePrincipal) {
        return farePrincipal.calculateFare(calculateDistance(), findExtraFare());
    }

    private Long findExtraFare() {
        return sectionEdges.stream()
                .mapToLong(SectionEdge::extraFare)
                .max()
                .orElse(0);
    }
    
```

전체적으로 스페이스 컨벤션도 확인해보면 좋을 것 같아요 :)

2021-05-30 08:29 UTC, hyunssooo commented on src/main/java/wooteco/subway/path/domain/fare/TeenagerFarePrincipal.java
> +
상수 아닌가요??

```suggestion
    private static final double DISCOUNT_RATE = 0.2;

```

2021-06-01 06:42 UTC, lns13301 commented
# 와일더의 학습 프로필 🃏

지하철 요금 미션을 하면서 새롭게 학습한 내용을 정리했습니다.

## [Spring] Dispatcher Servlet - 3

### 내용

Servlet Container 에서 HTTP 프로토콜을 통해 들어오는 모든 요청을 프레젠테이션 계층의 제일 앞에 두고 중앙집중식으로 처리해 주는 프론트 컨트롤러다.

서블릿을 사용하면 쉽게 웹 요청과 응답을 쉽게 사용할 수 있다. 그로인해 개발자들이 처리(비지니스)로직에 더 집중할 수 있다. Spring MVC Framework 의 유일한 Front Controller 이며 Spring MVC 의 핵심요소다. Spring MVC 의 웹요청 Life Cycle 을 주관한다고 할 수 있다.

### 링크

- [[[Spring\]Dispatcher-Servlet이란?](https://mangkyu.tistory.com/18)](https://mangkyu.tistory.com/18)
- [20180206 DispatcherServlet ? (디스패처 서블릿)](https://pasudo123.tistory.com/39)

## [Docs] Swagger - 3

### 내용

Swagger 란 API 가 가지고 있는 스펙을 명세, 관리할 수 있는 프로젝트다. API 를 테스트 해볼 수 있는 화면을 제공하며, 동작을 테스트하는 용도에 특화되어 있다. 제품코드에 애너테이션을 추가해야한다. 제품코드와 동기화가 안되는 상황이 발생할 수 있다.

협업하거나 만들어진 프로젝트에 대해 유지보수를 할때, 구축되어진 API 서버가 어떤 스펙을 가지고 있는지 파악해야한다. 이러한 스펙을 직접 문서로 작성하게 되면 API 가 변경될 때마다 문서를 수정해야한다. 그래서 유지보수성의 향상을 위해 문서 자동화를 해주는 Swagger 를 사용한다.

- 의존성 추가 (Gradle)

  ```java
  	implementation 'io.springfox:springfox-swagger2:2.9.2'
  	implementation 'io.springfox:springfox-swagger-ui:2.9.2'
  ```

- 코드 적용

  ```java
  @Configuration
  @EnableSwagger2
  public class SwaggerConfig {
      @Bean
      public Docket api() {
          return new Docket(DocumentationType.SWAGGER_2)
                  .select()
                  .apis(RequestHandlerSelectors.basePackage("wooteco.subway")) // 기준 패키지
                  .paths(PathSelectors.ant("/**")) // api 에 띄울 url 형식
                  .build();
      }
  }
  ```

### 링크

- [Swagger 프로젝트 적용과 어노테이션](https://velog.io/@changyeonyoo/Swagger-%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8-%EC%A0%81%EC%9A%A9%EA%B3%BC-%EC%96%B4%EB%85%B8%ED%85%8C%EC%9D%B4%EC%85%98)

## [Docs] Rest Docs - 2

### 내용

깔끔 명료한 문서를 만들 수 있기 때문에 문서 제공용으로 사용하기 좋다. 라이브러리를 추가하지 않아도 된다. 컴파일 시점에서 오류를 잡기 쉽다. 동적 테스트 작성이 불편하다.

### 링크

- [Spring Rest Docs 적용](https://woowabros.github.io/experience/2018/12/28/spring-rest-docs.html)

## [Docker] 도커 - 5

### 내용

<b>Docker Engine</b> 은 애플리케이션을 빌드하고 컨테이너화 하기 위한 오픈 소스 컨테이너화 기술이다. Docker Engine 은 다음을 사용하여 클라이언트~서버 애플리케이션으로 작동한다.

- 오래 실행되는 데몬 프로세스가 있는 서버
- 프로그램이 Docker 데몬과 통신하고 지시하는데 사용할 수 있는 인터페이스를 지정하는 API 다.
- CLI 클라이언트 도커

<b>Docker Hub</b> 는 컨테이너 이미지를 찾고 팀과 공유하기 위해 Docker 에서 제공하는 서비스다. 컨테이너 커뮤니티 개발자, 오픈 소스 프로젝트 및 ISV(Independent Software Vendor) 를 포함한 다양한 콘텐츠 소스가 포함된 세계 최대의 컨테이너 이미지 저장소다.

애플리케이션이 배포되는 환경을 서버에 직접 설치하여 구성할 경우, [snowflake server issue](https://bcho.tistory.com/1224) 에 직면한다. 서비스가 점차 확장되면서 기존에 사용하던 서버와 새로 구축할 서버간의 설정차이가 발생하고, 관리자의 인적요소에도 영향을 받을 수 있다. 그리하여 기존에는 스크립트를 활용한 자동화 방식부터, kickstart 등을 거쳐 OS 를 가상화 방식까지 다양한 형태로 서버를 관리해 왔다.

도커의 주요 기능 중 일부

- 모든 클라우드 플랫폼에서 여러 언어 및 프레임 워크로 모든 애플리케이션을 컨테이너화하고 공유할 수 있는 기능
- 완전한 Docker 개발 환경의 간편한 설치 및 설정
- 최신 버전의 Kubernetes 포함
- 최신 상태를 유지하고 보안을 유지하기 위한 자동 업데이트
- Windows 에서 애플리케이션을 빌드하기 위해 Linux 와 windows Server 환경간에 전환하는 기능
- 기본 Windows Hyper-V 가상화를 통한 빠르고 안정적인 성능
- Windows 컴퓨터에서 WSL 2를 통해 Linux 에서 기본적으로 작업할 수 있는 기능
- 파일 변경 알림 및 로컬 호스트 네트워크에서 실행중인 컨테이너에 대한 쉬운 액세스를 포함하여 코드 및 데이터에 대한 볼륨 마운팅
- 지원되는 IDE 를 사용한 컨테이너 내 개발 및 디버깅



도커 설치하기

```
$ sudo apt-get update && \
sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common && \
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - && \
sudo apt-key fingerprint 0EBFCD88 && \
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
sudo apt-get update && \
sudo apt-get install -y docker-ce && \
sudo usermod -aG docker ubuntu && \
sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
sudo chmod +x /usr/local/bin/docker-compose && \
sudo ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose
```

도커 컨테이너도 프로세스다.

도커 실행하기

```
docker-compose up -d
```

도커 정지하기

```
docker stop $(docker container ls -q)
```

도커 삭제하기

```
docker-compose rm -v -f
sudo rm -rf db
```

도커 실행중인 컨테이너 확인하기

```
$ docker ps
```

도커 실행중인 컨테이너 종료하기

```
$ docker kill [docker 컨테이너 hash_id]
```

도커 Mysql DB 접속하기

```
~$ docker exec -it local-db bash
:/# mysql -uroot -p
```

<b>도커 이미지</b>

> 이미지는 파일들의 집합이고, 컨테이너는 이 파일들의 집합 위에서 실행된 특별한 프로세스

프로세스의 데이터가 변경되더라도 원본 프로그램 이미지를 변경할 수 없듯, 컨테이너의 데이터가 변경되더라도 컨테이너 이미지의 내용을 변경할 수 없다.

```
// 도커 이미지는 [저장소 이름]/[이미지 이름]:[태그]의 형태로 구성된다.
## Official 이미지는 [저장소 이름]을 붙여주지 않아도 된다.
$ docker pull ubuntu:lastest
```

### 링크

- [Nextstep - 도커 컨테이너 이해하기](https://techcourse.woowahan.com/s/U8wOamCU/ls/sUKqMwuQ)
- [Nextstep- 배포하기](https://techcourse.woowahan.com/s/U8wOamCU/ls/rOuQtU1c)
- [공식 문서](https://docs.docker.com/desktop/)

2021-06-01 12:16 UTC, lns13301 commented on src/main/java/wooteco/subway/line/domain/Line.java
> +    }
getStations 와 getSections 는 역할이 다르지 않나요?

2021-06-01 12:19 UTC, lns13301 commented on src/main/java/wooteco/subway/line/dto/SectionEntity.java
> +    final Long id;
dao 내부에서 존재 여부확인은 뭔가 비즈니스 적인 로직 같은데 서비스에서 처리하는 것보다 dao 에서 처리하는게 나은 방법인가요?

2021-06-01 12:41 UTC, lns13301 commented on src/main/java/wooteco/subway/path/domain/SubwayPath.java
> +    }
좋은 지적 감사합니다. 핵심 비즈니스 로직을 수행하는 클래스의 단위 테스트를 추가했습니다.

2021-06-01 14:05 UTC, hyunssooo commented on src/main/java/wooteco/subway/line/domain/Line.java
> +    }
제가 잘못 봤나 봐요🥲

2021-06-01 17:43 UTC, hyunssooo commented on src/main/java/wooteco/subway/path/domain/fare/FarePrincipalFinder.java
> +public class FarePrincipalFinder {
유틸성 클래스는 기본생성자를 private으로 선언하여 객체 생성을 막는 것은 어떨까요? 
member의 나이로 계산되는 것이니 member 객체에서 처리할 수도 있을 것 같아요 :)

2021-06-01 17:43 UTC, hyunssooo commented on src/main/java/wooteco/subway/path/ui/PathController.java
> +    public ResponseEntity<PathResponse> findPath(@AuthorizationMemberPrincipal LoginMember loginMember,
`@ApiOperation` 👍 배포까지 챙겨주셨네요!

2021-06-01 17:43 UTC, hyunssooo commented on src/main/java/wooteco/subway/path/domain/SubwayPath.java
> +    }
이 클래스는 테스트가 없나요?
추가하신 테스트가 어떤걸까요? 🤔

2021-06-01 17:43 UTC, hyunssooo commented on src/main/java/wooteco/subway/line/dto/SectionEntity.java
> +    final Long id;
개인적으로 이런 경우는 dao나 repository 에서 처리해도 괜찮다고 생각합니다. 
1. repository는 도메인레어에 속한다.
2. 모든 객체 section을 찾아와서 물어볼 수는 없다.

이 정도가 제 생각입니다. dao 객체에게 물어본다 정도로 생각해보는 것은 어떨까요?🙂

2021-06-01 17:48 UTC, hyunssooo requested changes
안녕하세요 와일더 :)
빠르게 반영해 주셨네요! 
몇 가지 코멘트 남겼어요! 
참고 부탁 드립니다! 
와일더 생각도 궁금하네요!

2021-06-03 01:27 UTC, lns13301 commented on src/main/java/wooteco/subway/path/domain/SubwayPath.java
> +    }
PathFinderTest 에서 테스트를 한다고 생각했는데, SubwayPath 에 대한 테스트도 따로 추가하겠습니다.

2021-06-03 09:42 UTC, lns13301 commented on src/main/java/wooteco/subway/path/domain/fare/FarePrincipalFinder.java
> +public class FarePrincipalFinder {
상수가 포함되어 있어서 유틸로 사용하는게 더 나을 것 같아요. 생성자는 막겠습니다.

2021-06-05 09:39 UTC, hyunssooo approved these changes
안녕하세요 와일더 :) 
빠르게 반영해주셨네요! 👍
확인이 늦어 정말 죄송하고 방학 푹 쉬고 다음 레벨도 잘 진행하세요! 🙏

2021-06-05 09:39 UTC, hyunssooo commented on src/test/java/wooteco/subway/path/domain/SubwayPathTest.java
> +    private Station 잠실역;
도메인 객체 테스트 👍
기존에 작성된 코드에 대한 테스트를 작성하기가 생각보다 쉽지 않죠? 개인적으로는 테스트 코드가 있어야 신뢰할 수 있는 코드라고 생각해요! 와일더가 작성한 코드라면 와일더 혼자는 신뢰할 수 있겠지만 다른 동료들이 볼 때는 아닐 수도 있습니다. 
테스트 작성이 쉽지 않지만 작은 테스트부터 꾸준하게 작성하는 습관을 가지면 좋겠습니다. (저도 아직은 많이 어렵네요 🥲) 작은 테스트부터 작성하고 큰 테스트를 작성해야 더 단단한 코드가 되지 않을까 개인적으로 생각해요 :)

2021-06-05 09:39 UTC, merged