[스프링 - 협업 미션] 와이비(허영범) 미션 제출합니다.
woowacourse/atdd-subway-fare pull request #12
Opened 2021-05-28 11:58 UTC by hybeom0720

안녕하세요, 닉! 처음 뵙겠습니다. 와이비입니다.

이번 미션의 경우 단순 기능 구현보다는 프런트 엔드랑 협업하면서 일어날 수 있는 일들,
배포 인프라에서 여러 기능들을 직접 겪어보는 방향으로 진행되었습니다.
그 과정 속에서 스프링 설정에 관한 질문이 있어서 남기게 되었습니다.

# 인증 권한으로 할 수 있는 여러 일들

이번 미션에서는 로그인을 하지 못하면 아에 할 수 없는 일과 로그인을 안해도 할 수 있는 일이 있었습니다.
예를 들어 회원 정보 관리는 회원만이 할 수가 있지만, 노선 조회 등은 비회원도 할 수 있는 시스템입니다.
이 때, 로그인을 안해도 노선 조회를 하면 자동으로 성인 기본 기준으로 요금이 계산이 됩니다.
때문에 비회원들도 나이에 대한 기본 값이 주어져야합니다.

하지만 기존의 Resolver 및 Annotation에서는 로그인 되지 않으면 해당 항목으로 들어가지 못하도록 처리가 되어있습니다.
이는 그대로 적용하면 비회원들은 노선 조회를 할 수 없는 것으로 나오게 되었습니다.
페어와 의논해 본 결과, 기존에 주어진 @AuthenticationPrincipal를 다루는 기본 Resolver 뿐만이 아니라
 로그인하지 않을 시에도 기본적인 값으로 권한을 주는 Annotation과 Resolver를 만들어서 해당 권한에 대해서도 비회원도 접근할 수 있도록 바꾸게 되었습니다.

실제 현업에서는 이와 같은 케이스에 마찬가지로 처리해주는 객체 및 Annotation을 분리하는지 아니면 다른 방법을 사용하는지 궁금합니다.

감사합니다.

2021-05-30 12:28 UTC, wbluke requested changes
안녕하세요 와이비 ㅎㅎ 미션 잘 진행해 주셨네요 👍 
질문 주신 부분 포함해서 몇 가지 코멘트 남겼으니 확인 부탁드려요 🙂

2021-05-30 12:28 UTC, wbluke commented on src/main/java/wooteco/subway/path/domain/Fare.java
> +    }
어떻게 계산하고 있는지 한눈에 파악이 조금 어려워 보이는데요 ㅎㅎ
AgeAppliedRule에서 잘 해주신 것처럼 별도의 거리별 요금 계산 Enum을 만들어보면 어떨까요? :)

2021-05-30 12:28 UTC, wbluke commented on src/main/java/wooteco/subway/path/domain/Fare.java
> +    public Fare(int distance, LoginMember member, int extraFare) {
Fare 라는 네이밍을 생각했을 때, 생성자에 LoginMember를 포함한 다양한 인자를 받는 것이 조금 어색하게 느껴지는데요 ㅎㅎ
Fare는 순수 int 를 감싼 `요금` 자체로 표현이 되면 좋을 것 같고, 이를 계산해주는 별도의 계산기 객체가 있으면 어떨까요? :)

2021-05-30 12:28 UTC, wbluke commented on src/main/java/wooteco/subway/auth/ui/AuthenticationMemberArgumentResolver.java
> +            return new LoginMember(0L, "Guest", 20);
> 이번 미션에서는 로그인을 하지 못하면 아에 할 수 없는 일과 로그인을 안해도 할 수 있는 일이 있었습니다.
예를 들어 회원 정보 관리는 회원만이 할 수가 있지만, 노선 조회 등은 비회원도 할 수 있는 시스템입니다.
이 때, 로그인을 안해도 노선 조회를 하면 자동으로 성인 기본 기준으로 요금이 계산이 됩니다.
때문에 비회원들도 나이에 대한 기본 값이 주어져야합니다.
> 
> 하지만 기존의 Resolver 및 Annotation에서는 로그인 되지 않으면 해당 항목으로 들어가지 못하도록 처리가 되어있습니다.
이를 그대로 적용하면 비회원들은 노선 조회를 할 수 없는 것으로 나오게 되었습니다.
페어와 의논해 본 결과, 기존에 주어진 @AuthenticationPrincipal를 다루는 기본 Resolver 뿐만이 아니라
로그인하지 않을 시에도 기본적인 값으로 권한을 주는 Annotation과 Resolver를 만들어서 해당 권한에 대해서도 비회원도 접근할 수 있도록 바꾸게 되었습니다.
> 
> 실제 현업에서는 이와 같은 케이스에 마찬가지로 처리해주는 객체 및 Annotation을 분리하는지 아니면 다른 방법을 사용하는지 궁금합니다.

음 여러가지 방법이 있을 것 같은데요, LoginMember에 별도의 권한 체크 필드를 두면 어떨까요?
쉽게는 boolean 타입으로 로그인 유무를 판별할 수 있을 것 같고, (LoginMember라는 이름이 조금 바뀌어야 할 수도 있겠네요)
더 나아간다면 권한을 관리하는 객체(Enum)를 두고 체크해볼 수도 있을 것 같아요 :)

2021-05-30 12:28 UTC, wbluke commented on src/main/java/wooteco/subway/path/application/PathService.java
> +    public PathResponse findPath(Long source, Long target, LoginMember member) {
현재 인수테스트와 단위테스트만 존재하는데요, 서비스 레이어 통합테스트도 진행해보면 어떨까요? :)

2021-05-30 12:28 UTC, wbluke commented on src/main/java/wooteco/subway/path/application/PathService.java
> +            throw new InvalidPathException(e.getMessage());
`e.getMessage()`는 내부 구현 정보가 외부로 드러날 수 있기 때문에, 별도의 메시지를 부여하는 것이 좋을 것 같아요 :)

2021-05-30 12:28 UTC, wbluke commented on src/main/java/wooteco/subway/path/domain/AgeAppliedRule.java
> +    private IntPredicate isAgeInterval;
predicate 잘 사용했네요 👍

2021-05-30 12:28 UTC, wbluke commented on src/main/java/wooteco/subway/path/domain/SubwayPath.java
> +    public int maximumExtraFare() {
이 부분도 테스트가 있으면 좋을 것 같네요 :)

2021-05-30 12:28 UTC, wbluke commented on src/main/java/wooteco/subway/path/ui/PathController.java
> +        @RequestParam Long target, @AuthenticationMember
개인적으로는 `@ReuqestParam`을 지양하려고 하는데요.
RequestParam 대신 Request DTO로 파라미터를 받게 되면, 최소한의 validation도 해줄 수 있고
때에 따라 여러가지 책임(ex. 도메인으로의 변환) 등을 가질 수 있기 때문이에요 ㅎㅎ
(지금 로직에 null 값이 파라미터로 들어온다면?)

java bean validation으로 null check 등의 검증을 해보면 어떨까요? :)

2021-06-01 08:54 UTC, hybeom0720 commented on src/main/java/wooteco/subway/path/application/PathService.java
> +            throw new InvalidPathException(e.getMessage());
밑단에서 발생하는 Exception을 조사해보니, 전부 InvalidPathException 인 것 같아서,
해당 try-catch문을 제거하였습니다.

2021-06-03 13:33 UTC, hybeom0720 commented
안녕하세요! 닉
# LoginMember, Guest
닉의 말씀데로 이번에는 LoginMember 이외의 인증 권한을 가지도록 코드를 수정하게 되었습니다.
다만 이번엔 Guest라는 새로운 객체를 만들게 되었습니다.
닉의 말씀대로 필드 값을 Enum으로 관리해도 되지만, 두 개의 권한만 존재할 때에는 Interface로 필요한 기능들에 대해서 구현을 통한 재정의를 하는 것이 조금 더 기능에 따른 객체 분리에 있어서 좋아보였기 때문입니다.
만약 Enum으로 해야한 다면, LoginMember를 User로 수정한 다음에 authorization이라는 필드 값을 관리하는 Enum으로 관리하도록 하겠습니다. 
추가적으로 Guest이든 LoginMember이든 User라는 인터페이스르 구현한 객체가 서비스까지 흘러가는게 필수적일 것 같은데,
Guest가 권한이 없는 곳은 서비스에서 예외처리를 하면 될지 궁금합니다.

# Interceptor
이번에는 Interceptor 라는 기능을 처음으로 도입해보게 되었습니다.
다른 크루들은 저번 미션에서 도입하였지만, 저는 ArgumentResolver로만 처리하였기 때문입니다.
Interceptor의 경우에는 이번 미션에서는 단순하게 토큰을 가지고 있는지 없는지를 체크하게 되었습니다.
로그인 기능도 붙힐 수도 있지만, ArgumentResolver에서 토큰을 해석한 다음에 로그인 기능이 실질적으로 이뤄질 수 있다고 생각하여서
토큰 존재유무 확인 (Interceptor) -> 토큰 해석 (ArgumentResolver) -> 토큰을 통한 멤버 조회 (MemberService) 로
로직을 구현하게 되었습니다.
다만 이 때, 로그인이 필요한 기능들을 MemberService에서 메소드마다 넣어주어야하는 불편함이 있는 것 같습니다. 
실제로는 Interceptor에서 로그인에 필요한 기능(존재유무 확인, 해석, 멤버조회) 들을 다 넣고, 사용하는지 아니면 지금처럼 역할을 분리하여 로그인 과정을 거치는게 맞는지 궁금합니다!

#Fare
말씀하신데로 Fare는 순수 요금으로 두고 FareCalculator로 계산 로직을 분리하게 되었습니다.
이 때, Enum으로 각각의 거리에 따른 요금 계산 기준을 연결해놓고, 거리에 따라서 연쇄적으로 작동하도록 코드를 짜게 되었습니다.
(ex. 60 초과이면 Excess -> Extra -> Basic 거치면서 다 더해서 지하철 요금 산출)
이를 통해서 각각의 구간 요금 정책에 대해서 독립적으로 수정할 수 있는 장점이 있는 것 같은데, 리뷰해주신 방향이 맞는지 궁금합니다.

2021-06-04 15:56 UTC, wbluke approved these changes
수정해주신 내용 잘 보았습니다! 👍 
질문에 대한 답변 남겼으니 참고해 주시고요, 레벨2 미션 고생 많으셨어요 🙂

2021-06-04 15:56 UTC, wbluke commented on src/main/java/wooteco/subway/auth/AuthenticationPrincipalConfig.java
> +    public void addInterceptors(InterceptorRegistry registry) {
> Interceptor의 경우에는 이번 미션에서는 단순하게 토큰을 가지고 있는지 없는지를 체크하게 되었습니다.
로그인 기능도 붙힐 수도 있지만, ArgumentResolver에서 토큰을 해석한 다음에 로그인 기능이 실질적으로 이뤄질 수 있다고 생각하여서
토큰 존재유무 확인 (Interceptor) -> 토큰 해석 (ArgumentResolver) -> 토큰을 통한 멤버 조회 (MemberService) 로 로직을 구현하게 되었습니다.
다만 이 때, 로그인이 필요한 기능들을 MemberService에서 메소드마다 넣어주어야하는 불편함이 있는 것 같습니다.
실제로는 Interceptor에서 로그인에 필요한 기능(존재유무 확인, 해석, 멤버조회) 들을 다 넣고, 사용하는지 아니면 지금처럼 역할을 분리하여 로그인 과정을 거치는게 맞는지 궁금합니다!

Login 로직을 어디에 두는 것이 맞느냐라는 관점 보다는, ArgumentResolver의 역할을 생각해보시면 될 것 같아요.
애플리케이션 요청의 진입점인 Controller에서 원하는 형태로 파라미터를 받기 위해 사용한다는 관점으로 보면 이해가 되지 않을까 싶네요 :)

2021-06-04 15:56 UTC, wbluke commented on src/main/java/wooteco/subway/auth/ui/AuthenticationMemberArgumentResolver.java
> +            return new Guest();
> 첫 번째 질문으로는
권한이 다양해지면, ENUM으로 관리를 해야할 것 같은데 LoginMember, Guest로 나누기 보다는 권한에 관한 필드를 만든 다음에 ENUM과 연결하는 방향이 맞는지 궁금합니다.

네네, 제가 이전 코멘트에서 말씀드린 내용이 그 부분이에요 :)

> 두 번째 질문은
추가적으로 Guest이든 LoginMember이든 User라는 인터페이스르 구현한 객체가 서비스까지 흘러가는게 필수적일 것 같은데, Guest가 권한이 없는 곳은 서비스에서 예외처리를 하면 될지 궁금합니다.

비회원 권한이 없는 로직은 구성해주신 것처럼 interceptor에서 처리를 하거나, 
권한 필드로 분기 제어가 필요하다면 서비스에서 진행해야 겠네요 :)

2021-06-04 15:56 UTC, wbluke commented on src/main/java/wooteco/subway/path/domain/fare/fareStrategy/DistanceAppliedRule.java
> +    EXCESS(distance -> (distance>=40), ExcessDistanceFare::new);
Enum과 interface의 구현체를 조합하셨군요 👍

2021-06-04 15:56 UTC, wbluke commented on src/main/java/wooteco/subway/path/domain/fare/fareStrategy/DistanceAppliedRule.java
> +package wooteco.subway.path.domain.fare.fareStrategy;
패키지명은 소문자가 원칙이에요 :)

2021-06-04 15:56 UTC, merged