[스프링 - 협업 미션] 찰리(박민영) 미션 제출합니다.
woowacourse/atdd-subway-fare pull request #14
Opened 2021-05-28 18:01 UTC by Gomding

안녕하세요 미립!
코드리뷰를 받게 되어서 정말 영광이에요 🙇 🙇 🙇 🙇 

이번 미션은 프론트엔드 크루들과 API 명세에 대한 토론으로 시작을 해서 색다른 경험이었어요!
특히 예전부터 API 문서를 만들어주는 Swagger 를 사용해보고 싶었는데 적용하기가 겁이나서 못해보고 있었어요.
이번에 프론트 크루들이 Swagger 를 언급해줘서 한번 적용해보니 생각보다 너무 쉬워서 깜짝 놀랬다는 TMI 를 해봅니다!
(Swagger에서 제공해주는 API 테스트 기능을 배포된 상태에서 사용하면 에러가 발생해서 이 부분을 추가 학습해보려고 합니다 😭 )
```다음엔 restdoc 도 직접 만들어 보고 싶네요```

서버에 배포중인 API의 코드와 현재의 코드에 차이가 있지만 [여기](https://woowasubway.kro.kr/swagger-ui.html)서 Swagger로 만든 문서를 확인할 수 있어요.

이번 미션에서 가장 시간을 많이 들였던 부분은 역시 예외 처리인데요.
여러가지 예외 상황에서 HttpStatus 와 예외메세지를 팀과 함께 맞춰나가는게 재밌었습니다!
@Valid 를 사용해서 상황마다 다양한 예외 메세지(message)를 주도록 구현해봤어요 
ControllerAdvice 를 홀쭉하게 만든것같아서 뿌듯합니다 😄 
예외 상황에 대한 테스트도 모두 작성해봤는데 부족한 부분이 보이면 가차없는 피드백 부탁드립니다 🙏 

또 프론트엔드에서 요청한 사항 중 ```노선을 조회할 때 포함된 역마다 환승 가능한 노선정보를 모두 응답해주세요``` 라는 요청에 대해 가장 고민을 많이 했어요.
당시에 너무 늦으면 프론트분들이 미션을 진행할 수 없을까봐 
빠르게 구현한다고 코드가 많이 지저분해졌는데 이 부분은 최대한 리팩터링 해보겠습니다!!(굉장히 절차지향적인 부분이 있어요..)

2021-05-29 08:59 UTC, seok-2-o requested changes
안녕하세요 찰리. 이번 미션을 함께할 미립입니다.
코드를 엄청 꼼꼼하게 작성해주셨네요 👍 
꼼꼼한 예외처리와 응답 객체 작성이 인상적이였습니다.

다만, 완전히 동일한 형태의 DTO 객체들이 몇몇 눈에 띄네요.
추후 다른 갈래로 발전 가능하지만 현재 그렇지 않은데 미리 분리해놓을 필요가 있을지는 고민해보면 좋을것 같아요.

저와 의견이 다르거나 궁금한점 어려운점이 있으면 편하게 연락주세요. 🙇

2021-05-29 08:59 UTC, seok-2-o commented on src/main/java/wooteco/subway/line/dto/LineNameColorResponse.java
> +    public static LineNameColorResponse of(LineNameColorDto transferLine) {
DTO 랑 Response 랑 어떤 차이가 있나요? 🤔

2021-05-29 08:59 UTC, seok-2-o commented on src/main/java/wooteco/subway/line/dto/SectionAddResponse.java
> +public class SectionAddResponse {
완전히 동일한 Response객체를 여러개 만들 필요가 있을까요 ? 🤔 

https://ko.wikipedia.org/wiki/YAGNI

2021-05-29 08:59 UTC, seok-2-o commented on src/main/java/wooteco/subway/member/application/MemberService.java
> +        Member updateMember = member.update(member.getEmail(), member.getPassword(), memberInfoUpdateRequest.getAge());
불변객체로 만들어주셨네요. 어떤 장단점이 있으셨는 지궁금합니다.

id 와 마찬가지로 이메일과 패스워드도 this 로 받을 수 있을것 같은데 외부에서 주입 받은 이유도 궁금하네요.

2021-05-29 08:59 UTC, seok-2-o commented on src/main/java/wooteco/subway/member/dao/MemberDao.java
> +    private final JdbcTemplate jdbcTemplate;
NamedParameterJdbcTemplate 도 한번 살펴보고 어떤 장단점이 있을까 고민해보면 좋겠어요.

2021-05-29 08:59 UTC, seok-2-o commented on src/main/java/wooteco/subway/member/domain/LoginMember.java
> +    public static LoginMember guest() {
상수에 직접 접근하는것과 메소드를 통해 접근하는것은 어떤 차이가 있나요 ?

2021-05-29 08:59 UTC, seok-2-o commented on src/main/java/wooteco/subway/member/dto/DuplicateEmailCheckRequest.java
> +    @NotBlank(message = "입력되지 않은 항목을 확인해주세요")
@NotEmpty 는 null 과 "" 과 " " 모두 허용하지 않습니다.

2021-05-29 08:59 UTC, seok-2-o commented on src/main/java/wooteco/subway/station/dao/StationDao.java
> +            do {
이번과정에서는 들여쓰기를 1번으로 제한하고 있어요.
해당부분은 어떻게 리펙토링하면 좋을까요?

2021-05-29 08:59 UTC, seok-2-o commented on src/main/java/wooteco/subway/path/ui/PathController.java
>  @CrossOrigin(origins = "*", allowedHeaders = "*")
크로스 오리진 설정을 컨트롤러마다 해주신 이유가 있으실까요?

2021-05-29 08:59 UTC, seok-2-o commented on src/main/java/wooteco/subway/member/ui/MemberController.java
> +    @PutMapping("/me/pw")
엄격하게 구분하자면 PUT 은 모든 자원의 교체를 의미합니다.
따라서 비밀번호 하나만 변경하는 행위는 Patch 가 어울리는것 같아요.

2021-06-03 09:09 UTC, Gomding commented on src/main/java/wooteco/subway/line/dto/LineNameColorResponse.java
> +    public static LineNameColorResponse of(LineNameColorDto transferLine) {
데이터베이스 에서 조회한 후에 데이터를 담을 그릇으로 DTO 를 사용했었습니다.

LineNameColorDto 가 만들어진 배경은 아래와 같아요

### 하나의 역에서 환승 가능한 노선들의 정보를 가지도록 프론트측에서 데이터를 요청했는데

현재의 도메인 구조에서는 위와 같은 데이터를 담을 시 결국 DTO 같은 객체가 생길것 같다고 생각했어요.
데이터 베이스에서 조회하여 가져오는 환승가능 노선 정보는 
LIne 의 id, name, color 3가지 정보만 담으면 충분했기 때문에 LineNameColorResponse 가 존재함에도
데이터베이스에서 조회한 데이터를 담을 적절한 그릇이 없었기 때문에 LineNameColorDto 를 만들어서 사용하게 됐습니다.

만약 LineNameColorResponse 와 LineNameColorDto 가 중복된 클래스라고 하여 제거한다면
Response 를 데이터베이스에서 사용해도 되는가에 대해 고민하고 있어요!

미립의 의견을 듣고싶어요!

2021-06-03 09:13 UTC, Gomding commented on src/main/java/wooteco/subway/line/dto/SectionAddResponse.java
> +public class SectionAddResponse {
StationAddResponse 는 Section을 추가하고 응답해주기 위한 객체인데

이번에 명세를 맞추면서
Section 조회는 Station 에 대한 정보(id, 이름)을 전부 주도록 하고
``` java
public class SectionResponse {
    private final StationResponse upStation;
    private final StationResponse downStation;
    private final Integer distance;
```
Section 추가 후 응답에서는 Station 의 ID 만 필요했기 때문에 SectionAddResponse 라는 객체가 탄생하게 됐어요 ㅠㅠ
``` java
public class SectionAddResponse {
    private Long upStationId;
    private Long downStationId;
    private Integer distance;
```

2021-06-03 10:57 UTC, Gomding commented on src/main/java/wooteco/subway/member/application/MemberService.java
> +        Member updateMember = member.update(member.getEmail(), member.getPassword(), memberInfoUpdateRequest.getAge());
불변객체의 장점으로는 객체의 상태를 변경되지 않는다는걸 보장한다는 장점이 있겠네요.

#### 반성하자면 큰 이유없이 불변객체로 만들어버리고 있었네요

불변객체의 장점에 대해 생각하면서
Member 객체에 update 라는 메서드를 사용해서 상태를 변경한 객체를 단순히 새로운 주소값으로 반환해주는것으로 정말 괜찮은지 생각해봤어요. update 도 setter와 비슷한 느낌을 받았기 때문이에요!

이렇게 했을때는 불변의 의미가 없을거라 생각해요.

Member 처럼 상태가 변경될 여지가 확실한 경우에는 불변 객체로 만들지 않는게 맞을까요?

아니면 해당 객체를 다른곳에서 사용할 때 상태 변경을 공유하지 않도록 불변객체로 만들어주는게 맞을까요??!

2021-06-03 11:21 UTC, Gomding commented on src/main/java/wooteco/subway/member/dao/MemberDao.java
> +    private final JdbcTemplate jdbcTemplate;
JdbcTemplate 를 사용하면 쿼리문의 ? 에 배치하는 순서를 틀리게 넣을 수도 있다는 단점이 있는데

NamedParameterJdbcTemplate 를 사용하면 이런 단점을 보완할 수 있습니다.

한가지 궁금한점은 파라미터가 필요하지 않은 쿼리문의 경우에는
NamedParameterJdbcTemplate 를 사용하는 방법이 없을까요? ㅠㅠ
이게 단점이라고 생각해요 😭

2021-06-03 11:28 UTC, Gomding commented on src/main/java/wooteco/subway/member/domain/LoginMember.java
> +    public static LoginMember guest() {
큰차이가 없다고 생각해서 GUEST 에 바로 접근할 수 있도록 수정했어요!

```java
public static final LoginMember GUEST = new LoginMember(0L, "guest@email.com", 20);
```

2021-06-03 11:41 UTC, Gomding commented on src/main/java/wooteco/subway/member/dto/DuplicateEmailCheckRequest.java
> +    @NotBlank(message = "입력되지 않은 항목을 확인해주세요")
null 도 혀용하지 않는것을 포함하고 있었군요 😱 
모든 필드에 
NotBlank 와 NotNull 을 함께 써놓던것을 수정했습니다!
f037470

2021-06-03 11:51 UTC, Gomding commented on src/main/java/wooteco/subway/station/dao/StationDao.java
> +            do {
메서드 분리를 통해서 들여쓰기를 1번만 하도록 리팩터링을 해봤어요!

아래는 변경 전 코드에요!
```java
private RowMapper<List<StationTransferLinesDto>> stationRowMapperWithTransferLines = (rs, rowNum) -> {
        List<StationTransferLinesDto> stationTransferLinesDtos = new ArrayList<>();
        Long stationId = 0L;
        while (!stationId.equals(rs.getLong("id")) || !rs.isLast()) {
            stationId = rs.getLong("id");
            String stationName = rs.getString("name");
            List<LineNameColorDto> lineNameColorDtos = new ArrayList<>();
            do {
                lineNameColorDtos.add(
                        new LineNameColorDto(
                                rs.getLong("line_id"),
                                rs.getString("line_name"),
                                rs.getString("line_color"))
                );
            } while (!rs.isLast() && rs.next() && stationId.equals(rs.getLong("id")));
            stationTransferLinesDtos.add(new StationTransferLinesDto(stationId, stationName, lineNameColorDtos));
        }
        return stationTransferLinesDtos;
    };
```

아래는 변경 후 코드입니다!
```java 
private final RowMapper<List<StationTransferLinesDto>> stationRowMapperWithTransferLines = (rs, rowNum) -> {
        List<StationTransferLinesDto> stationTransferLinesDtos = new ArrayList<>();
        Long stationId = 0L;
        while (!stationId.equals(rs.getLong("id")) || !rs.isLast()) {
            stationId = rs.getLong("id");
            String stationName = rs.getString("name");
            List<LineNameColorResponse> lineNameColorResponses = extractLine(rs, stationId);
            stationTransferLinesDtos.add(new StationTransferLinesDto(stationId, stationName, lineNameColorResponses));
        }
        return stationTransferLinesDtos;
    };

 private List<LineNameColorResponse> extractLine(ResultSet result, Long stationId) throws SQLException {
        List<LineNameColorResponse> lineNameColorResponses = new ArrayList<>();
        while (!result.isLast() && result.next() && stationId.equals(result.getLong("id"))) {
            lineNameColorResponses.add(
                    new LineNameColorResponse(
                            result.getLong("line_id"),
                            result.getString("line_name"),
                            result.getString("line_color"))
            );
        }
        return lineNameColorResponses;
    }
```

2021-06-03 11:56 UTC, Gomding commented on src/main/java/wooteco/subway/path/ui/PathController.java
>  @CrossOrigin(origins = "*", allowedHeaders = "*")
기존 뼈대코드에 있던코드라 크게 신경쓰지 않았는데
만약 공통적으로 바꿔야하는 상황이 생기면
모든 컨트롤러를 돌아다니면서 설정을 바꿔줘야 하겠네요 😱 😱 😱 😱 

아래와 같이 설정파일로 만들어봤어요!
```java
@Configuration
public class WebConfig implements WebMvcConfigurer {
    @Override
    public void addCorsMappings(CorsRegistry registry) {
        registry.addMapping("/**").allowedMethods("*").allowedOriginPatterns("*");
    }
}
```

2021-06-03 11:58 UTC, Gomding commented on src/main/java/wooteco/subway/member/ui/MemberController.java
> +    @PutMapping("/me/pw")
Patch 라는 메서드가 어떤 상황에 사용되는지 모르고있었는데
리소스의 일부분 변경에 사용되는 메서드였군요!

[mozilla PATCH 메서드](https://developer.mozilla.org/ko/docs/Web/HTTP/Methods/PATCH)

2021-06-03 12:47 UTC, Gomding commented
안녕하세요 미립!
피드백 반영이 늦었네요 😢

최근 테스트에 대한 중요성을 다시 깨달아서
도메인과 DAO 에 대한 단위테스트도 전부 추가해봤어요!
특히 리팩터링 하는 부분에 대해서는 테스트부터 예외 사항까지 고려해 꼼꼼하게 추가해보려고 노력했어요 

---

노선을 조회할 때 아래와 같이 정보를 프론트 측에서 요구했었어요
```
HTTP/1.1 200 OK

{
  "id" : 1,
  "name" : "신분당선",
  "color" : "bg-red-600",
  "stations" : [
    {
      "id": 1,
      "name": "강남역",
      "distance": 10, // 다음역까지의 거리
      "transferLines": [ // 환승역 목록
         {
           "id" : 2,
           "name" : "2호선",
           "color" : "bg-green-600"
         }
      ]
    }
  ]
}
```

위의 데이터를 응답해주기 위해 많은 고민을 하다가 프론트 크루의 미션진행을 위해 급하게 구현하긴했는데
현재는 조금 복잡한 쿼리문을 날려서 만든 Response 객체들과 도메인을 활용해서 응답을 완성하도록 했어요

쿼리는 아래와 같아요
```java
public List<StationTransferLinesDto> findAllWithTransferLines() {
        String sql = "SELECT DISTINCT st.id, st.name, l.id AS line_id, l.name AS line_name, l.color AS line_color " +
                "FROM station AS st " +
                "LEFT JOIN section AS sec ON st.id = sec.up_station_id OR st.id = sec.down_station_id " +
                "LEFT JOIN line AS l ON sec.line_id = l.id";
        try {
            return jdbcTemplate.queryForObject(sql, stationRowMapperWithTransferLines);
        } catch (EmptyResultDataAccessException e) {
            return Collections.emptyList();
        }
    }
```

**제가 드리고 싶은 질문은** 보내주고 싶은 응답이(프론트에서 요구하는 데이터구조가) 현재의 도메인 설계로는 힘들어 보일때
* 쿼리 + DTO(Response)로 해결하는 방법
* 도메인 설계를 변경 또는 어떻게든 도메인을 활용해서 해결
둘 중 어떤것을 선택해야하는지 많이 고민했어요.

제 의견은 도메인을 무리하게 바꿔서 더럽히느니 쿼리문으로 해결하는 낫다고 생각해요!
하지만 언젠가는 도메인을 리팩터링하는 쪽으로 하고싶은데

미립의 경우에는 어떤식으로 진행하는지 궁금합니다 🙇

2021-06-04 11:02 UTC, seok-2-o commented on src/main/java/wooteco/subway/line/dto/LineNameColorResponse.java
> +    public static LineNameColorResponse of(LineNameColorDto transferLine) {
공통 적으로 사용하는 DTO 를 분리한 시도 자체는 훌륭한 것 같습니다 👍 

제가 너무 늦게 확인했네요 :(

2021-06-04 11:03 UTC, seok-2-o commented on src/main/java/wooteco/subway/member/application/MemberService.java
> +        Member updateMember = member.update(member.getEmail(), member.getPassword(), memberInfoUpdateRequest.getAge());
```
class Member {
    private String gender;
}
memberDao.update(Member member);
UPDATE SET (...) GENDER = :gender (...)
Member member = dao.findById(id);// 성별 정보 가지고 있음
member.update(req.getEmail(), req.getPassword()): // 성별 정보 가지고 있음
dao.update(member): // 성별 정보 유지됨
Member membeer. dao.findById(id) // 성별 정보 가지고 있음
Member nuwMember = new Member(member.getId(), req.getEmail(), req.getPassword()) // 성별 정보 사라짐
dao.update(member); // 성별정보 영구 소실
```

해당 케이스를 좀 더 고민해보면 좋을 것 같아요

2021-06-04 11:05 UTC, seok-2-o commented on src/main/java/wooteco/subway/member/dao/MemberDao.java
> +    private final JdbcTemplate jdbcTemplate;
NamedParameterJdbcTemplate 도 JdbcTemplate 과 동일하게 모든 인터페이스를 제공하고 있는것으로 알고 있어요.

2021-06-04 11:49 UTC, seok-2-o approved these changes
단위 테스트를 추가하는 일이 쉽지 않으셨을텐데 정말 대단하세요 💯 

저는 복잡한 조회의 경우 별도 DTO 와 Query르를 만드는 것이 옳다고 생각해요.
말씀하신 것처럼 도메인을 무리하게 변경하면 오히려 어떤 액터는 쓸때 없는 복잡성을 가지게 되기 때문이죠.

물론 빈번하게 함께 조회 되는경우에는 도메인을 리펙터링 하는 결정을 할 수 있지만,
단순히 조회 관점에서만 결정하는 것은 바람직하지 않은 것 같네요.

비지니스적인 관점, 성능, 라이프 사이클 등등 많은것들이 고려되어야 할 것 같아요.

이번 코멘트와 답글을 마지막으로 미션은 종료하도록 할게요.

이번 미션을 마지막으로 리뷰어로서 만나는 것은 마지막인데,
찰리와의 시간이 정말 좋은 경험으로 남게 될 것 같아요. 
찰리에게도 저와의 시간이 부디 그러하길 바랍니다. :)

즐거운 방학 보내시고 마지막까지 조금 더 힘내시길 바랄게요.
감사합니다.

2021-06-04 11:49 UTC, seok-2-o commented on src/main/java/wooteco/subway/auth/application/AuthService.java
>          } catch (Exception e) {
Exception 을 잡는것은 발생할 수 있는 모든 에러를 컨슘해서 이용자 혹은 개발자에게 빠르게 전달되어야 하는
에러도 컨슘해서 문제를 키울 수 있다고 생각해요.

2021-06-04 11:52 UTC, merged