[스프링 - 협업 미션] 인비(김태희) 미션 제출합니다.
woowacourse/atdd-subway-fare pull request #2
Opened 2021-05-22 07:00 UTC by taehee-kim-dev

### 안녕하세요, 게이츠!! 😄 

이번 미션은 배포와 새로운 정책 추가 및 프론트 크루들과의 협업 미션이었습니다.

배포 된 엔드포인트는 `https://inbi-subway.kro.kr` 입니다.

### 프론트 크루들과의 협업

프론트 분들과 API 스펙 회의를 했습니다.
이미 `GET "/lines"` 요청에 대한 응답 구현이 완벽하게 잘 돼 있고,
API path 자체도 `"/lines"` 가 가장 적절해서 그냥 쓰는 게 가장 베스트일 것 같다는 결론이 나왔어요.
2단계 요구사항에서는 모든 걸 새로 구현하라고 해서 어떻게 해야할지 감이 안 잡혔습니다.

그래서 이에 대해 코치 브라운에게 질문 드린 결과 아래와 같은 답변을 받았습니다.

```
그렇다면 그것을 써도 좋아요ㅎㅎ대신 새로운 path를 가지고 응답할 수 있는 api를 만들어보세요
lines와 응답이 같을 순 있지만 path는 다르게 만들어 주세요ㅎㅎ
```

그래서, 프론트 분들은 기존 뼈대코드인 `GET "/lines"` 를 사용하기로 했습니다.
그리고 브라운의 답변에 따라, `LineApiController` 에 `GET "/api/lines"` 의 Controller 메서드를 추가했어요. 이 API는 __기존 GET /lines API와 URI만 다를 뿐, 기능 및 응답결과 동일__ 합니다. 

### 요금 계산 도메인

요금 값을 도메인 객체 `Fare` 로 Wrapping 했습니다.

요금 계산 도메인 객체 `FareCalculator` 를 만들었습니다.
단위 테스트가 가능한 객체를 만들기 위해, 각 요구사항을 각 메서드로 분리했습니다.
한 메서드에서 복합적인 요금 계산 로직을 적용할 수 있지만, 
그렇게 되면 한 메서드가 여러가지 일을 하게 되고,
단위 테스트를 하기 어려워 이와 같은 방식을 선택했습니다.

### 로그인/비로그인 상태에서 경로 조회

기존 `@AuthenticationPrincipal` 은 로그인이 되어있지 않으면 바로 예외를 발생시킵니다.
하지만, 비로그인 상태에서 경로를 조회했을 때는 예외를 발생시키면 안됩니다.

이를 위해 `@AuthenticationPrincipal` 자체를 변경할 수도 있지만, 
처음에 주어진 뼈대코드를 최대한 건드리지 않고 새로운 정책을 추가하려 했습니다.

그래서 `@AuthenticationPrincipalOptional` 을 새로 만들었습니다.
이는 어노테이션이 있는 메소드 파라미터에 `Optional<LoginMember>`를 넣어줍니다.
로그인이 되어있을 경우, `Optional<LoginMember>` 의 내부에는 로그인 되어있는 사용자의 `LoginMember` 객체가 존재합니다.
로그인이 되어있지 않을 경우, `Optional<LoginMember>` 는 `Empty` 가 됩니다.

저와 페어의 구현 의도를 이렇게 정리해 봤습니다.
감사합니다!! 🙇

2021-05-24 03:03 UTC, serverwizard requested changes
안녕하세요 인비!

빠르게 요청주셨네요~ 👍

몇가지 피드백 남겼으니 확인 부탁드릴게요 :)

2021-05-24 03:03 UTC, serverwizard commented on src/main/java/wooteco/subway/auth/ui/AuthenticationPrincipalOptionalArgumentResolver.java
> +        if (loginMember.getId() == null) {
로그인 여부를 LoginMember의 id로 판단하고 있는데, 그렇다면 loginMember로부터 값을 꺼내 비교하는 게 아니라 메시지를 던져 확인하는 건 어떨까요?

2021-05-24 03:03 UTC, serverwizard commented on src/main/java/wooteco/subway/auth/ui/AuthenticationPrincipalOptionalArgumentResolver.java
> +            return Optional.empty();
로그인이 되지 않은 경우 빈 객체를 반환할 수 도 있지만, 바로 에러를 낼 수는 없었을까요?

2021-05-24 03:03 UTC, serverwizard commented on src/main/java/wooteco/subway/line/application/LineService.java
>          persistLine.addSection(addInitSection(persistLine, request));
Line을 생성하고 addSection메소드를 이용할 수도 있지만, Line이 생성됐을 때 이미 sections까지 초기화가 됐다면 어떨까요?
```
Station upStation = stationService.findById(request.getUpStationId());
Station downStation = stationService.findById(request.getDownStationId());

Line persistLine = lineRepository.save(new Line(request.getName(), request.getColor(), upStation, downStation .... );
```

그리고 이렇게 했을 때와 이전의 차이점도 느껴보셨으면 해요!

2021-05-24 03:03 UTC, serverwizard commented on src/main/java/wooteco/subway/line/domain/Sections.java
> +            .orElse(null);
Optional로 리턴할 수도 있었을 것 같은데 null로 리턴한 이유가 있었을까요?

2021-05-24 03:03 UTC, serverwizard commented on src/main/java/wooteco/subway/path/domain/FareCalculator.java
> +        return getFareWithExtraFareOfSecondRange(currentFare, distance);
현재 구조에서 거리 별 요금계산 방법이 추가되면 새로운 if문을 추가될 것 같은데요. 이를 다형성을 이용해서 제거해볼 수는 없을까요? 
개인적으로 지금 드리는 코멘트는 정말 쉽지 않은 코멘트라는 생각이 들어서, 무조건 반영한다기 보다 고민을 많이 해보셨음 해요!

2021-05-24 03:03 UTC, serverwizard commented on src/main/java/wooteco/subway/path/domain/FareCalculator.java
> +        }
이 부분도 다형성을 이용할 수는 없을지 고민해보셨으면 해요.

2021-05-24 03:33 UTC, taehee-kim-dev commented on src/main/java/wooteco/subway/auth/ui/AuthenticationPrincipalOptionalArgumentResolver.java
> +            return Optional.empty();
비로그인 상태에서 경로를 조회했을 때에도 경로 조회 결과를 반환해 줘야 하기에 예외를 발생시키면 안된다고 판단했습니다.

그래서 이와 같은 방식으로 했는데요!
더 나은 방식이 있을까요??

2021-05-24 03:54 UTC, taehee-kim-dev commented on src/main/java/wooteco/subway/line/domain/Sections.java
> +            .orElse(null);
초기에 주어졌던 뼈대코드 부분이네요!!

Optional로 리턴하도록 수정했습니다!! :)

2021-05-24 03:57 UTC, taehee-kim-dev commented on src/main/java/wooteco/subway/auth/ui/AuthenticationPrincipalOptionalArgumentResolver.java
> +        if (loginMember.getId() == null) {
그 방법이 확실히 더 객체지향스러울 것 같아요!
반영했습니다. :)

2021-05-24 05:41 UTC, taehee-kim-dev commented on src/main/java/wooteco/subway/line/application/LineService.java
>          persistLine.addSection(addInitSection(persistLine, request));
반영했습니다!
Line의 생성자에서 sections까지 초기화 시키니, 
Line에 초기 sections가 무조건 존재할 수 밖에 없다는 안정성이 보장되네요!
좋은 피드백 감사합니다!! 🙇

2021-05-24 07:45 UTC, taehee-kim-dev commented on src/main/java/wooteco/subway/path/domain/FareCalculator.java
> +        return getFareWithExtraFareOfSecondRange(currentFare, distance);
if문 분기에 대한 고민이 있었는데, 좋은 피드백 감사합니다!!

인터페이스로 추상화 하여 다형성을 활용해 if문을 최대한 줄였습니다.

하지만, 인터페이스의 정적 팩토리 메서드에서 조건에 맞는 적절한 구현체를 반환해야 하기에 if문 사용이 불가피 했어요.

혹시 더 좋은 방법이 있을까요?

2021-05-24 07:45 UTC, taehee-kim-dev commented on src/main/java/wooteco/subway/path/domain/FareCalculator.java
> +        }
이 부분도 거리 별 추가요금 적용과 같은 방식으로 수정했습니다!!

더 좋은 방법이 있다면 알려주시면 감사하겠습니다!! 🙏

2021-05-24 07:47 UTC, taehee-kim-dev commented
### 안녕하세요, 게이츠!!

좋은 피드백 감사합니다.
나름 고민을 많이 해서 모두 반영했습니다.

제가 적용한 내용과 생각들을 코멘트의 대댓글로 남겼어요.
더 나은 방법이 있다면 알려주실 수 있을까요??

감사합니다!! 🙇

2021-05-27 23:35 UTC, serverwizard requested changes
인비 안녕하세요! 
구현 잘 해주셨네요 👍 

몇가지 피드백 남겼는데 확인 부탁드릴게요 
혹시 궁금한 점 있으면 언제든지 질문 주세요!

2021-05-27 23:35 UTC, serverwizard commented on src/main/java/wooteco/subway/auth/ui/AuthController.java
> +            return ResponseEntity.ok().body(token);
사소한거면 사소한 거지만, token 지역변수를 한 곳에서만 사용한다면 굳이 지역변수로 선언하지 않아도 될 것 같아요

2021-05-27 23:35 UTC, serverwizard commented on src/main/java/wooteco/subway/line/application/LineService.java
> +    private final SectionDao sectionDao;
LineService에서 SectionDao을 직접 의존할 수도 있지만, SectionService를 통해 SectionDao를 사용하게 할 수도 있을 것 같아요. 그리고 이렇게 했을 때 어떤 장점이 있을지도 생각해보면 좋을 것 같아요

2021-05-27 23:35 UTC, serverwizard commented on src/main/java/wooteco/subway/line/application/LineService.java
> +        if (!lineWithName.getId().equals(lineIdToUpdate)) {
객체에서 값을 조회해와서 로직을 처리할 수도 있지만, 객체에게 메시지를 던져 작업을 위임해보는 건 어떨까요?

2021-05-27 23:35 UTC, serverwizard commented on src/main/java/wooteco/subway/auth/ui/AuthenticationPrincipalOptionalArgumentResolver.java
> +            return Optional.empty();
비로그인 상태에서 경로 조회가 가능해야 하는 부분을 제가 인식하지 못했네요! 👍 

추가로 아래와 같이 구현해볼 수도 있겠네요. (아래 코멘트는 반영하지 않아도 됩니다 ^^)
만약 비로그인 사용자들도 이용해야 한다면, LoginMember -> User로 변경하고 User중에 GuestUser도 있을 수 있다는 사실을 표현해볼 수도 있겠네요~

```
public class User {
	public static final GuestUser GUEST_USER = new GuestUser();

         ....

	@JsonIgnore
	public boolean isGuestUser() {
		return false;
	}

	private static class GuestUser extends User {
		@Override
		public boolean isGuestUser() {
			return true;
		}
	}
}
```

2021-05-27 23:35 UTC, serverwizard commented on src/main/java/wooteco/subway/path/application/PathService.java
>              SubwayPath subwayPath = pathFinder.findPath(lines, sourceStation, targetStation);
pathFinder.findPath( ... ) 메소드를 호출할 때 인자를 추가로 더 넘겨서 SubwayPath 결과를 리턴 받았을 때 요금이 세팅되서 넘어오게 할 수는 없을까요?

2021-05-27 23:35 UTC, serverwizard commented on src/main/java/wooteco/subway/path/domain/fare/distance/DistanceFare.java
> +        }
이 부분을 말씀 드릴까 말까 고민하다가 고민은 한 번 해보는 게 좋을 것 같아 남겨요.

현재 distance별 요금 정책이 추가 될 때마다 if문이 늘어날 것 같은데요.
이러한 if문 구조를 다형성을 통해 해결할 수 있는데 이 방법을 한 번 고민만 해보셨음 해요!

2021-05-28 03:50 UTC, taehee-kim-dev commented on src/main/java/wooteco/subway/line/application/LineService.java
> +    private final SectionDao sectionDao;
Service 분리를 통해 책임을 나눌 수 있네요!
Service에서 다른 Service 참조를 할 때 순환참조만 생기지 않는다면 객체지향적으로 더 좋은 구조 같습니다.
반영했습니다!

2021-05-28 03:50 UTC, taehee-kim-dev commented on src/main/java/wooteco/subway/auth/ui/AuthController.java
> +            return ResponseEntity.ok().body(token);
반영했습니다!

2021-05-28 03:54 UTC, taehee-kim-dev commented on src/main/java/wooteco/subway/line/application/LineService.java
> +        if (!lineWithName.getId().equals(lineIdToUpdate)) {
객체지향으로 구현할 수 있겠네요!!
좋은 피드백 감사합니다. 🙇 
반영했습니다!

2021-05-28 04:13 UTC, taehee-kim-dev commented on src/main/java/wooteco/subway/path/application/PathService.java
>              SubwayPath subwayPath = pathFinder.findPath(lines, sourceStation, targetStation);
경로찾기에 요금 계산의 책임을 주는 방식이군요!
Service 레이어가 더 깔끔해지는 것 같아요.
반영했습니다!

2021-05-28 04:54 UTC, taehee-kim-dev commented on src/main/java/wooteco/subway/path/domain/fare/distance/DistanceFare.java
> +        }
Enum과 함수형 인터페이스, 다형성을 이용해 if문을 제거했습니다.
좋은 피드백 감사합니다!!! 🙇

2021-05-28 05:13 UTC, taehee-kim-dev commented
### 안녕하세요, 게이츠!

좋은 피드백 감사합니다.

말씀하신 대로 조금 더 객체지향적인 구조로 리팩토링 했습니다.

- 비즈니스 로직 객체 내부로 이동
- Service 분리 및 책임 위임
- Enum, 함수형 인터페이스, 다형성을 이용해서 요금 할인 정책의  if문 제거

감사합니다!! 🙇

2021-06-01 03:18 UTC, serverwizard approved these changes
안녕하세요, 인비!

피드백 잘 반영해주셨네요 💯 
특히 다형성, enum을 활용해 if문을 제거하신 부분 인상 깊었습니다.

이만 merge하겠습니다~ 
고생하셨습니다

2021-06-01 03:18 UTC, serverwizard commented on src/main/java/wooteco/subway/path/domain/fare/age/AgeFarePolicy.java
> +public enum AgeFarePolicy {
자바의 다형성, enum을 활용해 if문을 제거하셨네요 👍

2021-06-01 03:18 UTC, serverwizard commented on src/main/java/wooteco/subway/path/domain/fare/distance/DistanceFarePolicy.java
> +public enum DistanceFarePolicy {
자바의 다형성, enum을 활용해 if문을 제거하셨네요 👍

2021-06-01 03:18 UTC, merged

2021-06-02 01:52 UTC, taehee-kim-dev commented
학습로그
- https://velog.io/@taehee-kim-dev/%EC%9A%B0%EC%95%84%ED%95%9C%ED%85%8C%ED%81%AC%EC%BD%94%EC%8A%A4-3%EA%B8%B0-%EB%B0%B1%EC%97%94%EB%93%9C-Lv2-%EC%A7%80%ED%95%98%EC%B2%A0-%EB%AF%B8%EC%85%98-%ED%95%99%EC%8A%B5%EB%A1%9C%EA%B7%B8