[스프링 - 협업 미션] 루트(김준근) 미션 제출합니다.
woowacourse/atdd-subway-fare pull request #21
Opened 2021-05-29 08:05 UTC by Junroot

안녕하세요 데이브! 루트입니다!

이번 미션을 진행하면서 고민하게된 점들이 몇개 있는데 데이브의 의견이 궁금하네요!

## DTO의 검증

이번 미션을 진행하면서 프론트의 요구사항을 처리해주기 위해 Spring boot validation을 사용해봤습니다. 이 라이브러리의 경우는 DTO에 어노테이션을 붙이는 형식으로 구현을 해주는데 이 때, 저는 한 가지 의심이 들었습니다. DTO는 단순히 컨트롤러에 값을 전달하는 역할을 하는 객체인데 검증이 포함되어도 되는지에 대한 것이었습니다. 
저는 지금까지 검증과정도 하나의 비즈니스 로직이라고 생각해서 모든 검증을 서비스 레이어에서 처리했습니다. 하지만 이 경우에는 검증 과정이 DTO와 서비스레이어에 혼용되어 포함되어있어 이게 맞는 방법일지 의문이듭니다. 이에대해 데이브는 어떻게 생각하시나요?

## properties 파일 관리 방법

이전 미션까지는 아무 생각없이 properties 파일을 함께 git에 커밋하고 관리했습니다. 하지만 이번 미션에서 여러개의 profile을 만들어주면서, '과연 properties 파일을 git에 함께 올리는것이 맞을까?'라는 생각이 들었습니다. properties 파일에는 db의 패스워드와 jwt의 secret key도 함께 포함되어 있어서 이를 그대로 커밋하면 보안에 위험이 있을거라는 생각이 듭니다. 현업에서는 이런 경우 어떻게 처리하고 관리하는지 궁금합니다.

## 선택적인 로그인 상태를 가질 때 처리 방법

이번 4단계 미션에서 로그인 상태인 경우 나이를 반영하여 요금을 조회하는 요구사항이 있었습니다. 즉, 로그인이 되어도 안되어도 사용 가능한 기능이 필요했습니다. 이를 어떻게 구현할지 고민하다가, ArgumentResolver에서 토큰이 존재하지 않으면 널객체를 반환하도록 구현을 했습니다. 이 방법말고 다른 깔끔한 방법이 있을지 궁금합니다. 현재로썬 좋은 방법이 떠오르지 않네요 😂

2021-05-31 22:00 UTC, dave915 commented
>이번 미션을 진행하면서 프론트의 요구사항을 처리해주기 위해 Spring boot validation을 사용해봤습니다. 이 라이브러리의 경우는 DTO에 어노테이션을 붙이는 형식으로 구현을 해주는데 이 때, 저는 한 가지 의심이 들었습니다. DTO는 단순히 컨트롤러에 값을 전달하는 역할을 하는 객체인데 검증이 포함되어도 되는지에 대한 것이었습니다.
저는 지금까지 검증과정도 하나의 비즈니스 로직이라고 생각해서 모든 검증을 서비스 레이어에서 처리했습니다. 하지만 이 경우에는 검증 과정이 DTO와 서비스레이어에 혼용되어 포함되어있어 이게 맞는 방법일지 의문이듭니다. 이에대해 데이브는 어떻게 생각하시나요?

사실 엄청 타이트하게 하면 모든 Layer에서 유효성 체크를 해야한다고 알고 있어요. 그런데 보통 dto를 서비스 까지 끌고 들어가거나 Controller, Service를 1:1로 사용하는 경우가 많아서 Controller에서만 체크하는 분들도 있더라구요! 
저 같은 경우엔 조금 유연한 처리가 필요할땐 Service Layer에서, 나머지 경우엔 Dto에서 체크해주고 있습니다.

>이전 미션까지는 아무 생각없이 properties 파일을 함께 git에 커밋하고 관리했습니다. 하지만 이번 미션에서 여러개의 profile을 만들어주면서, '과연 properties 파일을 git에 함께 올리는것이 맞을까?'라는 생각이 들었습니다. properties 파일에는 db의 패스워드와 jwt의 secret key도 함께 포함되어 있어서 이를 그대로 커밋하면 보안에 위험이 있을거라는 생각이 듭니다. 현업에서는 이런 경우 어떻게 처리하고 관리하는지 궁금합니다.

말씀 주신대로 민감한 정보 같은 경우엔 properties 파일에 저장하지않고 `Vault` 같은 것들을 이용해 어플리케이션이 실행될때 `db password`나 `jwt secret key`를 외부로부터 갖고오도록 하고 있어요.
때로는 코드 저장소가 내부망에 있고, 디비 접속 권한도 따로 받기 때문에 그냥 properties 파일에 그냥 쓰는 곳도 있는것으로 알고 있어요.

>이번 4단계 미션에서 로그인 상태인 경우 나이를 반영하여 요금을 조회하는 요구사항이 있었습니다. 즉, 로그인이 되어도 안되어도 사용 가능한 기능이 필요했습니다. 이를 어떻게 구현할지 고민하다가, ArgumentResolver에서 토큰이 존재하지 않으면 널객체를 반환하도록 구현을 했습니다. 이 방법말고 다른 깔끔한 방법이 있을지 궁금합니다. 현재로썬 좋은 방법이 떠오르지 않네요 😂

다른 크루 보니까 Guest User 로 구현하셨더라구요. 이 방법은 어떠신가요?

2021-05-31 22:16 UTC, dave915 requested changes
루트 안녕하세요! 리뷰가 늦었네요 🙇‍♂️
미션 구현 잘 해주셨네요! 
질문에 관한 코멘트와 몇가지 피드백 남겼습니다.
궁금한점 있으면 언제든지 질문 주세요 :)

2021-05-31 22:16 UTC, dave915 commented on src/main/java/wooteco/subway/config/SwaggerConfig.java
> +    public Docket api() {
DM에서 드렸던 피드백 기록차 남겨둘게요! 

로그인 제한이 걸려있는 api 는 swagger로 어떻게 요청 하셨나요?
swagger에서 jwt토큰을 추가해서 요청하도록 할 수 있어요. 아래 링크 참고해보세요!
https://kimyhcj.tistory.com/363

2021-05-31 22:16 UTC, dave915 commented on build_script.sh
> +ssh -i $CERTIFICATE_PATH -l $USER $HOST "PID=\$(ps -p \$(lsof -ti tcp:8080) o pid=); kill -15 \$PID; nohup java -Dspring.profiles.active=$DEPLOY -jar $LOCATION/$JAR_NAME > subway.out 2> subway.err <
`> subway.out 2> subway.err < /dev/null` 
이 부분은 로그 파일을 만들려고 사용한 부분일까요? 
logback fileappender 관련해서 찾아봐도 좋을 것 같아요 :)

2021-05-31 22:16 UTC, dave915 commented on src/main/java/wooteco/subway/path/ui/dto/PathResponseAssembler.java
> +        int fare = subwayPath.fare(loginMember).intValue();
path의 거리를 조회하기 위한 `subwayPath.fare` 호출도 비즈니스 로직이라고 생각이 드는데, 
domain -> dto 변환해주는 `PathResponseAssembler` 내부에서 호출 해야 할지 고민이네요 🤔

Path를 조회 하고 Path에 대한 금액을 책정한다. 는 Service에 있어야 하지 않을까요?

2021-05-31 22:16 UTC, dave915 commented on src/main/java/wooteco/subway/path/domain/Fare.java
> +            farePolicy -> farePolicy.calculate(distance)
모든 요금정책의 `calculate`를 모두 실행 시키는 부분이 마음에 조금 걸리네요. 
지금은 가벼운 로직들이지만 만약 로직이 무거워 진다면 비효율적이지 않을까요?

2021-05-31 22:16 UTC, dave915 commented on src/main/java/wooteco/subway/path/domain/SubwayPath.java
> +    private final Fare fare;
`SubwayPath`의 요금이라는 의미로 `Fare`로 넣은것이 맞을까요? 
Fare내부를 보면 금액 계산에 필요한 정책만 들고 있는데, 이를 모든 `SubwayPath` 에서 들고 있을 필요가 있나 싶어요!

2021-06-01 01:23 UTC, Junroot commented on src/main/java/wooteco/subway/path/domain/SubwayPath.java
> +    private final Fare fare;
생각해보니 현재 `Fare`는 경로에 따라 요금을 계산해주기 때문에, `SubwayPath`에서 상태로 가지고 있는게 어색하게 느껴지네요!! 오히려 반대로 주입되는 것이 더 맞을 것 같아요! 한 번 수정해보겠습니다!

2021-06-01 01:39 UTC, Junroot commented on src/main/java/wooteco/subway/path/domain/Fare.java
> +            farePolicy -> farePolicy.calculate(distance)
조건을 만족하는 정책만 계산되도록 수정해보라는 의미일까요? 🤔
일단 이렇게 수정해보겠습니다!

2021-06-01 10:54 UTC, Junroot commented on build_script.sh
> +ssh -i $CERTIFICATE_PATH -l $USER $HOST "PID=\$(ps -p \$(lsof -ti tcp:8080) o pid=); kill -15 \$PID; nohup java -Dspring.profiles.active=$DEPLOY -jar $LOCATION/$JAR_NAME > subway.out 2> subway.err <
따로 의도한 것은 아니지만 logback fileappender를 사용해보았습니다.
사용자 정의 로그백으로 request와 response를 어떻게 로깅하는지 몰라서, 일단은 `logback-access.xml`로 처리를 해봤습니다 ㅠㅠ

2021-06-01 12:03 UTC, Junroot commented on src/main/java/wooteco/subway/config/SwaggerConfig.java
> +    public Docket api() {
구현해봤는데 제가 제대로 한건지 잘모르겠네요 😅

2021-06-03 02:03 UTC, dave915 requested changes
루트 안녕하세요! 
피드백 반영한 부분 확인했습니다 👍 
간단한 피드백 남겼어요. 확인 부탁드릴게요!  
궁금한 점 있으면 언제든 질문 주세요!

2021-06-03 02:03 UTC, dave915 commented on src/main/java/wooteco/subway/path/application/PathService.java
> +            BigDecimal calculatedFare = fare.calculate(subwayPath, loginMember);
👍  메소드 분리도 해주면 더 좋을 것 같아요!

2021-06-03 02:03 UTC, dave915 commented on src/main/java/wooteco/subway/path/domain/Fare.java
> +            .filter(extraFarePolicy -> extraFarePolicy.isSatisfied(distance))
👍

2021-06-03 02:03 UTC, dave915 commented on src/main/resources/logback-access.xml
> +    <appender name="FILE" class="ch.qos.logback.core.FileAppender">
👍
추가로 RollingFileAppender 라는걸 쓰면 로그파일을 날짜 별로 분리 할 수도 있어요 :)

https://kouzie.github.io/spring/logback/#logback-xml-%EC%84%A4%EC%A0%95

2021-06-03 02:03 UTC, dave915 commented on src/main/resources/logback-access.xml
> +    <appender name="FILE" class="ch.qos.logback.core.FileAppender">
`logback-access.xml` 은 access log 만 남는 것 같네요! 
`logback.xml` 에 아래처럼 해보세요! `logHome` 은 수정해주세요! 

```
<configuration debug="true">
    <property name="logHome" value="/atdd-subway-fare/log" />

    <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder class="ch.qos.logback.classic.encoder.PatternLayoutEncoder">
            <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n</pattern>
        </encoder>
    </appender>

    <appender name="fileAppender" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <filter class="ch.qos.logback.classic.filter.ThresholdFilter">
            <level>DEBUG</level>
        </filter>
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>${logHome}/%d{yyyyMMdd}/subway.%d{yyyyMMdd}.%i.log</fileNamePattern>
            <timeBasedFileNamingAndTriggeringPolicy class="ch.qos.logback.core.rolling.SizeAndTimeBasedFNATP">
                <maxFileSize>15MB</maxFileSize>
            </timeBasedFileNamingAndTriggeringPolicy>
        </rollingPolicy>
        <encoder>
            <Pattern>
                %d{yyyy-MM-dd HH:mm:ss.SSS} %thread %-5level %logger - %m%n
            </Pattern>
        </encoder>
    </appender>

    <root level="info">
        <appender-ref ref="STDOUT" />
        <appender-ref ref="fileAppender" />
    </root>

</configuration>
```

2021-06-03 02:03 UTC, dave915 commented on src/main/java/wooteco/subway/config/SwaggerConfig.java
> +            .securitySchemes(Lists.newArrayList(apiKey()));
👍

2021-06-03 02:03 UTC, dave915 commented on src/main/java/wooteco/subway/path/application/PathService.java
> +            BigDecimal calculatedFare = fare.calculate(subwayPath, loginMember);
다시 보니까 Fare를 매번 생성해줄 필요가 있을까 싶기도 하네요!

2021-06-06 08:08 UTC, dave915 approved these changes
루트 안녕하세요! 
피드백 반영 한 부분 확인 했습니다! 
그동안 고생하셨습니다. 이만 머지할게요! 
궁금한 점 있으면 언제든 DM주세요 :)

2021-06-06 08:08 UTC, dave915 commented on src/main/java/wooteco/subway/path/application/PathService.java
> +        this.fare = new Fare(FarePolicyFactory.createExtraFarePolicy(),
👍

2021-06-06 08:08 UTC, merged

2021-06-15 15:43 UTC, Junroot commented
# 학습 로그
## Spring boot validation
- Spring boot 에서 제공하는 validation을 통해 어노테이션 기반으로 Bean Validation을 할 수 있었다.
- http://wiki.gurubee.net/pages/viewpage.action?pageId=12189867
- https://sanghye.tistory.com/36
## 태그
- Spring, validation

##  Swagger
- Swagger를 통해 서버에서 제공하고 있는 API를 자동으로 문서화시켜 HTML로 볼 수 있도록 구현했다.
- Swagger를 통해 프론트가 쉽게 jwt 토큰을 이용하여 테스트할 수 있도록 했다.
- https://jojoldu.tistory.com/31
- https://kimyhcj.tistory.com/363
## 태그
- Documentation

## Logback
- 자바 오픈소스 로깅 프레임 워크인 SLF4J의 구현체
- SLF4J는 추상화 클래스로 단독으로 사용하지 못한다.
- spring-boot-start-web 안에 spring-boot-starter-logging 구현체가 있어서 logback을 사용할 수 있다.
- 기본적은 자바 프로그램은 logback.xml 을 사용하지만, 로그백을 스프링에서 확장해서 사용한다면 (프로필 별 구성 등) logback-spring.xml을 사용해야된다.
- 표준 logback.xml구성 파일이 너무 일찍로드 되기 때문에 확장을 사용할 수 없다.  logback-spring.xml을 사용하거나  logging.config를 정의해야 한다.
- [https://goddaehee.tistory.com/206](https://goddaehee.tistory.com/206)
- [https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.logging.logback-extensions.profile-specific](https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.logging.logback-extensions.profile-specific)
- [http://logback.qos.ch/manual/appenders.html](http://logback.qos.ch/manual/appenders.html)