[스프링 - 협업 미션] 에어(김준서) 미션 제출합니다.
woowacourse/atdd-subway-fare pull request #29
Opened 2021-05-29 15:34 UTC by KJunseo

안녕하세요 제이!! 이번 미션을 함께하게 된 에어라고 합니다! 처음 뵙네요!
한 번 꼭 만나뵙고 싶었는데 레벨2 마지막 미션을 함께하게 되었네요 ㅎㅎ
대단히 반갑습니다! 리뷰 잘 부탁드려요!! 🙏🙏🙏

### 배포 url: https://air-subway.p-e.kr/ 

<hr>

이번에 처음으로 프론트 크루들과 같이 협업을 해봤는데 상당히 재미있었어요.
같이 의논하여 기본 API명세를 참고하여 저희 팀에 맞게 API 명세를 작성해보고, 명세에 맞게 구현했습니다.
저희 팀은 [GitHub에 subway-wiki](https://github.com/unluckyjung/subway-wiki/wiki)라는 저장소를 만들어 api 명세를 관리했습니다!

이번에 ec2 서버에 실제로 서비스를 배포해봤어요. 아래 구조와 같이 ec2 인스턴스를 구성해봤습니다!
<img width="738" alt="스크린샷 2021-05-29 오후 11 47 23" src="https://user-images.githubusercontent.com/45876793/120074590-89111880-c0d8-11eb-96e7-a0c604686500.png">

배포도 처음에는 너무 막막했는데, 실제로 구조대로 완성하고 잘 돌아가는 것을 보니까 재밌네요ㅎㅎ

이번에 거리에 따른 요금, 로그인 한 유저 나이에 따른 요금을 계산하는 것을 enum과 전략패턴을 사용해서 구현해봤어요.
2가지의 enum(DistanceType, AgeType)을 통해서 각각 거리에 따른 요금 정책, 유저 나이에 따른 요금 정책을 반환받아, Fare 객체에 2가지 전략을 주입하는 식으로 구현해봤습니다! 이 과정에서 한 가지 궁금증이 생겼는데 하단에 적어놓을게요!!

뼈대코드에 대한 테스트는 따로 추가하지 않았고, 새로 추가한 도메인이나, 기능에 대한 테스트만 추가하였습니다!

### 궁금증

Q1. 환경 설정을 분리하는 법을 찾아보다가, yml 파일은 한 개의 yml 파일에서 `---` 으로 프로파일 별로 나눠서 환경 설정을 할 수 있다는 것을 보고 이번에 하나의 yml 파일로 환경설정을 나눠봤어요! 실무에서는 보통 환경설정 별로 파일을 나눠서 처리하는지, 하나의 yml로 관리하기도 하는지 궁금해요! 지금 생각은 prod 환경설정은 따로 분리하는 게 좋을 것 같지만, 나머지 프로파일들은 하나로 묶어서 관리해도 되지 않을까라는 생각이 들기도 하네요. 

Q2. 현재 코드에 변경 사항이 생기면 `ec2접속` -> `git pull` -> `build` -> `원래 실행되고 있던 jar 파일 kill` -> `새로 build 된 jar 파일 재실행` 이 과정을 진행하는데요. 이렇게 하면 결국 애플리케이션이 중단되는 시간이 생길 수 밖에 없을 것 같아서, 점검 시간 등을 공지하고 처리해야할 것 같다는 생각이 들어요. 다른 크루들과도 이야기를 나눠봤지만, 보통 실무에서는 어떻게 진행되는지 궁금해요!  

Q3. 이번에 Line 테이블에 `extraFare`라는 추가 필드가 들어가는 과정이 있었어요. schema.sql을 변경해주고 코드도 수정한 후, 재배포 했는데, ec2 서버에 존재하는 DB의 Line 테이블에는 `extraFare`라는 필드가 존재하지 않아, 400 에러가 발생했었어요. 결국 ec2 서버의 Line 테이블을 drop하고 다시 애플리케이션을 실행시키니까 잘 되긴했어요. 하지만 이게 옳은 방법은 아닌 것 같아요. 운영 중에는 기존 데이터를 다 날리면 절대 안될 것 같아요. 그래서 궁금한 것이 새로운 필드가 DB에 추가될 경우 기존 테이블에 새로운 필드를 추가하는 방법과, DB 테이블이 변경된 후에, 기존에 들어가 있던 데이터에는 해당 필드 값이 없을 텐데 이럴 경우, 어떻게 기존 데이터들에 추가된 필드 값을 채워주는 지 궁금해요!

Q4. 이번 요구 사항에 로그인 / 비로그인 을 확인해서 요금을 계산하는 과정이 있었어요. 저희는 기존 뼈대 코드의 `ArgumentResolver`를 조금 변형해서 사용했어요. `ArgumentResolver`로 반환한 객체가 `LoginMember(null, null, 0)`인 경우를 비 로그인상태라고 생각하고 처리했는데, 이 방식이 좋은 방식인지에 대한 확신이 없네요 ㅠㅠ

Q5.  
>이번에 거리에 따른 요금, 로그인 한 유저 나이에 따른 요금을 계산하는 것을 enum과 전략패턴을 사용해서 구현해봤어요.
>2가지의 enum(DistanceType, AgeType)을 통해서 각각 거리에 따른 요금 정책, 유저 나이에 따른 요금 정책을 반환받아, Fare 객체에 2가지 전략을 주입하는 식으로 구현해봤습니다! 이 과정에서 한 가지 궁금증이 생겼는데 하단에 적어놓을게요!!

부분에 관련된 질문입니다! 나이에 따른 요금을 계산하는 방법은 크게 문제가 없다고 생각하는데, 거리에 따른 요금 계산을 할 때가 조금 문제가 있어요.

요구 사항이 아래와 같아요.
>1) 10km 이내 -> 1250원
>2) 10km ~ 50km -> 5km마다 100원
>3) 50km 초과 -> 8km마다 100원

그래서 만약 50km가 넘는 거리에 대한 요금을 계산해야하는 경우, 결국 1) 2) 3) 이 모두 필요하게 되더라고요. 
현재 거리에 따른 요금을 계산해주는 정책은 총 거리를 받아서 기본 요금에 **추가해 줄 요금**을 반환해줘요.

 2)와 3) 정책에서는, `들어온 거리 - 이미 계산한 거리`를 해주고 나머지 계산을 해주는데, 만약 `10km ~ 50km`가  `10km ~ 60km`로 바뀐다던지 하면 `들어온 거리 - 이미 계산한 거리` 계산을 하는 정책 클래스를 전부 고쳐야 하더라구요.. 유지 보수를 좋게 하기 위해 if문 분기를 하지 않고, 분리를 했는데 어떻게 발전시켜야할지 잘 떠오르지 않아 제이의 도움을 구해봅니다.🙏 

<hr>
적다보니 길어졌네요 ㅠㅠ

설명도 제대로 한 지 잘 모르겠습니다. 질문 중에 혹시라도 이해 안 되시는 부분있으면 바로 연락주세요!!
리뷰 잘 부탁드려요!!! 😄😄😄

2021-05-31 14:31 UTC, JunHoPark93 requested changes
안녕하세요 에어!
미션 잘 구현해주셨어요 🙇‍♂️
몇가지 피드백 남겼는데 확인부탁드려요.
질문주신부분들은 코멘트로 남겨두었습니다 🙏

2021-05-31 14:31 UTC, JunHoPark93 commented on src/main/resources/application.yml
> +  config:
첫번째 질문주신부분입니다!
팀마다 다릅니다. 어떤 프로젝트는 한통에 다 들어있기도하고, 어떤 프로젝트드는 yml을 환경별로 나누어 놓기도해요.
한통으로 관리하면 그 파일만 보면 되는 장점이 있는가하면 환경별로 새롭게 추가되는 경우 혹시나 빼먹을 수 있는 우려도 있어요.
그래서 어떤 팀은 yml을 명시적으로 다 분리시켜놓아 빼먹지 않게 의도적으로 신경쓰는 곳도 있습니다 :)

2021-05-31 14:31 UTC, JunHoPark93 commented on src/main/resources/schema.sql
> +    extraFare int,
세번째 질문주신부분입니다!
좋은 지적을 해주셨어요 👍
테이블을 수정하지 않고 엔티티코드만 수정해서 배포하는것은 매우 위험합니다.
실제로는 미리 컬럼추가작업이 선행이되고 앱을 배포합니다. 그리고 나서는 배치작업 혹은 수동으로 칼럼의 값들을 밀어넣게됩니다.
테이블의 크기가 클경우 칼럼추가작업도 그냥 해서는안되고 서비스특성상 부하가 적은시간대에 모니터링과 함께 진행되게됩니다.

2021-05-31 14:31 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/member/domain/LoginMember.java
> +    public LoginMember(Long id, String email, int age) {
네번째 질문주신부분입니다!
권한 관련내용들이 등장하지 않는이상 현재구조로 Id가 null인경우로 판단하는게 나을거같긴하네요 😢
만들어주신 isPresent()처럼 권한이 없는 LoginMember를 생성하는 정적메서드를 만들어보는것도 방법이 될거같아요 :)

2021-05-31 14:31 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/domain/fare/distance/DistanceType.java
> +    TEN_TO_FIFTY(new TenToFiftyStrategy(), (distance) -> distance > 10 && distance <= 50),
개인차가 있을 수 있지만 Strategy클래스 네이밍에 비지니스용어를 사용하면 더 좋다고생각해요 :)
Child... Teenager... 같은 네이밍으로요. 이거는 참고만해주세요!

2021-05-31 14:31 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/domain/fare/Fare.java
> +    }
fare 인스턴스변수를 유지할 필요가있을까요? 🤔
중간연산으로만 쓰이고 바로 ageStrategy에 넘겨주고있네요

2021-05-31 14:31 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/domain/fare/Fare.java
> +    }
Fare의 역할이 vo로써 사용을하는것인지, 전략을 받아서 무언가를 하는것인지 불분명합니다.
외부에서 계산된 값을 받아서 전달만 하는 역할을 의도하셨을까요?

2021-05-31 14:31 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/application/PathService.java
> +            return PathResponseAssembler.assemble(subwayPath, fare.calculate(distance));
calculateFare로 Fare라는걸 온전히 만들어준거같은데 아래에 fare.calculate를 또해주고있어요. 위에 언급드린 Fare를 개선해보면 불분명함을 줄일 수 있을거같아요!

2021-05-31 14:31 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/domain/fare/distance/OverFiftyStrategy.java
> +        distance -= MAX_DISTANCE;
마지막 질문주신 부분과 관련이 있는거같아요!
다른 전략클래스를 안에서 new를 해주고있어요. 결과적으로 변경이 일어날때마다 다 찾아서 바꿔줘야 될거같아요.
오히려 상속구조로 풀어나가면 중복을 없앨 수 있지 않을까요? 🤔

2021-05-31 14:36 UTC, JunHoPark93 commented
> Q2. 현재 코드에 변경 사항이 생기면 ec2접속 -> git pull -> build -> 원래 실행되고 있던 jar 파일 kill -> 새로 build 된 jar 파일 재실행 이 과정을 진행하는데요. 이렇게 하면 결국 애플리케이션이 중단되는 시간이 생길 수 밖에 없을 것 같아서, 점검 시간 등을 공지하고 처리해야할 것 같다는 생각이 들어요. 다른 크루들과도 이야기를 나눠봤지만, 보통 실무에서는 어떻게 진행되는지 궁금해요!

넵 맞습니다. 말씀주신대로 하면 중단이 일어나게되어요. 저희팀은 2가지를 사용을하는데요, 
실제로는 한벌의 서버를 더 띄워두고 일시에 라우팅을 돌리는 방법을 사용하구요 (블루그린)
사용자 api를 직접 맞지 않는 서버들은 순차적으로 (예를들어 2개씩) 죽이고 띄우고를 반복해서 배포하는 방식도 있습니다. (롤링)

일단은 무중단배포에 대해서 서칭해보시면 좋을거같아요 🙏 추후 프로젝트 진행하실때 하시게될수도있구요!

2021-06-01 08:54 UTC, KJunseo commented
제이 리뷰 잘 받았어요 ㅎㅎ 감사합니다!🙏
피드백 반영해봤습니다!

- 비 로그인 사용자를 판별 할 때 LoginMember.anonymous()를 통해 LoginMember(null, null, 0)를 비교하여 처리했습니다!
- Fare 도메인을 수정해봤는데, 의도하신 방향과 맞는지 한 번 확인해주시면 감사하겠습니다!
- 거리에 따른 요금 계산 구현을 `책임 연쇄 패턴`을 적용해서 한 번 처리해봤어요! 이 부분도 의견 남겨주시면 감사하겠습니다!!

리뷰 잘 부탁드려요~~🙏🙏🙏

### 궁금증
Q. 크루들과 이야기를 나누다가 궁금한 점이 생겼어요. static을 사용하게 되면 객체 지향 적이지 못하다는 글을 많이 봤어요. 그런데 enum을 사용하게 되면, enum에 메서드를 두면, static 메서드가 생기는데 그럼 enum도 객체 지향적이지 못하지 않나? 라는 생각이 들었어요. 정적팩토리메서드는 객체를 생성하는 것이라 static이어도 객체 지향적이라고 볼 수 있다는 생각이 들긴해요. 아직 객체 지향에 대해 저 만의 확실한 기준이 없다는 생각이 들긴하는데, 제이의 의견이 궁금해요!

2021-06-02 13:22 UTC, JunHoPark93 approved these changes
안녕하세요 에어!
리뷰 반영하느라 고생많으셨어요 🙇‍♂️
질문주신 부분은 코멘트로 남겨두었습니다.
앞으로의 미션에 도움이 되었기를 바랍니다 🙏

2021-06-02 13:22 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/domain/fare/distance/ChainOfDistance.java
> +    public ChainOfDistance() {
이런방법도있군요!
지난번게 더 가독이 좋은거같긴한데 새로운것을 시도해보는것도 좋네요 :)

2021-06-02 13:22 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/dto/PathResponseAssembler.java
> +        int totalFare = fare.calculate(subwayPath.extraFare(), distance);
Fare가 조금더 명확해졌네요!

2021-06-02 13:22 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/member/domain/LoginMember.java
> +    private static final LoginMember anonymous = new LoginMember();
마지막 질문주신 static입니다!
객체지향에서 안티패턴이라고들 하더라고요. 말씀주신 enum도 그런측면에서 봤을때는 그렇죠.
어떤 문제를 해결하는데 소위말하는 객체지향적으로 하기위해서(예를 들어 에어가 말씀주신 팩토리) 여러 수단을 동원하는데 그 수단까지 엄격한 기준으로 바라볼거야 말거야의 차이인거같아요. 

사실 저도 객체지향이 뭐다 명확히 이야기하기가 힘드네요. 
안티패턴이다에 대한 내용에 동의는 하나 쓰지말아야지라고 생각하진않아요. enum을 썼을때의 장점이 크고 이를 이용하여 코드자체를 유지보수하기 좋게 만들어놓는다면 크게 상관하지 않습니다.
답변이 조금 부족했다면 다시 말씀주세요~

2021-06-02 13:22 UTC, merged

2021-06-03 02:03 UTC, KJunseo commented
# [학습로그] 스프링 - 협업미션

총 정리 : [[새배내] 스프링 - 협업 미션을 하면서 새로 배운 내용](https://velog.io/@max9106/wtc-learning9)

## Docker
컨테이너 기반의 오픈소스 가상화 플랫폼. 서버 내에 많은 컨테이너를 두고, 각 컨테이너로 다양한 프로그램이나 실행환경을 추상화 한 것이다. 동일한 인터페이스를 제공하여 프로그램의 배포 및 관리를 단순화 시켜준 것이다.

(추가하기)

## 태그
Docker

<hr>

## Dockerfile vs docker.compose.yml
### Dockerfile
이미지를 실행하면서 특정 작업까지 같이 처리하게 해주는 도구. 사용자가 이미지를 조립하기 위해 호출 할 수 있는 명령이 포함된 간단한 텍스트 파일

### docker.compose.yml
다수의 컨테이너를 쉽게 실행할 수 있게 도와주는 도구.

-> docker-compose로 컨테이너를 자동 생성한 후, Dockerfile 생성한 컨테이너 안에 자동을 세팅 작업까지 돌아가게 할 수 있다. docker-compose.yml에서 모든 것을 정의할 수도 있지만, Dockerfile과 docker-compose.yml을 모두 사용하면 더 효율적이다.

1) 이미지 파일들을 빌드하기 위한 Dockerfile 생성
2) docker-compose.yml 내에서 해당 Dockerfile 이미지를 기반으로 복잡한 스택 처리
3) docker compose 명령어로 전체 스택 배포

## 태그
Docker

<hr>

## 해싱
보통 비밀번호는 해싱해서 db에 저장한다.

해싱 알고리즘을 통해 비밀번호를 해싱하는데, 해싱은 **단방향**이므로 원래대로 돌릴 수는 없다. 그래서 비밀번호를 비교할때 들어온 비밀번호값도 해싱 후 비교한다.

이때 보안을 위해서 salt를 사용한다. salt란 비밀번호에 추가로 다른 값을 넣는 걸 말한다. 해싱할때 값이 조금만 달라져도 해싱값이 완전 바뀌기 때문에 해커들이 찾기 어려워진다. 이때 salt 값은 db에 같이 저장해둔다. 로그인 할 때 해당 salt값을 통해 해싱해야하기 때문이다.

또 keyChain이라는 작업도 해준다. 서버에서 횟수를 정해놓고, 해싱한 결과값을 해당 횟수만큼 해싱을 또 하는 것이다. 이렇게하면 원래 비밀번호를 알기 더욱 어려워진다.

## 태그
해싱

<hr>

## AOP
aop란 관점 지향 프로그래밍을 뜻한다. 간단하게 AOP 비즈니스 로직과 분리되는 횡단 관심사를 분리하는 방식이다. 

흔히 로그를 찍을 때 많이 사용한다. 로그가 필요한 메서드 마다 똑같은 로그찍는 코드를 하나하나 추가해주는 것은 매우 비 효율적이다. 이럴때 aop를 사용한다.

예외를 잡을 때 사용하는 @ControllerAdvice 또한 aop를 이용하는 방식이다.

(추가하기)

## 태그
aop

<hr>

## CORS & Preflight
### CORS
Cross-Origin Resource Sharing의 약자로 브라우저에서 실행 중인 스크립트에서 시작되는 cross-origin HTTP 요청을 제한하는 브라우저 보안 기능을 말한다.

아래의 4가지 경우에 요청을 차단한다.
- 다른 도메인
- 다른 하위 도메인
- 다른 포트
- 다른 프로토콜

### Preflight
요청을 미리 보내보는 것이다.

기본적으로 브라우저는 cross-origin 요청을 전송하기 전에 OPTIONS 요청으로 preflight를 먼저 전송한다.

OPTIONS 요청의 응답으로 Access-Control-Allow-Origin(어떤 origin을 허용하는지), Access-Control-Allow-Methods(어떤 method를 허용하는지)가 넘어온다.

브라우저가 결과를 확인하고 난 후, cross-origin 요청을 보낸다.

그렇다고 매 요청시 preflight를 보내는 것은 아니다. 서버 설정을 통해 preflight 결과를 캐싱해둔다. 이 정보가 있는 동안은 preflight를 생략하고 요청을 바로 보낼 수 있다.

## 태그
cors, preflight

<hr>

## HTTP 상태코드(301 & 302 vs 307 & 308)
301, 302는 리다이렉트 시 http method를 GET요청으로 변환한다.
307, 308은 리다이렉트 시 http method를 그대로 유지해준다.

따라서 get요청 시는 상관없지만 post 요청 시는 리다이렉트 되면서 메서드가 get으로 바뀌어버려 오류가 날 수 있다.

예를 들어 http요청을 https로 리다이렉트 시킬때, 301, 302를 사용하면, `POST http://~` 요청이 `GET https://~`로 리다이렉트 되지만, 307, 308을 사용하면 `POST http://~` 요청이 `POST https://~`로 리다이렉트 된다.

301은 308과 유사하고, 302는 307과 유사하다. 301, 308은 영구적인 리다이렉트를 뜻하고, 302, 307은 임시 리다이렉트를 뜻한다.

## 태그
http

<hr>

## ApplicationContext
스프링 애플리케이션 전반에 걸쳐 모든 구성요소의 제어 작업을 담당하는 IoC 엔진. 빈을 생성하고 관계를 설정하는 일종의 빈 팩토리라고 볼 수 있다.(빈 팩토리를 좀 더 확장한 개념으로 ApplicationContext 인터페이스는 BeanFactory 인터페이스를 상속한 서브인터페이스이다.)

실제로 스프링 컨테이너 또는 IoC 컨테이너라고 말하는 것은 바로 이 ApplicationContext 인터페이스를 구현한 클래스의 객체이다.

애플리케이션 컨텍스트는 별도의 정보를 참고하여 빈의 생성, 관계 설정 등의 제어를 총괄한다.

또한 싱글톤을 저장하고 관리하는 싱글톤 저장소이다. 스프링은 기본적으로 내부에서 생성하는 빈 객체를 모두 싱글톤으로 만든다.

## 태그
ApplicationContext

<hr>

## on delete cascade
외래키로 연결된 튜플을 같이 삭제해주는 sql 문법이다.
```sql
create table if not exists SECTION
(
    id bigint auto_increment not null,
    line_id bigint not null,
    up_station_id bigint not null,
    down_station_id bigint not null,
    distance int not null,
    primary key(id),
    foreign key (up_station_id) references station(id),
    foreign key (down_station_id) references station(id),
    foreign key (line_id) references line(id) on delete cascade -- line 이 지워지면 section도 지워짐.
);
```
위의 예시로는 Section이 foreign key로 Line을 가리키고 있을 때, Line을 삭제하면 Section 도 같이 삭제된다.

## 태그
sql 

<hr>

## VPC
(추가하기)

## 태그
aws, vpc, subnet

<hr>

## AWS I am role
AWS 리소스에 대한 액세스를 안전하게 제어할 수 있는 웹 서비스이다. I AM을 사용하여 리소스를 사용하도록 인증(로그인) 및 권한 부여(권한 있음)된 대상을 제어한다.

AWS 계정을 처음 생성하면, 모든 AWS 서비스 및 리소스에 대한 루트 사용자가 된다.(모든 서비스와 리소스에 대한 완전한 액세스 권한이 있는 ID)

루트 사용자는 사용하지 않는게 좋다. 루트 사용자는 각 서비스 및 리소스에 권한을 가지고 있는 다른 사용자를 만들어서 사용한다. 이 사용자들이 IAM 사용자이다.

루트 사용자 자격 증명을 안전하게 보관해 두고 몇 가지 계정 및 서비스 관리 작업을 수행할 때만 해당 자격 증명을 사용한다.

## 태그
aws, iam

<hr>

## 책임 연쇄 패턴
명령 객체와, 다수의 처리 객체로 이루어진 패턴이다. 여러 처리 객체는 체인으로 연결되고, 각 처리 객체는 차례대로 명령을 수행한다. 수행할 수 없는 명령은 체인으로 연결되어 있는 다음 처리 객체로 넘겨준다.(다음 객체로 책임을 넘겨준다.)

요청을 보내는 객체와, 처리하는 객체간의 결합을 느슨하게 하기 위해 만들어진 패턴이다. (연관된 처리 방식의 결합을 느슨하게 유지). 외부에서는 어떤 방식으로 구현되어 있는지 알 필요가 없다.(OCP를 만족)

## 태그
디자인패턴, 책임 연쇄 패턴

<hr>

## 무중단 배포
버전 변경이 있을 때, 운영중인 서비스를 중지시키지 않고, 버전을 업데이트하는 방법.

### 블루 그린
이전 버전(blue)에 있던 사용자 트래픽을 새 버전(green)으로 점진적으로 이전하는 방법이다. 실제로 하나의 서버를 더 띄워두고(동일하게 구성된 환경) 일시에 라우팅을 돌리는 방법을 뜻한다.

blue와 green 모두 프로덕션 환경에서 실행상태를 유지한다. 로드밸런서를 사용하여 트래픽을 blue에서 green으로 이전시킨다. 프로덕션 트래픽이 blue에서 green으로 완전히 이전되면 blue는 롤백에 대비하여, 대기 상태로 두거나 다음 버전의 템플릿으로 사용할 수 있다.
<img width="729" alt="스크린샷 2021-06-03 오전 10 50 53" src="https://user-images.githubusercontent.com/45876793/120574102-a2f48780-c459-11eb-9975-40a90ee1865e.png">


### 롤링
서버를 하나씩 이전 버전에서 새 버전을 교체해가는 전략이다. 서비스 중인 여러 서버 중 하나를 제외시키고, 그 자리에 새 버전의 서버를 추가해준다.(사용자 api 요청을 직접적으로 처리하지 않는 서버들부터 순차적으로 죽이고, 새로 띄우고를 반복해서 배포하는 방법.) 이런 식으로 이전 버전의 서버들을 점진적으로 새 버전으로 교체해준다.

서버 수의 제약이 있는 경우 유용한 방법이지만, 배포 중에 인스턴스의 수가 줄어들게 되기 때문에, 서버 처리 용량을 미리 고려해줘야 한다.
<img width="737" alt="스크린샷 2021-06-03 오전 10 51 03" src="https://user-images.githubusercontent.com/45876793/120574124-abe55900-c459-11eb-9662-a723694d0bc5.png">


### 카나리
이전 버전의 서버와 새 버전의 서버를 구성하고, 이전 버전의 일부 트래픽을 새 버전으로 분산시켜 오류여부를 판단하는 방법. 점차 새 버전의 트래픽을 높여가며 오류가 나지 않는다면 완전히 옮기고, 오류가 나면 이전 버전으로 돌릴 수도 있다.
![스크린샷 2021-06-03 오전 10 51 14](https://user-images.githubusercontent.com/45876793/120574131-b0117680-c459-11eb-8485-20ffc7f91090.png)


## 참고 링크
[Blue-Green 배포란?](https://www.redhat.com/ko/topics/devops/what-is-blue-green-deployment)
[Blue-Green 배포 방식](https://wallees.wordpress.com/2018/04/22/blue-green-%EB%B0%A9%EC%8B%9D/)
[배포 전략: Rolling, Blue/Green, Canary](https://onlywis.tistory.com/10)

## 태그
블루 그린, 롤링, 카나리

2021-06-06 01:44 UTC, JunHoPark93 commented
오 성실히 잘 찾아주셨네요 👍