[스프링 - 협업 미션] 라이언(권영훈) 미션 제출합니다.
woowacourse/atdd-subway-fare pull request #3
Opened 2021-05-22 12:58 UTC by YounghoonKwon

안녕하세요 제이!

배포된 url 은 여기에요 !! https://subway-fare.kro.kr/

2단계 요구사항에는 새로 모든 노선을 응답하는 것을 구현하라고 되있는데,
이미 GET "/lines" 에 요청에 대한 코드가 완벽하게 구현되있었어요.
그래서 딱히 2단계의 요구사항을 어떻게 진행해야될지 감이 안와요:)

로그인/비로그인 상태에서 경로 조회 부분은,
ArgumentResolver에서 null이면 exception이 발생하게끔 짜여져있던 코드를,
컨트롤러에서 로그인이 가능한 멤버인지 아닌지 판단하여 로직을 실행하게끔 짰는데
이 방법이 맞는지 잘 모르겠네요~

리뷰 잘 부탁드리겠습니다🙏 주말 잘 보내시구요~

2021-05-23 12:39 UTC, JunHoPark93 requested changes
안녕하세요 라이언!
빠르게 요청주셨네요~
몇가지 피드백 남겼으니 확인부탁드려요 :)

2021-05-23 12:39 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/dto/PathResponse.java
> +    private int fare;
2단계 요구사항인

> 프론트엔드에서 필요한 데이터만 응답할 수 있도록 프론트엔드 페어와 논의하여 API 설계하기


에서 프런트엔드 페어와 커뮤니케이션은 어떤방식으로 하신건가요?

2021-05-23 12:39 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/dto/PathResponse.java
> +    private int fare;
협업 미션인데 코드내에 문서화관련된 것들이 보이지 않아서요.
기존 api 문서가 존재하나 (https://woowacourse.github.io/atdd-subway-fare/) 이건 그냥 예시로 보이고
api 스펙은 각 조원들이 논의하여 새로 만들어져야 할거로 보이는데요.
이번미션에서는 문서화가 따로 없는걸까요?

2021-05-23 12:39 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/dto/PathResponseAssembler.java
> +        return new PathResponse(stationResponses, distance, subwayPathFare.getFare());
assembler는 client에 내려줄 dto를 만들기위해 단순 조립의 역할만을 수행할것으로 기대합니다. 하지만 내부에서 SubwayPathFare 라는 도메인도 생성되네요. 
이 친구는 밖에서 전달되어 assembler내부로 들어와야할거같은데 어떻게 생각하시나요?

2021-05-23 12:39 UTC, JunHoPark93 commented on README.md
> +  - [x] 어린이(6세 이상~ 13세 미만): 운임에서 350원을 공제한 금액의 50%할인
이번미션이 4단계까지 다 마치고 리뷰요청을 보내는것으로 알고있는데요,
1,2단계에 대한 내용은 다 완료가 된걸까요?

인프라를 구성하신 파일이나 배포를 하셨다면 배포 스크립트도 같이 들어있어야될거같은데 보이지않아서 여쭤봅니다.

2021-05-23 12:39 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/ui/PathController.java
> +        return loginMember;
질문주신부분인거같아요!
* 비로그인일때는 age를 -1로 하드코딩 하는 방법말고 다른 방법은 없을까요?
* null로 LoginMember를 초기화하여도 운임을 계산할때 내부적으로 age만 사용되는것으로 보여요. LoginMember를 초기화할 필요가 있을까요?

2021-05-23 12:39 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/domain/SubwayPathFare.java
> +    }
반복되는 if문을 개선할 수 있는 방법이 있을까요?

2021-05-23 12:39 UTC, JunHoPark93 commented on src/main/resources/application-prod.properties
> +account.name=produser
환경별로 여러 설정파일들을 나눠보셨네요!
logging도 환경별로 설정할 수 있으니 이부분은 여력이 되신다면 찾아보시길바랍니다

2021-05-23 12:39 UTC, JunHoPark93 commented on README.md
> +  - [x] 어린이(6세 이상~ 13세 미만): 운임에서 350원을 공제한 금액의 50%할인
배포되었다고 올려주신 url이 접근이 되지 않는데, 이부분도 확인부탁드려요!

2021-05-23 14:31 UTC, YounghoonKwon commented on README.md
> +  - [x] 어린이(6세 이상~ 13세 미만): 운임에서 350원을 공제한 금액의 50%할인
커맨드라인으로 배포 했는데, 배포 스크립트 준비해서 다시 업로드 하겠습니다!
url 접근 관련 말씀은 아직 프론트 배포가 안되서 그런거 같은데, 일단 postman으로 할 시에 작동합니다!

2021-05-23 14:32 UTC, YounghoonKwon commented on src/main/java/wooteco/subway/path/dto/PathResponse.java
> +    private int fare;
예시 api스펙과 뼈대 코드를 그대로 쓰기러 프론트 크루들과 협의가 되었고,
추후에 변동사항이 있으면 api 명세에 수정을 하는 것으로 했어요.

snapshot 사용해서 문서화 추가하겠습니다~

2021-05-23 14:49 UTC, YounghoonKwon commented on src/main/java/wooteco/subway/path/dto/PathResponseAssembler.java
> +        return new PathResponse(stationResponses, distance, subwayPathFare.getFare());
반영했습니다!

2021-05-23 15:46 UTC, YounghoonKwon commented on src/main/java/wooteco/subway/path/domain/SubwayPathFare.java
> +    }
앗!!! 리팩토링 했습니다! Enum이랑, BinaryOperator랑 UnaryOperator써서 처리했어요!

2021-05-23 15:53 UTC, YounghoonKwon commented on src/main/resources/application-prod.properties
> +account.name=produser
넵 적용하고 리뷰요청 날리겠습니다!

2021-05-25 09:07 UTC, YounghoonKwon commented on src/main/java/wooteco/subway/path/ui/PathController.java
> +        return loginMember;
resolver를 따로 하나 더 만들어서, 나이만 보내주는건 어떨까요??
정답이 뭔지 궁금하네요 ㅠ

2021-05-28 14:44 UTC, YounghoonKwon commented
예시 api스펙과 뼈대 코드를 그대로 쓰기로 프론트 크루들과 협의가 됬었고,
그 사이 미션 요구사항이 끝나서 PR을 좀 일찍 쐈던 감이 없잖아 있네요~

추후에 변동사항이 있으면 api 명세에 수정을 하는 것으로 했는데,
요구사항이 어그제 와서 수정 하고 다시 제출 합니다!!

백엔드 배포 url: https://subway-fare.kro.kr/
프론트 배포 url: https://doby-collin-react-subway.web.app/
API 명세: https://subway-fare.kro.kr/docs/index.html

이번에 리팩토링하면서 크게 진행한것은,
restdocs 사용하기, 배포 스크립트 만들기, 프론트와 백엔드 크루들과 API명세 수정하기(응답값, 예외 맞추기)
이렇게 세개 정도에요!

그리고, 로그인 관련된 기능을, ArgumentResolver를 하나 더 만들어서 나이만 보내주는 것으로 했는데,
제이 생각이 궁금하기도 하네요!

이번에도 잘 부탁드립니다:)

2021-05-30 03:58 UTC, JunHoPark93 commented on app/step1/deploy-prod.sh
> +    sleep 5
각 라인별로 어떤것이 수행되는지 잘 봐주셨어요~

라이언 스프링부트 버전이 2.4버전을 사용하고 계셔서 이거는 그냥 공부해보면 좋을거같아서 남기니 여유가 되실때 찾아보셔요

**💡 사용자의 요청이 들어오고 내부에서 처리중인데 앱을 죽이면 그 요청은 어떻게 될까요?**

부트 버전업이 되면서 해당부분이 개선이 되었어요.

📍`keyword`
graceful shutdown

2021-05-30 03:58 UTC, JunHoPark93 commented on src/docs/asciidoc/index.adoc
> +include::{snippets}/station-create/http-response.adoc[]
문서도 생성해보셨네요! 👍

2021-05-30 03:58 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/config/ExceptionAdvice.java
> +        logger.error("method argument not valid exception occurred. message=[{}]", e.getMessage(), e);
세분화해서 잘 나누어보셨네요!
이메서드랑 바로밑에 메서드에서 error 로그가 `method argument.. `가 맞을까요?

2021-05-30 03:58 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/line/application/LineService.java
> +        }
Optional 처리를 개선해볼 수 있을까요? 🤔

2021-05-30 03:58 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/member/application/MemberService.java
> +        }
검증을 잘해주셨네요!
인자로 email을 넘겨주면 추후 로그를 확인할때 좋습니다 :)

2021-05-30 03:58 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/domain/FareCalculatorByDistance.java
> +public enum FareCalculatorByDistance {
if문을 개선해주셨네요 👍

2021-05-30 03:58 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/domain/SubwayPathFare.java
> +            return -1;
이부분도 프런트분들과 협의가 된거죠~?

2021-05-30 03:58 UTC, JunHoPark93 commented on src/main/resources/application-prod.properties
> +account.name=produser
음 logback 파일을 profile별로 나누는것을 의도하였어요! 해당부분은 실제 프로젝트하실때 적용해봐도 좋을거같아요 :)

2021-05-30 04:00 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/ui/PathController.java
> +        return loginMember;
코멘트 남겨둘게요!

2021-05-30 04:04 UTC, JunHoPark93 requested changes
안녕하세요 라이언!
문서화와 스크립트도 추가해주셨네요 👍
간단하게 몇가지 남겼는데 금방보실수있을거같아요 :)

2021-05-30 04:04 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/ui/PathController.java
> +    public ResponseEntity<PathResponse> findPath(@AgeAuthenticationPrincipal Integer age,
질문주신부분입니다!
개인적으로는 기존의 LoginMember에서 id같은 키값만 들고있고 컨트롤러에서 회원을 조회해서 세팅하는 방법이 나아보여요!
id가 null이어서 조회를 못하거나 없는회원같은 경우는 정의하신 age(-1)로 세팅하는것도 방법이 될수있을거같아요

2021-05-30 04:04 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/path/ui/PathController.java
> +    public ResponseEntity<PathResponse> findPath(@AgeAuthenticationPrincipal Integer age,
다시 수정하실필요는 없고 이런 방법도 있다만 참고하시면 좋을거같아요

2021-05-30 07:56 UTC, YounghoonKwon commented on src/main/java/wooteco/subway/path/domain/SubwayPathFare.java
> +            return -1;
요금 계산 관련 부분은 프론트쪽 미션은 아니고, 백엔드쪽에만 있는 미션이라서 협의가 안되었어요!!

2021-05-30 08:15 UTC, YounghoonKwon commented on app/step1/deploy-prod.sh
> +    sleep 5
부트 짱이네요!!!!

2021-05-30 08:20 UTC, YounghoonKwon commented on src/main/java/wooteco/subway/path/ui/PathController.java
> +    public ResponseEntity<PathResponse> findPath(@AgeAuthenticationPrincipal Integer age,
그게 더 효율적이겠네요!!!!

2021-05-31 15:33 UTC, JunHoPark93 approved these changes
안녕하세요 라이언!
빠르게해주셨네요! 리뷰반영하시느라 고생많으셨어요 🙏 
궁금한점이 남아있다면 언제든 말씀주세요.
다음 레벨도 화이팅이에요 🥳

2021-05-31 15:34 UTC, JunHoPark93 commented on src/main/java/wooteco/subway/line/domain/Sections.java
> +                .orElseGet(() -> null);
null대신 빈리스트를 반환하는건 어떨까요?

2021-05-31 22:52 UTC, merged