[스프링 - 협업 미션] 파즈(강승윤) 미션 제출합니다.
woowacourse/atdd-subway-fare pull request #36
Opened 2021-05-31 06:27 UTC by Be-poz

안녕하세요 김고래 반갑습니다.  
이번 미션은 요금 관련 기능을 구현하는 것도 있었지만, 프론트 크루들과 협업하는 것이 더 비중이 컸던 것 같아요! 
커밋에서 651df91 부터 a6f30ff 까지가 요금관련이고 나머지는 프론트 분들과 맞춰가기 위한 커밋입니다!  
거리와 나이에 따른 요금계산은 enum 으로 처리했고 Fare 객체 내부에서  
```java
        int fareAfterDistanceDiscount = DistanceDiscount.calculateFareAfterDiscount(distance);
        return AgeDiscount.calculateFareAfterDiscount(fareAfterDistanceDiscount, age) + extraFare;
```
다음과 같이 처리해주었습니다.  

이번 미션은 리뷰하기도 굉장히 어려울 것 같다는 생각이 많이 드네요... 리뷰해주셔서 감사합니다~!

2021-06-01 18:49 UTC, ep1stas1s requested changes
안녕하세요 파즈~
API 문서화까지 잘 해주셨네요 👍 
몇 가지 코멘트 남겼으니 참고해보시고 궁금한 점 있으시면 언제든 DM 주세요~

2021-06-01 18:49 UTC, ep1stas1s commented on src/docs/asciidoc/index.adoc
> +ifndef::snippets[]
Rest docs 👍

2021-06-01 18:49 UTC, ep1stas1s commented on build.gradle
> +	testCompile 'org.springframework.restdocs:spring-restdocs-mockmvc:2.0.2.RELEASE'
compile vs implementation 차이에 대해 학습해보셔도 좋을 것 같아요 ^_^

2021-06-01 18:49 UTC, ep1stas1s commented on src/main/java/wooteco/subway/common/BaseControllerAdvice.java
> +@ControllerAdvice
```suggestion
@RestControllerAdvice
```
exception handler 👍

2021-06-01 18:49 UTC, ep1stas1s commented on src/main/java/wooteco/subway/common/BaseControllerAdvice.java
> +                .body(new ErrorResponse(ex.getBindingResult().getAllErrors().get(0).getDefaultMessage()));
첫 번째만 사용하는 거면 `getFieldError()` 요런 메서드도 있습니다 :)

2021-06-01 18:49 UTC, ep1stas1s commented on src/main/java/wooteco/subway/line/application/LineService.java
> +    public List<LineMapResponse> findLineMapResponses() {
한 번 경로를 조회할 때 디비 호출량을 최소화해보는 것도 좋을 것 같아요

2021-06-01 18:49 UTC, ep1stas1s commented on src/main/java/wooteco/subway/line/dao/LineDao.java
> +        } catch (DuplicateKeyException e) {
중복 검사는 서비스에서 진행하는 건 어떨까요?
개인적으로 데이터를 넣기 전에 검사하는 것과 일단 넣어보는 건 의미가 조금 다르다고 생각합니다ㅎㅎ;

2021-06-01 18:49 UTC, ep1stas1s commented on src/main/java/wooteco/subway/line/dao/LineDao.java
> +            List<Map<String, Object>> result = jdbcTemplate.queryForList(sql, new Object[]{id});
```suggestion
            List<Map<String, Object>> result = jdbcTemplate.queryForList(sql, id);
```
마지막 매개변수가 가변인자라 이렇게도 가능합니다 :)

2021-06-01 18:49 UTC, ep1stas1s commented on src/main/java/wooteco/subway/line/dao/LineDao.java
> +        } catch (EmptyResultDataAccessException e) {
요걸 캐치하는 경우도 있나요~?

2021-06-01 18:49 UTC, ep1stas1s commented on src/main/java/wooteco/subway/line/exception/line/DuplicatedLineNameException.java
> +public class DuplicatedLineNameException extends LineException {
예외 계층을 잘 나누셨네요 👍

2021-06-01 18:49 UTC, ep1stas1s commented on src/main/java/wooteco/subway/line/dto/SectionRequest.java
> +    @Positive(message = "INVALID_INPUT")
메세지를 클라이언트에 내려주기 때문에, 해당 메세지를 보고 어떤게 문젠지 알수 있으면 더 좋을 것 같아요
(다른 의미가 있으시면 말씀해주시고, 수정은 번거로우니 알고만 가셔도 될 것 같습니다ㅎㅎ)

2021-06-01 18:49 UTC, ep1stas1s commented on src/main/java/wooteco/subway/path/domain/fare/DistanceDiscount.java
> +    LONG_DISTANCE(distance -> distance > 50, distance -> 2050 + ((int) (Math.ceil((double) (distance - 50) / 8)) * 100));
매직넘버들이 하드코딩으로 느껴지는데요~
예를 들어 2050의 경우, 기본 요금 또는 추가금이 변경되면 따로 계산을 해서 넣어줘야 할 것 같아요

2021-06-01 18:49 UTC, ep1stas1s commented on src/main/java/wooteco/subway/path/domain/fare/DistanceDiscount.java
> +    UnaryOperator<Integer> discountPolicy;
요기도 접근 제어자를 붙여주세요ㅎㅎ

2021-06-01 18:49 UTC, ep1stas1s commented on src/main/java/wooteco/subway/path/domain/fare/DistanceDiscount.java
> +    public static int calculateFareAfterDiscount(int distance) {
enum으로 부터 계산하려면 정책을 get해야할 거 같은데, 역할을 나눠 보는건 어떨까요?

2021-06-01 18:49 UTC, ep1stas1s commented on src/test/java/wooteco/subway/member/MemberControllerTest.java
> +        given(authService.findMemberByToken(null))
테스트 진행과 관련 없는 부분은 빼주시면 더 좋을 것 같아요~
혹은 전부다 필요하다면 beforeEach를 활용해주세요ㅎㅎ

2021-06-01 18:49 UTC, ep1stas1s commented on src/test/java/wooteco/subway/member/MemberControllerTest.java
> +public class MemberControllerTest {
통합 테스트와 컨트롤러 테스트를 나눈 기준이 있으실까요?
만약 rest docs 때문이라면 통합 테스트에서 같이 진행하는 게 더 좋을 것 같습니다ㅎㅎ

2021-06-01 18:49 UTC, ep1stas1s commented on src/main/java/wooteco/subway/line/application/LineService.java
> +@Transactional
CUD와 R을 나눠서 적용해보시는 건 어떨까요~?

2021-06-03 07:01 UTC, Be-poz commented on build.gradle
> +	testCompile 'org.springframework.restdocs:spring-restdocs-mockmvc:2.0.2.RELEASE'
안그래도 이 부분 정말 궁금해서 공부해보려했는데 감사합니다!! 일단 이것부터 학습해볼게요!

2021-06-06 14:22 UTC, Be-poz commented on src/main/java/wooteco/subway/common/BaseControllerAdvice.java
> +                .body(new ErrorResponse(ex.getBindingResult().getAllErrors().get(0).getDefaultMessage()));
오우 잘 알아가요!!

2021-06-06 14:33 UTC, Be-poz commented on src/main/java/wooteco/subway/line/dao/LineDao.java
> +            List<Map<String, Object>> result = jdbcTemplate.queryForList(sql, new Object[]{id});
그냥도 가능하군요~!

2021-06-06 14:34 UTC, Be-poz commented on src/main/java/wooteco/subway/line/dto/SectionRequest.java
> +    @Positive(message = "INVALID_INPUT")
이 부분은 프론트크루들과 약속되어서 정한 메세지에요~!

2021-06-06 14:46 UTC, Be-poz commented on src/main/java/wooteco/subway/line/application/LineService.java
> +    public List<LineMapResponse> findLineMapResponses() {
이 부분은 한 방 쿼리로 해결하려고 처음에 시도했는데, 프론트 쪽에서 요구한 명세가 Line에 대한 Dto가 있고 내부에 Station에 관한 Dto가 존재하며 이 내부에 또 다른 Line과 관련 Dto가 있어서.. 한 방 쿼리를 시도하려했으나 진짜 안되더라구요... 이 부분 어떻게 줄여야 될지 잘 모르겠습니다 ㅜ ㅜ

2021-06-06 15:09 UTC, Be-poz commented on src/main/java/wooteco/subway/line/application/LineService.java
> +@Transactional
필요하다고 생각되는 곳만 추가했습니다~

2021-06-06 15:10 UTC, Be-poz commented on src/test/java/wooteco/subway/member/MemberControllerTest.java
> +public class MemberControllerTest {
이 부분은 기존의 테스트가 AcceptanceTest였는데 이 테스트를 완성짓고나서 급하게 문서를 만든다고 사실 문서를 위한 테스트였습니다! 그래서 비교 또한 그냥 ``status().isok()`` 만 했던거였습니다! 이 부분은 다음번 필요할 경우에 처음부터 mockMvc를 사용한 테스팅을 하도록 하겠습니다!

2021-06-06 15:39 UTC, Be-poz commented on src/test/java/wooteco/subway/member/MemberControllerTest.java
> +        given(authService.findMemberByToken(null))
컨트롤러 테스트들 다 공통부분 처리가 안됐네요 호다닥하다보니 ㅎㅎ;; 처리했습니다!

2021-06-06 15:53 UTC, Be-poz commented on src/main/java/wooteco/subway/path/domain/fare/DistanceDiscount.java
> +    LONG_DISTANCE(distance -> distance > 50, distance -> 2050 + ((int) (Math.ceil((double) (distance - 50) / 8)) * 100));
Age Policy와 더불어서 고치겠습니다!

2021-06-07 14:07 UTC, Be-poz commented on src/main/java/wooteco/subway/line/dao/LineDao.java
> +        } catch (EmptyResultDataAccessException e) {
중복검사와 더불어서 처리했습니다.

2021-06-07 14:07 UTC, Be-poz commented on src/main/java/wooteco/subway/line/dao/LineDao.java
> +        } catch (DuplicateKeyException e) {
서비스에서 확인하는 것으로 변경했습니다.

2021-06-07 15:10 UTC, Be-poz commented
안녕하세요 김고래! 리뷰 재요청이 많이 늦어진점 죄송합니다! 테코톡 준비하느라 지난주에는 신경을 못썼네요 ㅜ.ㅜ  
리뷰해주신거에 대해서 반영했습니다! gradle 관련해서 공부를 하면서 jvm에 대해서도 다시 공부하게 됐고 알찬 시간이었습니다!  

# 학습로그
## Gradle 파일 implementation, api, runtimeOnly, compileOnly... 등에 대해  
- https://github.com/Be-poz/TIL/blob/master/Spring/Gradle%20%ED%8C%8C%EC%9D%BC%20implementation%2C%20api%2C%20runtimeOnly%2C%20compileOnly%20...%20%EB%93%B1%EC%97%90%20%EB%8C%80%ED%95%B4.md  
## 태그
- {gradle}, {dependency_configuration}, {implementation_vs_api}, {runtimeOnly}, {compileOnly}

2021-06-08 22:14 UTC, ep1stas1s approved these changes
미션 진행하시느라 고생 많으셨습니다 👍 
크게 변경이 필요한 부분은 없어 머지할게요ㅎㅎㅎ
추가적으로 코멘트 남겼으니 같이 참고해보셔도 좋을 것 같습니다!

2021-06-08 22:14 UTC, ep1stas1s commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +        Member member = memberDao.findByEmail(request.getEmail());
findByEmail 에서 optional을 반환하면 좀 더 간단하게 표현이 가능할 것 같아요 ^_^
```java
memberDao.findByEmail(request.getEmail())
                .orElseThrow(MismatchIdPasswordException::new);
```

2021-06-08 22:14 UTC, ep1stas1s commented on src/main/java/wooteco/subway/line/application/LineService.java
>      public Line findLineById(Long id) {
읽기 전용을 명시하면 약간의 성능 향상도 볼 수 있고, 나중에 DB를 분리할 때도 용이해요 :)
```java
@Transactional(readOnly = true)
public Line findLineById(Long id) { ...}
```
저의 경우는 이러한 반복을 줄이기 위해 class level에 `@Transactional(readOnly = true)`를 명시하고, cud가 필요한 부분에만 따로 `@Transactional` 어노테이션을 붙이는 방법을 사용합니다

2021-06-08 22:14 UTC, ep1stas1s commented on src/main/java/wooteco/subway/path/domain/fare/AgeDiscount.java
> +        return fare - discountedFare(findAge, fare);
정적 메서드가 아닌 인스턴스 메서드로 `ageDiscount.discountedFare(fare)`와 같은 형식은 어떨까요?

2021-06-08 22:14 UTC, ep1stas1s commented on src/main/java/wooteco/subway/path/domain/fare/DistanceFareRule.java
> +    private final int fareForDistanceFormulaValue;
필드가 조금 많다고 생각이 드네요ㅎㅎㅎ; 
전에 코멘트를 남긴 2050의 경우, 기본 요금(1250)에 `MIDDLE_DISTANCE`의 최대 요금이 합쳐진 금액이지만, `MIDDLE_DISTANCE`의 계산식이 바뀌게 되면 같이 변경될 수 있을 것 같아서 코멘트를 남겼었어요~

간단하게 두 가지 변경안이 있는데요~ 시간나실 때 한 번 고민해보셔도 좋을 것 같습니다ㅎㅎ
1. 현재 방식에서 defaultFare를 이전 요금에서부터 계산하는 방식으로 변경
2. 거리에 해당하는 모든 룰을 적용

2021-06-08 22:15 UTC, merged