[스프링 - 협업 미션] 제이온(박진영) 미션 제출합니다.
woowacourse/atdd-subway-fare pull request #4
Opened 2021-05-25 08:09 UTC by pjy1368

안녕하세요 데이브! 레벨 1에 이어서 또 뵙네요 ✌
배포된 url은 https://jayon-subway.r-e.kr 이며, 2단계 요구 사항은 차차 적용해 나갈 생각이에요.
1, 3, 4단계 위주로 봐주시면 감사하겠습니다 ㅎㅎ

한 가지 질문이 있어요.  
현재 거리에 따른 추가 요금과 연령에 따른 할인 정책에 대해 enum을 사용했지만, 분기 자체를 아예 지울 수가 없었어요.  
만약, 기준이 50개가 넘어간다면 현재 50개의 분기를 처리해야하는데 현업에서는 어떻게 사용하나요?
전략 패턴을 적용해도, 외부에서 전략을 주입하는 과정에서 분기가 필연적이라고 생각합니다.  
개인적으로 생각해 보았을 때, 분기만 처리해서 반환하는 Factory 객체를 만들어서 전략을 반환하고 그 전략을 주입하는 방식이 있었는데, 이 방식은 어떠한 것 같나요?  

제 코드 리뷰를 위해 귀한 시간 내 주셔서 감사합니다 🙏

(2021-05-27 수정)
2단계도 대부분 구현이 되었습니다. 2단계는 구간을 포함한 전체 노선을 조회하는 기능을 만들어주었고, 프론트 요청으로 환승 정보를 포함한 역 정보를 조회하는 기능을 구현하였습니다. 환승 정보 관련 url은 "/stations/transfer"입니다.

그리고 프론트 요청으로 특정 이메일이 중복된 이메일인지 확인하는 기능도 만들었습니다. 해당 url은 "/members/email-check"입니다.

그 외에는 전반적인 예외 검증을 디테일하게 적용하였고, 인터셉터를 통해 조회를 제외한 생성, 수정, 삭제 기능은 로그인 유저만 가능하도록 수정하였습니다.

2021-05-27 17:04 UTC, dave915 requested changes
제이온 안녕하세요! 
구현 잘 해주셨네요 👍 
몇가지 피드백 남겼습니다. 확인부탁드릴게요 =)
혹시 궁금한 점 있으면 언제든지 질문 주세요!

2021-05-27 17:04 UTC, dave915 commented on scripts/subway-deploy.sh
> +nohup java -jar -Dspring.profiles.active=remote atdd-subway-fare-0.0.1-SNAPSHOT.jar 1> log.txt 2>&1 &
`1> log.txt 2>&1` 이 부분은 log파일 만드려고 사용하시는 걸까요? 
맞다면 logback `FileAppender` 찾아보셔도 좋을 것 같아요 :)

2021-05-27 17:04 UTC, dave915 commented on src/main/java/wooteco/subway/path/domain/SectionEdges.java
> +        return sectionEdgeGroup.stream().mapToInt(it -> it.getSection().getDistance()).sum();
디미터의 법칙을 적용 할 수 있을 것 같아요 :) 
```suggestion
        return sectionEdgeGroup.stream().mapToInt(it -> it.getSectionDistance()).sum();
```

2021-05-27 17:04 UTC, dave915 commented on src/main/java/wooteco/subway/path/domain/ExtraFare.java
> +            .filter(element -> element.minRange < distance && element.maxRange >= distance)
`element.minRange < distance && element.maxRange >= distance` 이 부분 메소드 분리 하면 좋을 것 같아요 :)

2021-05-27 17:04 UTC, dave915 commented on src/main/java/wooteco/subway/common/GlobalExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(new ErrorResponse(exception.getMessage()));
`@ExceptionHandler(RuntimeException.class)`  같은 경우 개발자가 정의 하지 않은 에러도 다루기 때문에 에러 메세지에 패키지 정보, 또는 사용하는 기술에 관한 정보가 담겨있을 수 있어요. 그렇기 때문에 `exception.getMessage()` 를 그대로 내보내주기 보단 로그로 남기고 `서버에서 오류가 발생했습니다.` 와 같은 메세지로 변경 해서 내보내줘요.

그리고 404, 405 같은 오류는 못잡네요. RuntimeException.class 대신 Exception.class 를 핸들링 하는것도 고려해보세요 :)

2021-05-27 17:04 UTC, dave915 commented on src/main/java/wooteco/subway/path/application/PathService.java
> +        if (loginMember.isLogin()) {
이 부분 때문에 `LoginMember` 객체 내에 `isLogin()` 을 추가 한 것으로 보이는데요. 
필드 추가 없이 그냥 Controller에서 `@AuthenticationPrincipal LoginMember loginMember` 부분에 null을 받아도 되지 않을까 싶은데... 제이온은 어떻게 생각하시나요?

2021-05-27 17:04 UTC, dave915 commented on src/main/java/wooteco/subway/path/domain/DiscountRate.java
> +        }
질문 주신 분기를 제거하지 못한 부분이 이 부분일까요? 
ageBaseline와 비교하기 보단 `IntPredicate` 을 이용해서 반환 할 value를 정하는건 어떠신가요?

2021-05-29 05:24 UTC, dave915 requested changes
제이온 안녕하세요! 
피드백 반영한 부분 확인했습니다. 
몇가지 코멘트 남겼어요! 확인 부탁드릴게요 :)

2021-05-29 05:24 UTC, dave915 commented on src/main/resources/file-appender.xml
> +  <appender name="file" class="ch.qos.logback.core.rolling.RollingFileAppender">
👍

2021-05-29 05:24 UTC, dave915 commented on src/main/java/wooteco/subway/SwaggerConfig.java
> +public class SwaggerConfig {
안그래도 이번 피드백에 swagger 추가 제안드려볼려고 했는데 적용하셨군요 👍

2021-05-29 05:24 UTC, dave915 commented on src/main/java/wooteco/subway/PageController.java
>  public class PageController {
이 Api 는 Swagger에서 볼 필요가 없을 것 같아요. `@ApiIgnore` 를 사용하면 숨길 수 있습니다 :) 
```suggestion
@ApiIgnore
@Controller
public class PageController {
```

2021-05-29 05:24 UTC, dave915 commented on src/main/java/wooteco/subway/SwaggerConfig.java
> +    public Docket api() {
로그인 제한이 걸려있는 api 는 어떻게 테스트 하셨나요? 
swagger에서 jwt토큰을 추가해서 요청하도록 할 수 있어요. 아래 링크 참고해보세요! 

https://kimyhcj.tistory.com/363

2021-05-29 05:24 UTC, dave915 commented on src/main/java/wooteco/subway/common/GlobalExceptionHandler.java
> +            .body(new ErrorResponse("서버에서 에러가 발생했습니다."));
👍

2021-05-29 05:24 UTC, dave915 commented on src/main/java/wooteco/subway/line/ui/LineController.java
>      @PostMapping
Swagger에 Post만 보이고 Get이 안보여서 살펴 봤더니 PageController에서 가져갔었네요!

2021-05-31 21:42 UTC, dave915 approved these changes
제이온 안녕하세요! 
그동안 미션 진행 하느라 고생 많으셨습니다 👍
이만 머지할게요! 
혹시 추가로 궁금한 부분있으면 언제든 DM주세요!

2021-05-31 21:42 UTC, dave915 commented on src/main/java/wooteco/subway/path/domain/DiscountRate.java
> +    private final IntPredicate predicate;
👏

2021-05-31 21:42 UTC, dave915 commented on src/main/java/wooteco/subway/SwaggerConfig.java
> +            .securitySchemes(Lists.newArrayList(apiKey()));
👍

2021-05-31 22:56 UTC, merged

2021-06-22 12:53 UTC, pjy1368 commented
# 제이온의 학습 로그
## Docker File
- 컨테이너에 설치해야하는 패키지, 소스코드, 명령어, 환경변수 설정 등을 기록한 하나의 파일이다
- 그리고 이를 빌드하면 자동으로 이미지가 생성되며, 앞으로는 애플리케이션 빌드 및 배포를 자동화할 수 있게 된다.

## HTTPS vs TLS vs SSL
- HTTP의 보안이 강화된 버전으로 통신의 인증과 암호화를 위해 개발되었다. 일반 텍스트를 이용하는 대신 SSL이나 TLS 프로토콜을 통해 세션 데이터를 암호화 한다.
- SSL은 Netscape사에서 웹 서버와 웹 브라우저 간의 보안을 위해 만들어졌으며, 공개키/개인키 대칭키 기반으로 사용한다.
-  TLS는 SSL에 대한 IETF에서 1999년 1월 RFC 2246과 같은 표준 규약으로 정의된 버전이라고 할 수 있다.

## Reverse Proxy
- 서버와 가까운 곳에 프록시가 존재하는 것으로, 서버의 응답을 대신 클라이언트에게 전달해주는 역할을 수행한다.
- 요청에서 개인 정보를 파악할 수 있는 헤더를 제거하고 서버에 요청을 보냄으로서 익명성을 보장해줄 수 있다. 그리고 서버 앞단에 놓여있기 때문에 실제 서버에 대해 알 수 없도록, 보안을 높일 수도 있다.

## 예외 처리
- @Valid를 통한 Dto 값 검증을 할 수 있다.
- @NotNull, @NotEmpty, @NotBlank 등 다양한 예외를 처리할 수 있다.
- 해당 방식으로 발생한 예외는 'MethodArgumentNotValidException'이다.