[스프링 - 협업 미션] 멍토(김유기) 미션 제출합니다.
woowacourse/atdd-subway-fare pull request #43
Opened 2021-05-31 15:37 UTC by daum7766

안녕하세요. 지노!
마지막 미션을 함께하게 된 멍토입니다.

이번 미션을 하면서 이미 만들어진 코드에 내용을 추가하고 수정하는 데 있어서 어려움을 느꼈습니다. 기능만 구현한다면 어려운 내용이 아니지만, 최대한 구조를 해치지 않으며 기능을 추가해야 했고, 테스트 코드 또한 리팩터링이 들어가야 해서 어려웠습니다. 실제로 일을 하게 된다면 리팩터링을 자주 경험하게 될 텐데 이번 미션을 통해서 프론트와의 협업 + 다른 사람이 작성한 코드 유지보수 및 기능추가를 경험할 수 있었고 이걸 노린 미션이 아닐까 생각해 보았습니다.

이번 미션을 하면서 생겼던 이슈입니다.

1. `AuthenticationPrincipalConfig` 클래스에서 LoginInterceptor에 jwtTokenProvider를 주입하기 위해 들고있는 상황인데 페어가 authService가 jwtTokenProvider를 들고있는데 authService를 넣으면 되지 않겠냐? 라고 했습니다.
저는 jwtTokenProvider의 역할만 필요하지 authService의 역할은 필요가 없다고 판단되어 jwtTokenProvider만 넣자고 했습니다.
지노가 생각은 어떠신가요?

2. 노선에 추가요금을 넣는 파트에서 노선에 추가요금을 안 넣을 수도 있다는 생각에 extraFare에 디폴트로 0을 주었습니다. 사용자에게 입력을 받을때 모든 값을 다 넣게하고 추가요금이 없다면 0을 받도록 해야할까요? 아니면 추가요금이 없다면 extraFare를 빼도 되게 만들어도 될까요?

감사합니다.

2021-06-03 06:54 UTC, hyunssooo requested changes
안녕하세요 멍토! 
미션 잘 진행하셨네요! 
확인이 늦어서 정말정말 죄송합니다 😭😭
몇 가지 코멘트 남겼습니다 확인 부탁드려요!

2021-06-03 06:54 UTC, hyunssooo commented on src/main/java/wooteco/subway/SubwayAdvice.java
> +        System.out.println(exception.getMessage());
디버깅을 위함일까요? logger를 사용해보는 것은 어떨까요??

2021-06-03 06:54 UTC, hyunssooo commented on src/main/java/wooteco/subway/SubwayAdvice.java
> +@ControllerAdvice
`@RestControllerAdvice` 도 찾아보면 좋을 것 같아요 :)

2021-06-03 06:54 UTC, hyunssooo commented on src/main/java/wooteco/subway/path/domain/FareCalculator.java
> +
이 클래스는 빈으로 등록될 필요가 있을까요??

2021-06-03 06:54 UTC, hyunssooo commented on src/main/java/wooteco/subway/station/dao/StationDao.java
> +    }
station에 id가 이미 있지 않나요?? 이런 경우는 getter를 사용하는 것이 더 나을 것 같아요! 
메서드만 봤을 경우 id와 station이 다르더라고 쿼리는 실행될 것 같아요!

2021-06-03 06:54 UTC, hyunssooo commented on src/main/java/wooteco/subway/station/domain/Station.java
> +
패턴 재사용 👍

2021-06-03 06:54 UTC, hyunssooo commented on src/main/java/wooteco/subway/member/domain/LoginMember.java
> +    }
어느 경우에 사용하는 생성자일까요? 
member 정보가 없을 경우 사용하는 생성자인거 같은데 이때는 loginMember를 사용하는 것이 맞나요??

2021-06-03 06:54 UTC, hyunssooo commented on src/main/java/wooteco/subway/path/AgeSet.java
> +
enum 👍

2021-06-03 06:54 UTC, hyunssooo commented on src/main/java/wooteco/subway/path/ui/PathController.java
> +        return ResponseEntity.ok(pathService.findPath(source, target, loginMember.getAge()));
loginMember 에서 age를 getter로 꺼내고 있는데 member에서 ageset을 반환하는건 어떨까요?

2021-06-03 06:54 UTC, hyunssooo commented on src/main/java/wooteco/subway/auth/config/AuthenticationPrincipalConfig.java
> +    private final JwtTokenProvider jwtTokenProvider;
> AuthenticationPrincipalConfig 클래스에서 LoginInterceptor에 jwtTokenProvider를 주입하기 위해 들고 있는 상황인데 페어가 authService가 jwtTokenProvider를 들고 있는데 authService를 넣으면 되지 않겠느냐? 라고 했습니다.
> 저는 jwtTokenProvider의 역할만 필요하지 authService의 역할은 필요가 없다고 판단되어 jwtTokenProvider만 넣자고 했습니다.

이 부분은 개인 취향이 아닐까 생각합니다. 레이어 관점으로 봤을 경우 바로 아래 레이어에만 의존하나 하위 레이어라면 어떤 레이어든 의존할 수 있는지에 차이인 것 같은데 개인적으로는 바로 아래 레이어에만 의존하는 것이 좋다고 생각해요. JwtTokenProvider 같은 경우는 인프라스트럭처로 세부사항이라고 볼 수 있겠네요.

2021-06-03 06:54 UTC, hyunssooo commented on src/main/java/wooteco/subway/line/dto/LineRequest.java
> 노선에 추가 요금을 넣는 파트에서 노선에 추가 요금을 안 넣을 수도 있다는 생각에 extraFare에 디폴트로 0을 주었습니다. 사용자에게 입력을 받을 때 모든 값을 다 넣게 하고 추가 요금이 없다면 0을 받도록 해야 할까요? 아니면 추가 요금이 없다면 extraFare를 빼도 되게 만들어도 될까요?

이 부분인 것 같아요! 🙂 개인적으로는 요청값이 비어 있다면 0으로 처리해도 괜찮을 것 같습니다! 사용하기 편한 api가 아닐까 생각해요.

2021-06-03 06:54 UTC, hyunssooo commented
추가로 api문서와 배포링크까지 부탁드릴게요 :)

2021-06-03 12:44 UTC, daum7766 commented on src/main/java/wooteco/subway/SubwayAdvice.java
> +        System.out.println(exception.getMessage());
나중에 바꿔야지 하고 깜빡했네요 ㅜㅠ
변경하도록 하겠습니다!

2021-06-03 12:45 UTC, daum7766 commented on src/main/java/wooteco/subway/SubwayAdvice.java
> +@ControllerAdvice
@RestControllerAdvice 에 대해서 공부해보겠습니다!

2021-06-03 12:46 UTC, daum7766 commented on src/main/java/wooteco/subway/station/dao/StationDao.java
> +    }
그렇네요! 변경하도록 하겠습니다!

2021-06-03 12:46 UTC, daum7766 commented on src/main/java/wooteco/subway/member/domain/LoginMember.java
> +    }
해당 부분은 고민해서 변경하도록 하겠습니다.

2021-06-03 12:47 UTC, daum7766 commented on src/main/java/wooteco/subway/path/ui/PathController.java
> +        return ResponseEntity.ok(pathService.findPath(source, target, loginMember.getAge()));
어떻게 적용할지 고민해보겠습니다!

2021-06-03 12:48 UTC, daum7766 commented on src/main/java/wooteco/subway/line/dto/LineRequest.java
의견 감사합니다!

2021-06-03 13:18 UTC, daum7766 commented on src/main/java/wooteco/subway/auth/config/AuthenticationPrincipalConfig.java
> +    private final JwtTokenProvider jwtTokenProvider;
그렇군요! 현재 상태를 가져가도록 하겠습니다!

2021-06-03 13:34 UTC, daum7766 commented on src/main/java/wooteco/subway/SubwayAdvice.java
> +@ControllerAdvice
RestControllerAdvice는  ControllerAdvice와 ResponseBody가 합쳐진 어노테이션입니다.
만약 ResponseEntity를 쓰지 않았다면 문제가 생겼을 부분인데 ResponseEntity를 이용함으로써 문제가 회피되었던 것으로 파악됩니다. 
기본적인 내용으로 생각한다면 json으로 응답하기 위해 ControllerAdvice와 ResponseBody를 같이 붙여서 사용해야 하는데 이것을 사용하지 않아서 말씀해 주신것으로 판단됩니다.
앞으로는 RestControllerAdvice를 사용하도록 하겠습니다.
감사합니다.

2021-06-03 13:44 UTC, daum7766 commented on src/main/java/wooteco/subway/path/domain/FareCalculator.java
> +
!!! 메서드에 static을 붙여 놓고 빈으로 등록을 했었네요!
제거하도록 하겠습니다!

2021-06-05 13:39 UTC, daum7766 commented on src/main/java/wooteco/subway/station/dao/StationDao.java
> +    }
DM으로 이야기가 한번 오갔던 내용입니다.
저는 id를 외부에서 넣어서 객체를 만들어 반영하는 방식을 채택했습니다.
그 이유는 첫번째로 컨벤션입니다.
지금 구조에서는 이미 서비스에서 예외처리가 되어있고, 해당 부분을 바꾸면 많은 부분이 한꺼번에 변경이 되야 한다고 생각합니다. 따라서 오해의 소지만 줄일 수 있도록 station객체를 서비스에서 만들어 넘겨주는 방식으로 처리하도록 간소화 했습니다.

2021-06-05 13:41 UTC, daum7766 commented on src/main/java/wooteco/subway/member/domain/LoginMember.java
> +    }
해당 부분은 삭제하고 리졸버를 나누기로 결정하였습니다.

2021-06-05 14:53 UTC, daum7766 commented on src/main/java/wooteco/subway/path/ui/PathController.java
> +        return ResponseEntity.ok(pathService.findPath(source, target, loginMember.getAge()));
loginMember를 해당 메서드에서 사용하지 않도록 변경하여 member에서 ageSet을 반환할 필요성이 사라져 반영하지 않았습니다.

2021-06-05 15:35 UTC, daum7766 commented
안녕하세요 지노!
멍토입니다.

피드백을 주신 내용으로 생각하고 저만의 생각대로 반영해보았습니다.

## 피드백 반영사항입니다.
1. log를 적용했습니다. -> 해당 부분은 나중에 적용한다고 하고 적용을 안했던 부분입니다. 다음에는 나중에 적용하지 않고 미리 적용하겠습니다.
2. RestControllerAdvice를 적용했습니다. 자세한 내용은 [피드백](https://github.com/woowacourse/atdd-subway-fare/pull/43#discussion_r642571230)에 적어놓았습니다.
3. static class를 빈으로 등록하는 부분을 제거했습니다. 여기는 필요하지 않는데도 불구하고 저도 왜 추가했는지 모르겠더라고요... 다음에 좀 더 정신차리고 만들도록 하겠습니다.
4. station update 부분을 수정하였습니다. [피드백](https://github.com/woowacourse/atdd-subway-fare/pull/43#discussion_r644424462)에 자세한 내용이 적혀있습니다.
5. LoginMember에서 null로 처리하던 부분을 제거했습니다.
6. LoginMember에서 age만 넣던 것을 처리하기 위해 리졸버를 하나 더 생성했습니다. 새로 생성한 리졸버는 AgeSet을 반환하도록 되어있습니다. 리졸버에서 AgeSet을 반환함으로써 Member에서 ageSet을 반환하는 메서드를 만들 필요가 없다고 판단되어 해당 내용은 추가하지 않았습니다.

아래는 api문서, 프론트와 약속한 내용, 그리고 api 주소입니다.

## 자료
[api 문서](https://documenter.getpostman.com/view/12054749/TzXxjdcx)
[사전 협약 내용](https://www.notion.so/2-API-d23b5ee6baef4a76bfc098661339d796)
api 주소 : https://mungto-subway.o-r.kr

부족한 부분이 있다면 많이 지적해주세요!
감사합니다.

2021-06-06 12:06 UTC, hyunssooo approved these changes
안녕하세요 멍토 :) 
레벨 2 진행하신다고 정말 수고 많으셨습니다!! 🥳🥳
방학 푹 쉬시고 남음 과정도 잘 진행하시면 좋겠네요!

2021-06-06 12:06 UTC, hyunssooo commented on src/main/java/wooteco/subway/auth/application/AuthService.java
>          }
로그인하지 않은 사용자 같은 경우는 `AgeSet.ADULT` 으로 처리하고 있네요! 👍
이 방법도 충분히 좋은 방법이라고 생각합니다! 
디엠으로 얘기 나눴던 부분인데 설계에는 정답이 없으니 이 방법도 좋은 방법 같아요!

2021-06-06 12:10 UTC, hyunssooo commented
안녕하세요 멍토 :) 
api 문서 관련해서 궁금한 점이 있어서 코멘트 남겨요! postman 으로 자동화가 가능했나요??
제가 postman으로는 시도 안해봐서 잘 모르겠네요! 
혹시 아니라면 swagger나 rest docs 를 사용해보면 좋을 것 같아요 :) 
생각보다 api와 문서를 따로 관리하는 게 쉽지 않을 거라는 생각이 드네요!

2021-06-06 12:12 UTC, merged