[스프링 - 협업 미션] 피케이(박유진) 미션 제출합니다.
woowacourse/atdd-subway-fare pull request #45
Opened 2021-05-31 16:23 UTC by pkeugine

안녕하세요 휴!
피케이입니다! 처음 만나는데 잘 부탁드려요 😁

이번 미션에서는 뼈대 코드를 받았음에도 신경 쓸 요소가 많았어요.
프론트엔드 크루들과 협업도 해보고, 주어진 코드를 바탕으로 기능을 추가하는 것도 정말 재밌었습니다!

제가 이번 미션에서 집중했던 점은 다음과 같아요:

1. 금액과 BigDecimal
이번에 페어와 함께 지하철 요금을 BigDecimal로 관리해보기로 했(었)어요.
그래서 다음과 같이 요금과 관련된 Fare객체를 만들고, 그 안의 value 데이터형을 BigDecimal로 했죠:
```java
public class Fare {
    private final BigDecimal value;
    // ...
}
```
그랬더니 당연하게도 value를 원시값 int로 처리했을 때보다 훨씬 고려할 요소가 많았어요.
테스트를 할 때도 새로운 BigDecimal 객체를 만들어서 비교하고, 요금을 할인하거나 연산할 때마다 괜히 BigDecimal을 이용하기 때문에 추가 작업을 해야한다는 생각이 들더라구요. 마치 값을 BigDecimal로 포장했는데, 그걸 또 Fare로 포장해서 사용하는 느낌이었습니다. 그래서 금액은 그냥 BigDecimal로만 처리하던가 (`ex: BigDecimal fare = new BigDecimal(1_000);`), Fare 안의 value를 int로 바꾸자는 생각을 했고, 결과적으로 Fare를 유지하고 int형을 사용하기로 했습니다.

2. LoginInterceptor를 통한 인가
현재 저희 서비스에서는 로그인을 하지 않으면 `역 조회`와 `노선 조회`만 가능하고 다른 모든 기능을 막아놓은 상태입니다. 이를 가능하게 해주는 것이 `LoginInterceptor`인데요, 처음에는 `AuthenticationPrincipalConfig`만을 이용하여 LoginInterceptor를 통과할 요청을 정해주었습니다. 

그런데 나중에 가면 그 요청이 GET인지 (역 조회, 노선 조회), GET이면서 멤버의 정보를 조회하는 요청인지를 구분하기 위해 LoginInterceptor 안에서도 요청을 확인해야했어요:
```java
    @Override
    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
        if ("OPTIONS".equalsIgnoreCase(request.getMethod())) {
            return true;
        }
        if ("GET".equalsIgnoreCase(request.getMethod()) && !request.getRequestURI().contains("members")) {
            return true;
        }
       // ... 위의 if문에 걸리지 않으면 토큰 검증
    }
```
(OPTIONS는 preflight 요청 때문에 추가했습니다.)
과연 위와 같은 형태가 괜찮은지 의문이 들기도 했지만, 일단은 이보다 더 좋은 방식을 찾지 못했어요.

아직 이번 pr에 추가하지는 않았지만, 서비스 레이어 테스트도 진행해보고 있습니다!
휴와 함께 리뷰 진행하면서 리팩토링과 함께 진행할 예정입니다.
거침없는 리뷰 부탁드려요!!!! 🔥🔥🔥🔥
감사합니다!!!!!!!!!

2021-06-01 16:55 UTC, Hue9010 requested changes
피케이 반가워요. 이번 리뷰를 맡은 휴입니다. 😄
레벨 2 + 리뷰어의 마지막을 함께하게 됐네요.
피드백 남겼는데 확인하고 궁금한건 질문 주세요!
그리고 이번 미션은 기존과 다르게 프론트와 협업을 해보셨는데 이에 대한 간단한 문의 남겼는데 이것도 답변 부탁드려요. 😉

2021-06-01 16:55 UTC, Hue9010 commented on src/main/resources/application-prod.yml
> +    url: jdbc:mysql://localhost:3306/SUBWAY?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
db 분리를 잘해주셨네요. 👍
local과 별도로 두고 관리하니까 어떻던가요?
동일한 인스턴스에 떠 있긴하지만 로컬이 아닌 곳에 위치한 db를 관리해본 경험이 없었다면 이것도 어떠셨을지 궁금하네요. 😄

2021-06-01 16:55 UTC, Hue9010 commented on src/main/java/wooteco/subway/auth/AuthenticationPrincipalConfig.java
> +//                        , "/paths"
필요없는 주석은 제거해주세요.

2021-06-01 16:55 UTC, Hue9010 commented on src/main/java/wooteco/subway/DataLoader.java
> +@Profile("local")
💯

2021-06-01 16:55 UTC, Hue9010 commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +            return Optional.of(LoginMember.of(member));
ofNullable에서 of로 바꾼 이유는 LoginMember.of로 생성을 하다보니 null이 들어갈 일 이 없어서가 맞을까요?
바꾸게 된 과정이 궁금해서 질문 드려요! 😉

2021-06-01 16:55 UTC, Hue9010 commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +            return Optional.empty();
findMemberByToken의 사용처를 보니 Optional을 반환하기보다는 LoginMember를 반환하게 시그니처를 바꾸고 게스트를 바로 반환해줘도 되지 않을까요? 🤔

2021-06-01 16:55 UTC, Hue9010 commented on src/main/java/wooteco/subway/line/application/DuplicatedLineException.java
> +        super(String.format("색상 혹은 이름이 이미 존재합니다. 이름 : %s, 색상 : %s", request.getName(), request.getColor()));
예외 발생시 원인 파악이 쉽게 메시지를 잘 활용해 주셨네요. 👍

2021-06-01 16:55 UTC, Hue9010 commented on src/main/java/wooteco/subway/line/application/DuplicatedLineException.java
> +    }
이건 사용되지 않는것 같은데 제거해주죠!

2021-06-01 16:55 UTC, Hue9010 commented on src/main/java/wooteco/subway/line/application/LineService.java
> +    @Transactional
```java
@Transactional(readOnly = true)
```
이 메서드는 CUD가 이뤄지니 대상은 아니지만 조회만 발생하는 메서드에는 readOnly 옵션을 줄 수 있답니다.
JPA 또는 replica db를 두고 있지 않아 큰 이점을 얻을 부분이 적지만 명시적인 측면에서 구분해주는 것도 좋다고 생각해요.

2021-06-01 16:55 UTC, Hue9010 commented on src/main/java/wooteco/subway/line/domain/AlreadyExistsException.java
> +    }
여기도 사용하지 않는 기본 생성자를 추가하셨네요.
거꾸로 생각해서 기본 제공된 뼈대 코드에 사용되지 않는 메서드가 많았다면 어떨까요?
정체를 알 수 없는 코드가 많으면 분석하는데 그만큼 시간을 뺏기게 됩니다. 그리고 보통 남이 짠 코드를 제거하는게 자신의 코드를 제거하는 것보다 더 오래걸리죠.
그래서 불필요한 코드라고 판단되면 바로 제거하는 버릇을 들이는게 좋답니다.

2021-06-01 16:55 UTC, Hue9010 commented on src/main/java/wooteco/subway/line/domain/Line.java
> +    public Line(Long id, String name, String color, Sections sections) {
이제 사용되지 않는 것 같은데 확인해주세요.
Line 52의 update도 같이 봐주세요!

2021-06-01 16:55 UTC, Hue9010 commented on src/main/java/wooteco/subway/line/domain/Sections.java
> +            throw new AlreadyExistsException("노선에 이미 포함된 구간입니다.");
DuplicatedXxxException이 있는데 AlreadyXxxException와 어떤 차이가 있나요?
동일한 예외를 의미하는 것 같은데 이왕이면 Already, Duplicated 중 한가지로 네이밍을 맞추면 어떨까요? 🤔

2021-06-01 16:55 UTC, Hue9010 commented on src/main/java/wooteco/subway/line/dto/LineRequest.java
> +    @NotNull
바로 위에 NotBlank가 있는걸 보니 NotBlank, NotEmpty, NotNull의 차이는 아실것 같아서 여쭤봐요!
color는 빈 값을 허용하는 건가요?

2021-06-01 16:55 UTC, Hue9010 commented on src/main/java/wooteco/subway/line/dto/LineRequest.java
> +    private int extraFare;
NotNull이 없는데 PositiveOrZero는 null을 허용할까요 아닐까요? 🤔
조금더 얘기해볼게 있는데 그전에 extraFare에 어떤 정책을 적용하려고 하셨는지 알려주시면 좋을 것 같아요!

2021-06-01 16:55 UTC, Hue9010 commented on src/main/java/wooteco/subway/line/dto/LineRequest.java
> +    }
가능하다면 테스트만을 위한 코드는 안만드는게 좋다고봐요.
조금 더 정확히는 extraFare가 추가되면서 테스트 외에는 사용하지 않게 된것 같지만요.

2021-06-01 16:55 UTC, Hue9010 commented on src/main/java/wooteco/subway/line/ui/LineController.java
> +    public ResponseEntity<Void> updateLine(@PathVariable Long id,
Void 👍

2021-06-01 16:55 UTC, Hue9010 commented on src/main/java/wooteco/subway/member/application/MemberException.java
> +public class MemberException extends RuntimeException {
만약에 LineException이 있으면 이건 어떤 예외일까요?
특정 도메인명만 붙인 예외는 어떤 예외인지, 어떤 상태 코드를 응답할지 MemberException코드를 까보기 전까지는 알 수 없습니다.
직관적이지 못한 이름이죠.

LineException과 DuplicatedLineException 중 어느게 더 좋은 이름일까요?

```java
throw new MemberException("이미 사용되고 있는 이메일입니다.");
```
사용되고 있는걸 봤을 때 이름을 고쳐보면 좋을 것 같아요.

2021-06-01 16:55 UTC, Hue9010 commented on src/main/java/wooteco/subway/member/ui/MemberController.java
>          return ResponseEntity.created(URI.create("/members/" + member.getId())).build();
반환 타입이 MemberResponse인데 response body엔 아무것도 반환하지 않고 있네요.

2021-06-01 16:55 UTC, Hue9010 commented on src/main/java/wooteco/subway/station/application/StationService.java
> +                .orElseThrow(() -> new NotFoundException("존재하지 않는 StationID 입니다."));
DuplicatedStationException, DuplicatedLineException처럼 어떤 아이디로 요청했는지 메시지에 추가할 수 있을 것 같아요. 😉

2021-06-01 16:55 UTC, Hue9010 commented on src/main/java/wooteco/subway/station/ui/StationController.java
> +    public ResponseEntity<Void> handleBadRequestException() {
ResponseStatusr과 Controller 내의 ExceptionHandler 이 두가지로 예외 처리를 하고 있네요.
그렇다면 예외 발생시 어떤 응답을 하는지 확인하려면 모든 예외와 컨트롤러를 확인해야지만 가능해집니다.
그리고 SQLException에 대해서도 중복 코드가 발생하고 있죠.

[AOP 정리 (3)](https://jojoldu.tistory.com/71)에 대해서 한번 읽어본다음 ControllerAdvice를 통해 예외 처리에 대한 관심사는 ExceptionHandler를 만들어 관리해주면 어떨까요?
지금은 AOP에 대해서는 `관심사의 분리` 이 키워드만 기억해주셔도 충분해요. 그리고 AOP가 무엇인지에 대해만 알면되니 공유드린 글의 다른 시리즈는 보실 필요 없답니다. 😉

2021-06-01 16:55 UTC, Hue9010 commented on src/test/java/wooteco/subway/path/domain/FareTest.java
> +class FareTest {
신규 추가한 도메인에 대한 테스트 💯 👍

2021-06-01 16:55 UTC, Hue9010 commented on src/test/java/wooteco/subway/path/domain/FareTest.java
> +        int basicValue = 1_250;
`_` 소소하지만 유용한 기능을 잘 쓰시는군요. 👍

2021-06-01 16:55 UTC, Hue9010 commented on src/test/java/wooteco/subway/path/domain/FareTest.java
> +    }, delimiter = ':')
Junit 5 활용 👍

2021-06-01 16:55 UTC, Hue9010 commented on src/main/java/wooteco/subway/path/domain/discount/AgeDiscountRule.java
> +public enum AgeDiscountRule {
👍 
이후 노약자가 추가된다면 if문이 아니라 enum을 추가해주면 되겠네요. 👏

2021-06-01 16:55 UTC, Hue9010 commented on src/main/java/wooteco/subway/path/domain/Fare.java
> +    public static final Fare ADDITION = new Fare(100);
매직 넘버일 수 있는 값을 Fare 채로 상수화 시키셨군요. 
단순히 `int ZERO = 0`이였다면 상수화 시킨 의미가 없는데 `Fare ZERO = new Fare(0);`는 확실히 의미가 있군요. 👍

2021-06-01 16:55 UTC, Hue9010 commented on src/main/java/wooteco/subway/path/domain/Fare.java
> +    private final int value;
저도 BigDecimal를 다룰 일이 없는데 큰 도전을 하셨군요. 😋 
요금은 억단위 넘기도 힘들테니 int로도 충분하지만 학습적인 도전이였다면 충분히 시도해볼만한 도전이였다고 생각해요. 👍 
혹 그 학습적인 이유가 아니라 돈이기때문에 BigDecimal의 사용을 고려했다면 정말 필요했을까 다시 한번 생각해보는 것도 좋을 것 같아요. 하지만 학습 이유가 컸을 것 같군요. 😏

2021-06-01 16:55 UTC, Hue9010 commented on src/main/java/wooteco/subway/auth/ui/LoginInterceptor.java
> +    public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
넵, 지금처럼 해주시면 됩니다!

2021-06-01 16:55 UTC, Hue9010 commented on src/test/java/wooteco/subway/station/application/StationServiceTest.java
> +}
개인적으로 이번 미션을 진행하신 분들께 공통적으로 드리는 질문입니다! 

프론트와 협업하는 과정은 어땠나요? 
- API를 어떻게 정했는지
- 정하고서 실제 제공은 언제 했는지
- 서버에서 API를 제공하기 전에 프론트가 먼저 실제 API를 사용할 수 있는 상태는 아니였는지
- 인터페이스를 가지고 협업한건 어땠는지
- 예외 응답 처리는 어떻게하기로 했는지

등등이 될 것 같은데 위에는 간단히 생각난 예시를 드린거고 간단히 알려주시면 같이 얘기해볼게 있을지 보고자 질문드려요.

예를들면 서버에서 구현이 끝나기 전 프론트에서 먼저 API를 연동해야할 상황이라면 mock api 형태로 특정 응답만 하는 API를 먼저 만들어 줄 수도 있답니다. 간단하게는 Controller와 Request, Response만 구현하고 특정 값을 채운 Response를 응답해주면 되겠죠? 그러고서 실제 기능이 개발 됐을 때 재배포 할 수 있을 겁니다.

위와 같은 이런 저런 얘기를 해볼 수 있을 것 같아요. 말은 이렇게 했지만 기대에 부흥하지 못하고 아무 얘기도 못해 드릴수 있답니다. 😋

2021-06-01 16:55 UTC, Hue9010 commented on src/test/java/wooteco/subway/station/application/StationServiceTest.java
> +//        verify(stationDao).insert(stationRequest.toStation());
주석 처리한 이유가 뭘까요? 🤔
참고로 테스트에서만 제외하고 싶으면 `@Disabled`를 사용할 수 있습니다!

2021-06-07 02:55 UTC, pkeugine commented on src/main/resources/application-prod.yml
> +    url: jdbc:mysql://localhost:3306/SUBWAY?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
local, test 환경에서는 h2를 사용하고 실제 배포 서버에서는 mysql을 사용했어요. 휴가 말하신 것처럼 동일한 인스턴스에 떠 있긴 했지만 터미널을 이용하여 mysql 테이블을 관리하는게 처음이라 신기했습니다! 리눅스에서는 테이블 이름이 case sensitive로 설정되어 있다는 것도 이번 미션을 통해 알게되었어요. 이렇게 분리해놓으니 가장 큰 장점으로는 테스트 때문에 실제 db가 변경되지 않았습니다.

2021-06-07 03:02 UTC, pkeugine commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +            return Optional.of(LoginMember.of(member));
사실 ofNullable이 'null일 수 있는 객체'를 담는다는 것만 알고 이 둘을 언제 사용하면 좋을지 잘 몰랐어요. 그래서 휴의 코멘트를 보고 한 번 알아봤습니다! Optional.of 를 사용하면 개발자가 '이것은 null이 될 수 없어'라고 표시하는 것과 같아서, 실제로 null이 들어오는 상황이 생기면 에러가 발생하도록 사용한다는 것을 알게되었습니다. 그래서 LoginMember.of 로 객체를 생성하는 부분에서는 Optional.of를 사용하는 것이 맞네요! null이 될 수 없고, 만약 null이 된다면 에러가 발생해야하니까요!

2021-06-07 03:07 UTC, pkeugine commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +            return Optional.empty();
그러네요! 수정 완료했습니다. 😁

2021-06-07 03:12 UTC, pkeugine commented on src/main/java/wooteco/subway/line/application/DuplicatedLineException.java
> +        super(String.format("색상 혹은 이름이 이미 존재합니다. 이름 : %s, 색상 : %s", request.getName(), request.getColor()));
감사합니다! 이 부분에서 한가지 걸리는 점은 파라미터로 LineRequest를 보내고 있다는 점이에요.
현재 제 exception들을 보면 어떤 것은 message를 받고, 어떤 것은 역 이름, 그리고 어떤 것은 LineRequest 를 받아서 통일성이 떨어진다는 생각이 드네요! 예외에 친절한 에러 메시지를 담고 싶을 때 휴는 어떻게 하시나요?

2021-06-07 03:16 UTC, pkeugine commented on src/main/java/wooteco/subway/line/domain/AlreadyExistsException.java
> +    }
감사합니다! 예외에서 사용하지 않는 생성자 모두 제외했습니다 🙏

2021-06-07 03:19 UTC, pkeugine commented on src/main/java/wooteco/subway/line/domain/Sections.java
> +            throw new AlreadyExistsException("노선에 이미 포함된 구간입니다.");
Duplicated로 네이밍을 맞췄어요! 이번에 여러 커스텀 예외를 만들면서 '통일성'의 중요성을 느끼고 있습니다. 그런데 미리 예외를 만들어 놓지 않고 필요할 때 만들어서 쓰다보니 이렇게 통일성이 떨어지는 현상이 발생하네요. 예외를 만들기 전에 기존에 제가 어떻게 만들었는지 확인을 해가며 진행해야겠다는 생각이 들었습니다!!

2021-06-07 03:20 UTC, pkeugine commented on src/main/java/wooteco/subway/line/dto/LineRequest.java
> +    @NotNull
아닙니다! color도 name과 마찬가지로 빈 값을 허용하지 않아요. 이 부분 @NotBlank로 수정했습니다!

2021-06-07 03:40 UTC, pkeugine commented on src/main/java/wooteco/subway/line/application/LineService.java
> +    @Transactional
제가 service를 만드는 경우에는 보통 클래스 단위로 Transactional(readOnly=true)를 두고, CUD가 이뤄지는 메서드에 따로 Transactional을 명시하는 편입니다!

2021-06-07 03:43 UTC, pkeugine commented on src/test/java/wooteco/subway/station/application/StationServiceTest.java
> +//        verify(stationDao).insert(stationRequest.toStation());
와우 감사합니다!! 엄청 유용한 어노테이션이네요. 사용해보면서 JUnit5의 Jupiter에 어떤 어노테이션이 있는지도 살펴보고 있어요!

2021-06-07 03:45 UTC, pkeugine commented on src/main/java/wooteco/subway/line/dto/LineRequest.java
> +    private int extraFare;
extraFare는 프론트엔드와 함께하지 않고 페어와 둘이서 진행하는 단계였습니다. 그래서 저희끼리 얘기했을 때, 추가요금은 없을 수도 있다는 정책을 만들었어요. 그런데 PositiveOrZero를 보니 null 검증을 하지 않네요! 리팩토링하면서 NotNull을 추가했습니다!!

2021-06-07 03:45 UTC, pkeugine commented on src/main/java/wooteco/subway/line/dto/LineRequest.java
> +    }
이런 부분은 커밋하면서 다시 확인해봐야하는데 예상치 못하게 발생하게 되네요 🥲

2021-06-07 03:50 UTC, pkeugine commented on src/main/java/wooteco/subway/member/application/MemberException.java
> +public class MemberException extends RuntimeException {
위에서 받은 리뷰를 고려하여 DuplicatedMemberException으로 이름을 수정했습니다!

2021-06-07 04:11 UTC, pkeugine commented on src/test/java/wooteco/subway/station/application/StationServiceTest.java
> +}
먼저 API는 이미 만들어져 있는 것을 최대한 활용했어요.
저희가 새로 만들어야하는 API (GET "/lines/all") 역시 있었는데, 프론트엔드 쪽에서는 URI가 딱히 민감한 부분이 아니라고 하여 백엔드 쪽에서 정했습니다. 응답에 담길 요소는 프론트엔드의 요구사항을 먼저 듣고 정했어요. 아무래도 받는 쪽이 원하는 것을 말하고 만들어 주는 쪽이 거기서 수정할 만한 것들을 찾는게 좋으니까요.

그러다보니 에러 발생시 메시지를 전달하지 않고 상태코드만 전달해도 된다고 하여 예외 메시지를 exception에 담기는 하지만 따로 response에 담아서 전달하지는 않았어요. 아직 로깅을 적용하지 않았지만 에러 메시지는 로깅할 때 유용할 것 같다는 이유에서 넣었습니다!

이번 미션에서는 프론트엔드가 조금 더 늦게 미션이 진행되어 더미 api를 먼저 제공할 필요는 없었는데요, 확실히 공통된 속도로 개발을 진행할 때는 더미 api를 먼저 만들어서 프론트엔드도 해당 api를 활용할 수 있도록 하는 방식이 옳다고 생각했어요. 그리고 이런 방식으로 하면 더미 api이긴 하지만 swagger와 같은 도구로 명세서도 미리 만들어서 볼 수 있다는 장점이 있겠네요!

한가지 어려웠던 점이라면, 프론트엔드 쪽에서 기능에 에러가 있다고 했을 때 그것이 어떤 문제인지 파악하기 위한 시간이 협업하지 않았을 때보다 조금 더 오래 걸렸다는 점입니다! 그런데 이 부분은 당연하다는 생각도 드네요.😂

2021-06-07 04:19 UTC, pkeugine commented on src/main/java/wooteco/subway/station/application/StationService.java
> +                .orElseThrow(() -> new NotFoundException("존재하지 않는 StationID 입니다."));
추가했습니다!

2021-06-07 04:49 UTC, pkeugine commented
안녕하세요 휴!
정말 친절한 리뷰 감사합니다!!! 덕분에 많이 배우고 있어요!!
이번에도 잘 부탁드립니다.

변경사항 / 리뷰 받고 싶은 부분은 다음과 같아요:
### 서비스 레이어 테스트를 추가했어요
- 서비스 레이어 테스트를 두 가지 방식으로 진행했어요.
- LineServiceTest는 SpringBootTest를 이용하여 실제 컨텍스트에 dao와 필요한 service를 autowired 해서 테스트하고,
- 나머지 서비스 테스트들은 mockito를 사용하여 유닛테스트를 진행했습니다.
- 이렇게 한 이유는 LineService에 필요한 객체들을 모킹하지 않고 autowired를 쓰는 것이 테스트 시간은 오래걸리더라도 더 간편해서 였어요. 학습해보고 싶은 이유도 있었구요. 그래서 실제로 휴도 두 가지 방식을 함께 사용하는지 궁금합니다! SpringBootTest를 쓰는 순간 그것이 unit test가 아니라는 생각은 드네요!

2021-06-07 13:00 UTC, Hue9010 requested changes
추가로 피드백 드릴 부분이 적을 정도로 잘 반영 해 주셨네요. 👍 😋
궁금한건 이전과 마찬가지로 질문 주시면 답변드리도록 할게요. 😄 
혹시 놓친 질문이 있으면 말씀주세요!!

2021-06-07 13:00 UTC, Hue9010 commented on src/main/resources/banner.txt
> +
배너를 추가하셨군요. 😄

2021-06-07 13:00 UTC, Hue9010 commented on src/main/resources/application-prod.yml
> +    url: jdbc:mysql://localhost:3306/SUBWAY?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
운영중인 서비스의 기능이 추가될 때 개발 과정의 무언가가 prod 환경의 db에 영향을 끼치면 안되겠죠? 
거꾸로 운영 데이터나 테이블에 문제가 없으니 개발 과정에서도 마음편히 개발을 할 수 있답니다. 

그리고 실제 라이브가 되기 전의 서비스라면 prod의 db도 반쯤은 개발 db라고 생각해도 무방하긴 합니다. 😄

2021-06-07 13:00 UTC, Hue9010 commented on src/main/java/wooteco/subway/line/application/DuplicatedLineException.java
> +        super(String.format("색상 혹은 이름이 이미 존재합니다. 이름 : %s, 색상 : %s", request.getName(), request.getColor()));
지금은 name이 String이라 그런데 Long id였다면 조금은 더 수월해요.


```java
@ResponseStatus(HttpStatus.BAD_REQUEST)
public class DuplicatedStationException extends RuntimeException {

    public DuplicatedStationException(Long id) {
        super(String.format("이미 존재하는 역 이름입니다. ID: %d",id));
    }

    public DuplicatedSectionException(String message) {
        super(message);
    }
}
```

이렇게 말이죠. 하지만 지금 같이 문자열을 받는다면 아쉽게도 지금 피케이가 한 것 처럼 message를 받는 형태로 하고 예외 발생하는 곳에서 필요한 형태로 메시지를 만드는 편입니다.

2021-06-07 13:00 UTC, Hue9010 commented on src/main/java/wooteco/subway/line/dto/LineRequest.java
> +    private int extraFare;
`private int extraFare;`에 null이 들어갈 일은 없습니다!!
int와 Integer의 차이죠. int는 아무것도 할당하지 않으면 0으로 초기화 됩니다.
즉, 클라이언트에서 extraFare를 비어서 보내면 0으로 초기화 된다는 것이죠.
그래서 NotNull을 추가하셔도 null로 요청했을 때를 검출해내지 못합니다. 지금은 extraFare를 500으로 보내려고 했는데 코드상의 버그던 몇가지 이유로 이를 누락해서 요청하게되면 0으로 저장되게 됩니다.

확인하고자 했던게 extraFare에 대한 요청이 비었을 때 0을 디폴트값으로 처리하고자 했는지였습니다. 😏 

int, Integer도 그렇지만 Boolean, boolean도 마찬가지인데 boolean이 false로 초기화되기 때문에 여기서 생각치 못한 버그가 발생할 수 있답니다.

2021-06-07 13:00 UTC, Hue9010 commented on src/test/java/wooteco/subway/station/application/StationServiceTest.java
> +}
이번 미션을 보면 리뷰이마다도 서버의 에러메시지가 클라이언트에 그대로 출력되기도 하고 아니기도 한데 실제로도 클라이언트에서 에러메시지를 자체적으로 처리할지, 서버의 응답을 그대로 사용할지는 회사, 조직마다 다른 편이랍니다. 정책적인 면으로 봐주셔도 될 것 같아요. 그리고 오류가 생겼을 때 진짜 명확한 상황이 아니라면 어디가 어떻게 문제인지 찾는게 원래 힘들답니다. 😢

여담이지만 학습할 때 이걸 봐두면 조금 더 시야가 넓어 질 거라고 생각해요. [Day1, 2-2. 그런 REST API로 괜찮은가](https://www.youtube.com/watch?v=RP_f5dMoHFc)
참고로 저도 완벽한 rest api를 만들고자 하진 않고, rest api를 지향하는 정도랍니다.ㅎㅎ

2021-06-07 13:00 UTC, Hue9010 commented on src/test/java/wooteco/subway/station/application/StationServiceTest.java
> +@MockitoSettings
Q.
이렇게 한 이유는 LineService에 필요한 객체들을 모킹하지 않고 autowired를 쓰는 것이 테스트 시간은 오래걸리더라도 더 간편해서 였어요. 학습해보고 싶은 이유도 있었구요. 그래서 실제로 휴도 두 가지 방식을 함께 사용하는지 궁금합니다! SpringBootTest를 쓰는 순간 그것이 unit test가 아니라는 생각은 드네요!

A.
저는 주로 외부 API만 mocking하는 편이에요. 한가지 예를 들면 사내 개발 서버가 자정에 모두 셧다운 되는 상황에서 새벽에 테스트할 일이 있으면 외부 API 또한 서버가 종료되어 있기 때문에 호출을 실패할거에요. 코드상에 문제가 하나도 없는데 테스트가 실패한다는 얘기죠. 이런 외부의 의존성을 제거하기 위해 mocking합니다. 

이것도 약간은 스타일의 차이라고 생각해요. [[번역] UnitTest By Martin Fowler](https://medium.com/@joohotheman/번역-unittest-by-martin-fowler-2fbba01a782e) - 단독(Solitary) VS 협동(Sociable)을 보시면 말이 어렵지만 생각보다 상세하게 나와있답니다. 😄

2021-06-07 13:02 UTC, Hue9010 commented on src/main/java/wooteco/subway/line/domain/Sections.java
> +            throw new AlreadyExistsException("노선에 이미 포함된 구간입니다.");
사람이란게 하다보면 자주쓰는 용어들도 생기는 법이고, 기존 프로젝트에 참여하게 되면 이미 사용되고 있는 네이밍이 있어 그걸 참고하는 것도 방법입니다. 😉

2021-06-07 13:03 UTC, Hue9010 commented on src/test/java/wooteco/subway/station/application/StationServiceTest.java
> +//        verify(stationDao).insert(stationRequest.toStation());
여담이지만 스프링을 어느정도 공부하고 사용하다보면 애노테이션 주도 개발하는 기분이 들때도 있습니다. 🤣

2021-06-08 07:35 UTC, pkeugine commented
휴!
언제나 친절한 리뷰 감사합니다.
변경점은 다음과 같아요:

#### 1. exception 패키지를 따로 만들었어요. 
도메인별 패키지에도 추가하고, 여러 도메인에서 같이 쓰는 exception은 별도로 분리해서 패키지를 만들었습니다 (NotFoundException의 경우). 기존에는 application 패키지에 있었는데, 예외는 별도 패키지를 만들어서 보관하는 것이 훨씬 찾기 편하고 application 패키지에는 어울리지 않다고 생각했어요.

#### 2. ResponseStatus로 에러를 더 이상 처리하지 않아요.
제 서비스는 클라이언트에서 에러 메시지를 신경쓰지 않았기 때문에 원래 ResponseStatus로 커스텀 예외를 처리했어요. 그런데 예외가 많아질수록 한 곳에서 잡아주는 것이 중복도 없애고 코드 가독성도 높인다고 판단했습니다.

#### 3. int형 값에 붙인 NotNull 어노테이션을 제거했어요. 
이 부분은 휴 덕분에 확실히 배워가네요! 정말 감사합니다 :)

2021-06-08 13:10 UTC, Hue9010 approved these changes
피케이 피드백 반영 잘해주셨네요. 👍 
이미 이전에 잘 해두셔서 이번엔 크게 피드백 드릴 내용이 없네요. 😋
이번 단계는 여기서 머지하도록 할게요! 협업 과정 수고하셨습니다!!
간단한 피드백 남기긴 했는데 코드 수정을 하지 않아도 어떤 내용인지 충분히 아실 것 같아 마무리 했어요.
머지는 코드의 변경이 필요 없다는 것 뿐이니까 궁금한거나 마저 얘기하고 싶은 내용은 코멘트 남겨주시면 됩니다. 😉
그리고 제가 빠트린 질문이 있다면 이건 필수적으로 말씀주세요!!

남은 우테코 과정도 잘 해가시길 바라겠습니다. 화이팅!

2021-06-08 13:10 UTC, Hue9010 commented on src/main/java/wooteco/subway/SubwayGlobalControllerAdvice.java
> +    }
RuntimeException을 badRequest로 응답해주는건 좋지 못합니다.
커스텀하게 만든 Exception 외에도 왠만한 Exception은 RuntimeException에 해당하죠. 즉, 어떤 예외가 발생하던 400 응답을 하게된다는 겁니다. 진짜 몇가지 특정 예외를 제외하고는 handleUnexpectedException를 탈일이 없이 handleRuntimeException를 통해 400 응답을 하게 될겁니다.

2021-06-08 13:10 UTC, Hue9010 commented on src/main/java/wooteco/subway/line/domain/DuplicatedSectionException.java
> +@ResponseStatus(HttpStatus.BAD_REQUEST)
DuplicatedSectionException, InvalidDistanceException에 ResponseStatus가 아직 남아있네요.
참고로 저는 `cmd + shift + f` 로 찾아봤습니다. 😋

2021-06-08 13:10 UTC, merged

2021-06-11 11:42 UTC, pkeugine commented
# 피케이 학습로그

## Swagger 3
* api 문서화 툴 중 하나
* 장점으로:
    * 빠르다. Swagger 3는 `application.yml`에 `springdocs:swagger-ui` 설정만 해주면 바로 문서가 완성된다.
    * ui가 예쁘다.
    * api 명세서 화면에서 직접 테스트 해볼 수 있다.

위와 같은 이유로 미션에서 Swagger 3를 이용하여 api 명세서를 작성하였다.

* 그러나 단점도 있었다.
    * 디테일한 명세서를 만들기 위해서는 실제 코드에 문서 관련 코드를 추가해야 한다. 이는 가독성 하락으로 이어져, 최대한 문서 관련 코드 추가를 지양하기로 페어와 결정했다.
```java
    @Operation(summary = "Create new Station") // 1
    @PostMapping("/stations")
    public ResponseEntity<StationResponse> createStation(
            @Valid @RequestBody StationRequest stationRequest) {
        StationResponse station = stationService.saveStation(stationRequest);
        return ResponseEntity.created(URI.create("/stations/" + station.getId())).body(station);
    }
```
1. StationController라는 실제 코드에 문서 관련 코드가 적용된 것을 볼 수 있다.

## MockMvc와 RestDocs

RestDocs는 실제 코드에 문서 관련 코드를 추가하지 않아도 된다는 장점이 있지만,
RestDocs로 api 명세서를 작성하려면 test를 먼저 만들고 통과시켜야 한다.
그 테스트를 만드는 방법으로는 크게 두 가지가 있는데, 바로
1. RestAssured를 사용한다.
2. MockMvc를 사용한다.

미션을 별도로 다시 진행해볼 때 나는 MockMvc와 RestDocs로 api 명세서를 작성했다.
그 이유로:
1. MockMvc는 `spring-boot-starter-test` 에 포함되어 있지만, RestAssured는 사용하려면 의존성을 추가해야 한다.
2. RestAssured와는 달리 MockMvc는 Controller가 의존하는 빈들만 컨테이너에 올려서 빠른 테스트가 가능하다. (RestAssured도 추가 설정을 통해서 web 레이어 빈들만 사용하는 `@WebMvcTest` 어노테이션을 사용할 수 있긴하다.)

#### RestDocs를 사용할 때 build.gradle 변경사항
```groovy
plugins {
    id "org.asciidoctor.convert" version "1.5.9.2" // 1
    id 'org.springframework.boot' version '2.4.3'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'java'
}
```
1. 먼저 plugin에 "org.asciidoctor.convert"를 추가해준다. AsciiDoc 파일을 컨버팅한 후 build 폴더에 복사하기 위한 플러그인이다.
   
```groovy
dependencies {
    // ... 기존에 존재하던 의존성
    
    
    // MockMvc의 경우
    testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc' // 2
    // RestAssured의 경우
    testImplementation 'org.springframework.restdocs:spring-restdocs-restassured'

    asciidoctor 'org.springframework.restdocs:spring-restdocs-asciidoctor:1.2.6.RELEASE' // 3
}
```
2. `dependencies`에 mockMvc를 RestDocs에 사용할 수 있게끔 하는 라이브러리를 추가한다. 만약 RestAssured를 사용하고자 한다면, 하단의 코드를 추가하면 된다.
3. asciidoctor 설정에 `spring-restdocs asciidoctor` 의존성을 추가한다. 이 설정으로 인해 `.adoc`파일에 있는 `snippets`가 `build/generated-snippets`를 가리키게 된다!

```groovy
asciidoctor { // 4
    dependsOn test
}


task createDocument(type: Copy) { // 5
    dependsOn asciidoctor

    from file("build/asciidoc/html5/index.html")
    into file("src/main/resources/static/docs")
}

build { // 6
    dependsOn createDocument
}
```
4. asciidoctor 실행하기 전에 test를 먼저 실행하도록 해주는 코드.
5. createDocument 라는 새로운 gradle 명령을 추가하고, `.adoc` 파일과 `index.html` 파일을 만든 다음 원하는 장소로 해당 html 파일을 옮겨주는 코드.
6. gradle build 할 때 `createDocument`를 먼저 실행하도록 해주는 코드.