[스프링 - 협업 미션] 김김(김기문) 미션 제출합니다.
woowacourse/atdd-subway-fare pull request #46
Opened 2021-05-31 16:39 UTC by tributetothemoon

안녕하세요 김고래!! 김김입니다🙇‍♂️.

우테코를 처음 시작하고 레벨1 첫 미션을 받았을 때 첫 리뷰어가 김고래였는데, 그 때 너무 잘해주셔서 좋은 기억으로 남아있었습니다.

그런데 레벨 2를 마무리하는 이 시점에 다시 만나니 정말 반갑네요! 이번에도 잘 부탁드리겠습니다😄!

---------------

이번 미션에서는 기능 구현에 대해서는 오랜 시간이 걸리진 않았습니다.

하지만 주제가 `협업`인 만큼, API 문서 자동화를 해야겠다고 생각하고 실행에 옮겼는데...생각보다 세팅이 힘들어 오랜 시간이 걸렸네요😢.

API 문서는 [여기서 보실 수 있습니다!](https://kimkimsubway.o-r.kr/docs/index.html)

------------------

API 문서 자동화를 위해 제가 선택한 것은 **REST Docs** 였습니다.

- `Swagger`는 프로덕션 코드에 영향을 미친다는 점이 아쉬웠습니다.
- `Postman`을 이용하는 방법은 빌드 및 배포시 자동 생성이 아닌, 문서를 생성하고 싶을 때 매뉴얼로 요청을 보내고 받아보아야 한다는 점에서 절반의 자동화 같다는 생각이 들었습니다.

-----------------

부족한 코드임에도 성심껏 리뷰해주시는 노고에 항상 감사드립니다.

잘 부탁드립니다 :)!

2021-06-03 11:17 UTC, ep1stas1s requested changes
안녕하세요 김김~ 벌써 레벨2 마지막 미션이네요ㅠㅠ
요청을 잘 분리해서 테스트를 진행하셨네요 👍 
몇 가지 코멘트 남겼으니 참고해보시고 궁금한 점 있으시면 Dm 주세요!

2021-06-03 11:17 UTC, ep1stas1s commented on build.gradle
> +	testAnnotationProcessor 'org.projectlombok:lombok'
프로덕션 코드에 추가 했기 때문에, test는 추가 안해도 따로 추가하지 않으셔도 됩니다^_^

2021-06-03 11:17 UTC, ep1stas1s commented on build.gradle
> +	testCompile 'org.springframework.restdocs:spring-restdocs-restassured'
compile과 implementation에 대해 학습해보셔도 좋을 것 같습니다ㅎㅎ

2021-06-03 11:17 UTC, ep1stas1s commented on src/docs/asciidoc/index.adoc
> +김김의 지하철 협업 미션 API docs입니다.
Rest docs 👍 👍 
상세하게 문서를 작성해주셨네요 :)
ErrorResponse를 사용하니, 문서에 공통 에러 객체에 대한 설명도 명시해주면 좋을 것 같아요

저도 처음 세팅이 힘들었지만... 김김과 동일한 이유로 rest docs를 선호합니다ㅎㅎ

2021-06-03 11:17 UTC, ep1stas1s commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +        member.checkPassword(request.getPassword());
findByEmail 메서드에서 optional로 반환하면 상황에 따라 편하게 사용하실 수 있을 것 같아요

아래는 예시일 뿐 꼭 이렇게 사용하지 않으셔도 됩니다ㅎㅎ;
```java
memberDao.findByEmail(request.getEmail())
    .filter(member -> member.checkPassword(request.getPassword()))
    .orElseThrow(new AuthorizationException("잘못된 정보를 기입하셨습니다."));
```

2021-06-03 11:17 UTC, ep1stas1s commented on src/main/java/wooteco/subway/auth/ui/AuthenticationPrincipalOptionalArgumentResolver.java
> +public class AuthenticationPrincipalOptionalArgumentResolver implements HandlerMethodArgumentResolver {
AuthenticationPrincipalArgumentResolver와 크게 다른 역할을 하는 것 같은데, 합치는건 어떨까요??

2021-06-03 11:17 UTC, ep1stas1s commented on src/main/java/wooteco/subway/path/application/PathService.java
> +    public PathResponse findPath(Long source, Long target, Optional<LoginMember> loginMember) {
일반 객체를 주고 받는건 어떨까요~?
매개변수로 Optional을 사용하면 불필요하게 optional 객체를 만들어야 하는 경우가 잦아질 수 있어요

2021-06-03 11:17 UTC, ep1stas1s commented on src/main/java/wooteco/subway/path/application/FarePolicy.java
> +    Fare getTotalFare(SubwayPath subwayPath, Optional<LoginMember> loginMember);
get보단 계산하는 의미의 메서드명이 좋을 것 같네요ㅎㅎ

2021-06-03 11:17 UTC, ep1stas1s commented on src/main/java/wooteco/subway/path/application/PathService.java
>          } catch (Exception e) {
(레거시긴 하지만) 이렇게 예외를 잡는 건 조금 무책임해보여요ㅎㅎㅎ;
너무 상위 예외로 퉁치는 느낌이 있고, 어느 부분에서 나는 예외일지도 감이 안잡히는데 try catch를 없애거나 그 범위를 줄여보는 건 어떨까요~?

2021-06-03 11:17 UTC, ep1stas1s commented on src/main/java/wooteco/subway/path/application/FareCalculator.java
> +        return getFareByDistance(currentFare, 50).add(new Fare(extraFare));
거리에 대한 추가 정책이 생기면 동일한 코드가 또 생길 수 있을 것 같아요...!

2021-06-03 11:17 UTC, ep1stas1s commented on src/main/java/wooteco/subway/GlobalControllerAdvice.java
> +        e.printStackTrace();
Logger를 사용해보시는 건 어떨까요~?

2021-06-03 11:17 UTC, ep1stas1s commented on src/main/java/wooteco/subway/GlobalControllerAdvice.java
> +    public ResponseEntity<ErrorResponse> resolveRequest(BindException e) {
에외로부터 bingResult를 가져오면 어떤 필드에서 어떤 문제가 생겼는지 알 수 있습니다
이런 정보를 에러 메세지에 담아주면 좋을 것 같아요ㅎㅎ

2021-06-03 11:17 UTC, ep1stas1s commented on src/main/java/wooteco/subway/GlobalControllerAdvice.java
> +                .body(new ErrorResponse("예상치 못한 DB 예외가 발생했습니다." + System.getProperty("line.separator") + "에러 메세지: " + e.getMessage()));
500의 경우 상세한 문제까지 클라이언트에 전달할 필요는 없을 것 같습니다ㅎㅎ
클라이언트엔 시스템 에러라고만 내려주고, 개발자가 빠르게 인지할 수 있도록 로그를 남기는 것이 좋습니다 ^_^

2021-06-03 11:17 UTC, ep1stas1s commented on src/test/java/wooteco/subway/path/application/FareCalculatorTest.java
> +class FareCalculatorTest {
도메인 테스트 👍

2021-06-08 14:32 UTC, tributetothemoon commented on build.gradle
> +	testAnnotationProcessor 'org.projectlombok:lombok'
그렇군요...! 무비판적으로 Lombok 공식 홈페이지에 예시로 나와있는 build.gradle을 복사했는데, 정말 위 두 라인은 없어도 잘 돌아가는군요.
- 프로덕션 환경에 의존성을 추가하면, test 환경을 추가로 설정해주지 않아도 된다.

배워갑니다!👍

2021-06-08 14:36 UTC, tributetothemoon commented on build.gradle
> +	testCompile 'org.springframework.restdocs:spring-restdocs-restassured'
compile/implementation의 간/직접 의존 모듈 재빌드 방식의 차이, 그리고 compile은 deprecated 되었다는 것을 배웠습니다.
이에 [커밋](https://github.com/woowacourse/atdd-subway-fare/pull/46/commits/0bd6675ae61df3b9caf1ef9bc71cb369f3304531)을 통해 compile 옵션은 Implementation으로 바꾸었습니다. 감사합니다!!🙇‍♂️

2021-06-08 14:38 UTC, tributetothemoon commented on src/docs/asciidoc/index.adoc
> +김김의 지하철 협업 미션 API docs입니다.
[커밋](https://github.com/woowacourse/atdd-subway-fare/pull/46/commits/524fa800bfb945e23fbcae63b9fed4ef28fcd0f2)을 통해 반영하였습니다!

아쉽게도 현재 클라우드 인스턴스는 방학이라 정지되어 웹상으로 문서 확인이 안 되네요😢.

2021-06-08 14:41 UTC, tributetothemoon commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +        member.checkPassword(request.getPassword());
김고래의 의견대로 findByEmail은 Optional을 리턴하는 것이 맞는 것 같습니다!
어디까지나 서비스 이용자가 직접 이메일을 기입하는만큼, 오류의 발생 확률이 높고 이 때마다 예외를 발생시켜 처리하기에는 예외 처리는 다소 비싼 연산이라고 생각합니다. 따라서 쿼리 결과가 0개여도 예외를 발생시키지 않아도 되도록 Optional을 리턴해주는 것이 좋은 것 같습니다. 또한 예시 코드로 보여주신대로 코드도 더 말끔해지구요!
[반영해보았습니다!](https://github.com/woowacourse/atdd-subway-fare/pull/46/commits/5951b62bbc26ae39a29923b6ebd73ce40d61fc0e)
좋은 피드백 감사합니다!😄🙇‍♂️

2021-06-08 14:56 UTC, tributetothemoon commented on src/main/java/wooteco/subway/auth/ui/AuthenticationPrincipalOptionalArgumentResolver.java
> +public class AuthenticationPrincipalOptionalArgumentResolver implements HandlerMethodArgumentResolver {
이 Optional<LoginMember>가 생겨난 이유는, 회원/비회원 모두에게 제공되지만 서로 다른 결과를 응답하는 서비스(경로 조회와 이를 통한 요금 조회) 때문이었습니다. 레거시 코드 상으로는 Controller에서 LoginMember를 받으면, ArgumentResolver가 비회원의 경우 예외를 발생시켜 서비스를 이용할 수 없게 만들도록 되어있었습니다. 따라서 비회원은 빈 객체를 Argument로 Resolve 하도록 이 OptionalArgumentResolver를 만들었습니다.
따라서 합쳐보는 것을 제안하신 김고래의 의견을 들으니 많은 고민이 들었는데요, 하지만 돌이켜 생각해보니 이는 ArgumentResolver가 인가까지 진행하는 책임을 가지고 있어서 생기는 문제였습니다.
따라서 [토큰의 유효성에 따라 서비스에 대한 인가를 담당하는 것은 LoginInterceptor로 위임하고, ArgumentResolver는 비회원과 같이 토큰이 없는 경우 Null 객체인 LoginMember를 던지는 것으로 다시 리팩토링을 해보았습니다.](https://github.com/woowacourse/atdd-subway-fare/pull/46/commits/1db1a9c3dc920795c235cb9acdb6cff6dd2e158d)

2021-06-08 14:59 UTC, tributetothemoon commented on src/main/java/wooteco/subway/path/application/PathService.java
> +    public PathResponse findPath(Long source, Long target, Optional<LoginMember> loginMember) {
상단의 [코멘트](https://github.com/woowacourse/atdd-subway-fare/pull/46#discussion_r647525902)를 통해 바꾸어보았습니다! 🙂

2021-06-08 15:02 UTC, tributetothemoon commented on src/main/java/wooteco/subway/path/application/FarePolicy.java
> +    Fare getTotalFare(SubwayPath subwayPath, Optional<LoginMember> loginMember);
생각해보니 그렇네요😅! [반영](https://github.com/woowacourse/atdd-subway-fare/pull/46)해보았습니다!

2021-06-08 15:05 UTC, tributetothemoon commented on src/main/java/wooteco/subway/path/application/PathService.java
>          } catch (Exception e) {
말씀하신대로 레거시라서 대충 지나쳐간 느낌이 있습니다😢. [try catch문은 삭제하고, ControllerAdvice를 통해 잡을 수 있도록 변경해보았습니다!](https://github.com/woowacourse/atdd-subway-fare/pull/46/commits/d0f5f7545055922f6154de3f65046f49b973eed4)

2021-06-08 15:12 UTC, tributetothemoon commented on src/main/java/wooteco/subway/path/application/FareCalculator.java
> +        return getFareByDistance(currentFare, 50).add(new Fare(extraFare));
타당한 지적이라고 생각합니다😢👍. enum 객체를 생성하여 [수정](https://github.com/woowacourse/atdd-subway-fare/pull/46/commits/413d42bf2bfeaf010caea10b0027f4a4b958a4f4)해보았습니다!

2021-06-08 15:16 UTC, tributetothemoon commented on src/main/java/wooteco/subway/GlobalControllerAdvice.java
> +        e.printStackTrace();
로깅이 중요하다는 것은 알면서도 차일피일 미루고 있었네요😢. 덕분에 서투르지만, 처음으로 로깅을 [설정](https://github.com/woowacourse/atdd-subway-fare/pull/46/commits/e83a1a955ec9afe86d0dd3ba44f6dddc2fc725cd)해볼 수 있었습니다. 좋은 피드백 감사합니다😄🙇‍♂️!

2021-06-08 15:19 UTC, tributetothemoon commented on src/main/java/wooteco/subway/GlobalControllerAdvice.java
> +    public ResponseEntity<ErrorResponse> resolveRequest(BindException e) {
BindException으로 부터 bindResult를 가져올 수 있는 건 처음 알았네요!!
덕분에, [ControllerAdvice에서 어떠한 필드에서 어떤 문제가 생겼는지를 담아줄 수 있도록 코드를 작성](https://github.com/woowacourse/atdd-subway-fare/pull/46/commits/71533b438ee0521be11721c75181b50bc04686f3)해보았습니다.

> 예시
![image](https://user-images.githubusercontent.com/49346677/121212369-3eea1d00-c8b8-11eb-8d74-d49e429a51de.png)

2021-06-08 15:22 UTC, tributetothemoon commented on src/main/java/wooteco/subway/GlobalControllerAdvice.java
> +                .body(new ErrorResponse("예상치 못한 DB 예외가 발생했습니다." + System.getProperty("line.separator") + "에러 메세지: " + e.getMessage()));
에러에 서버 내부의 민감성 정보가 드러날 수도 있고하니 말씀해주신대로, 로그로 남겨놓고 서버 개발자가 참고하는 것이 좋을 것 같습니다.
[반영](https://github.com/woowacourse/atdd-subway-fare/pull/46/commits/8173d5c57acdf52aef808d032e9c602e0d96cb13)해보았습니다!👍

2021-06-08 15:22 UTC, tributetothemoon commented on src/test/java/wooteco/subway/path/application/FareCalculatorTest.java
> +class FareCalculatorTest {
👍!!

2021-06-08 23:32 UTC, ep1stas1s approved these changes
피드백 잘 반영해주셨네요 👍 
추가적으로 간단한 코멘트 남겼으니 확인해주세요
레벨2 미션 진행하시느라 고생하셨습니다~!

2021-06-08 23:32 UTC, ep1stas1s commented on src/docs/asciidoc/index.adoc
> +=== 응답 거절 형식
로컬에서 확인 했습니다 👍 👍

2021-06-08 23:32 UTC, ep1stas1s commented on src/main/java/wooteco/subway/auth/application/AuthService.java
>  @Transactional
읽기 전용을 명시하면 약간의 성능 향상도 볼 수 있고, 나중에 DB를 분리할 때도 용이해요 :)
```java
@Transactional(readOnly = true)
public Line findLineById(Long id) { ...}
```
저의 경우는 이러한 반복을 줄이기 위해 class level에 `@Transactional(readOnly = true)`를 명시하고, cud가 필요한 부분에만 따로 `@Transactional` 어노테이션을 붙이는 방법을 사용합니다

2021-06-08 23:32 UTC, ep1stas1s commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +        return new LoginMember();
isPresent()는 사실상 null check와 동일하므로 지양하는 것이 좋습니다 :)
```java
return memberDao.findByEmail(email)
                .map(member -> new LoginMember(member.getId(), member.getEmail(), member.getAge()))
                .orElseGet(LoginMember::new);
```

2021-06-08 23:32 UTC, ep1stas1s commented on src/main/java/wooteco/subway/auth/infrastructure/LoginInterceptor.java
> +        return HandlerInterceptor.super.preHandle(request, response, handler);
`HandlerInterceptor.super.preHandle(request, response, handler)`는 무조건 true를 반환하니 아래와 같이 사용해도 좋을 것 같아요ㅎㅎ
```suggestion
        return authService.validateToken(credentials);
```

2021-06-08 23:32 UTC, ep1stas1s commented on src/main/java/wooteco/subway/member/application/MemberService.java
> +                .orElseThrow(InvalidMemberInformationException::new);
요런 부분은 반복되니 service단에서 따로 메서드로 빼도 되겠네요ㅎㅎ

2021-06-08 23:32 UTC, ep1stas1s commented on src/main/java/wooteco/subway/path/application/DistanceExtraFarePolicy.java
> +    OVER_50KM(50, 8.0);
UNDER, OVER가 있어서 혼돈이 있을 것 같은데, 기준을 명확히 할 필요가 있을 것 같아요

2021-06-08 23:32 UTC, ep1stas1s commented on src/main/java/wooteco/subway/GlobalControllerAdvice.java
> +    Logger logger = LoggerFactory.getLogger(GlobalControllerAdvice.class);
```suggestion
    private final Logger logger = LoggerFactory.getLogger(GlobalControllerAdvice.class);
```

2021-06-08 23:32 UTC, ep1stas1s commented on src/main/java/wooteco/subway/GlobalControllerAdvice.java
> +@ControllerAdvice
```suggestion
@RestControllerAdvice
```

2021-06-08 23:32 UTC, ep1stas1s commented on src/main/java/wooteco/subway/dto/BindErrorResponse.java
> +    private final Map<String, String> causes;
프론트와 커뮤니케이션이 중요하겠지만, map 형태로 하면 필드가 계속 바뀌기 때문에 list형식으로 메세지를 넘겨주는 것이 좋을 것 같아요ㅎㅎ

2021-06-08 23:32 UTC, merged

2021-06-20 17:54 UTC, tributetothemoon commented on src/main/java/wooteco/subway/auth/application/AuthService.java
> +        return new LoginMember();
분기문을 사용할 때 못내 찝찝한 면이 있었는데 그렇군요😢.
Optional의 체이닝 메소드를 잘 알지 못했는데 보여주신 예시코드를 보니 Optional의 존재 이유가 더 잘 드러나는 것 같았습니다!!
[수정](https://github.com/tributetothemoon/atdd-subway-fare/commit/e053b2cb810e4acc823cf00ab4757351b9ffa600)하였습니다 :)!!

2021-06-20 17:55 UTC, tributetothemoon commented on src/main/java/wooteco/subway/auth/infrastructure/LoginInterceptor.java
> +        return HandlerInterceptor.super.preHandle(request, response, handler);
너무 IDE의 자동 완성을 무비판적으로 수용했네요😭. [수정](https://github.com/tributetothemoon/atdd-subway-fare/commit/7a4145206cdeda1ce7feece7b9bcef605b90a244)했습니다!!

2021-06-20 17:55 UTC, tributetothemoon commented on src/main/java/wooteco/subway/member/application/MemberService.java
> +                .orElseThrow(InvalidMemberInformationException::new);
좋은 지적이라고 생각합니다!🙇‍♂️!
[커밋](https://github.com/tributetothemoon/atdd-subway-fare/commit/c4f5d778ab7f44f94f2b651b603e6035bf7e2c4e)

2021-06-20 17:57 UTC, tributetothemoon commented on src/main/java/wooteco/subway/path/application/DistanceExtraFarePolicy.java
> +    OVER_50KM(50, 8.0);
변수/상수 명을 짓는 건 항상 어려운 것 같습니다😢.
몇 가지 생각을 해보다가, 조금 길어져도 영어 문법에 따라 정확하게 풀어쓰는 것이 좋겠다고 생각했습니다.
[수정](https://github.com/tributetothemoon/atdd-subway-fare/commit/f69e13d1c3ef09c9a7fea2604dda3dacf4a812d1)해보았습니다 !!

2021-06-20 17:57 UTC, tributetothemoon commented on src/main/java/wooteco/subway/GlobalControllerAdvice.java
> +    Logger logger = LoggerFactory.getLogger(GlobalControllerAdvice.class);
이크😨
[수정](https://github.com/tributetothemoon/atdd-subway-fare/commit/65161bcab48e9629b4c5bb86f3401601b29d05e5)하였습니다...

2021-06-20 18:00 UTC, tributetothemoon commented on src/main/java/wooteco/subway/GlobalControllerAdvice.java
> +@ControllerAdvice
앗!! 감사합니다!
에러 상황에서도 ResponseEntity를 리턴해서 별 다르지 않게 구동하고 있었을 뿐이었네요...
주의하겠습니다!
[수정](https://github.com/tributetothemoon/atdd-subway-fare/commit/94216895ba3fbe0c6182c3276761745c2bd01c0c)하였습니다.

2021-06-22 11:40 UTC, tributetothemoon commented
# 학습로그
## API 명세서 자동화
- Swagger, RestDocs 등을 이용하여 API 명세서의 자동화를 할 수 있다.
- 간략히 얘기하자면, RestDocs는 테스트 코드 작성을 통해 자동화를 실행하고, Swagger는 프로덕션 코드에 어노테이션을 활용하여 API 명세를 작성한다.

## 태그
- API 문서 자동화