[스프링 - 협업 미션] 에드(박성진) 미션 제출합니다.
woowacourse/atdd-subway-fare pull request #48
Opened 2021-06-01 06:17 UTC by sjpark-dev

안녕하세요 재연링! 😆

레벨1 체스 미션 이후에 다시 뵙네요.
그 때 해주신 조언 덕분에 무사히 레벨2 마지막 미션까지 올 수 있었습니다! (정말 감사합니다 🙇‍♂️)
레벨2의 마지막 미션도 재연링과 함께할 수 있어서 너무 기뻐요. 🎉

프런트와 협업을 하면서 정확한 소통의 중요성을 깨달았네요.
서로 같은 말을 하더라도 생각하는게 다를 수 있더라고요 🤣

프런트와 의논한 주요 내용은
1. LineController의 `/map` API의 설계와 구현
2. 예외 발생시의 Status Code와 메세지 통일
3. API의 문서화
가 있습니다.

API 문서화를 위해서 처음에는 Swagger를 사용하다가 
원인 모를 에러 떄문에  Spring Rest docs로 바꿨는데
재연링은 실제로 어떤 API 문서화 도구를 선호하시나요?

그리고 지금은 예외를 하나의 패키지에 모으고 세분화해서 처리를 하고 있는데
재연링을 예외 관리를 어떻게 하는지 궁금하네요!

소중한 시간 내주셔서 감사합니다. 👍

2021-06-02 12:00 UTC, jaeyeonling requested changes
안녕하세요 에드! 다시 만나게 되어 반가워요 😄
요구사항에 맞게 잘 구현해주셨습니다 💯
질문의 답변과 코멘트 남겨두었으니 확인 부탁드려요~!!

2021-06-02 12:00 UTC, jaeyeonling commented on build.gradle
> +	id 'org.asciidoctor.convert' version '1.5.6'
asciidoctor 👍

Q. API 문서화를 위해서 처음에는 Swagger를 사용하다가
원인 모를 에러 떄문에 Spring Rest docs로 바꿨는데
재연링은 실제로 어떤 API 문서화 도구를 선호하시나요?

A. 상황에 따라 다르지만 스프링 기반의 서비스를 구현한다면 테스트를 강제한다는 장점(단점..?)이 있는 Rest docs를 사용하는 것을 선호합니다 ㅎㅎ
최근 프로젝트에 gRPC를 사용하여 protobuf으로 데이터 구조를 잡고 프로젝트를 진행했는데, 문서화에 대한 비용이 거의 사라져 정말 편안하게 개발을 했었네요 :)

2021-06-02 12:00 UTC, jaeyeonling commented on src/main/java/wooteco/subway/auth/ui/AuthFareArgumentResolver.java
> +public class AuthFareArgumentResolver implements HandlerMethodArgumentResolver {
Member에 대한 정보에 포함하지 않고 나이에 대한 Resolver를 따로 분리해주신 이유가 있을까요!?

2021-06-02 12:00 UTC, jaeyeonling commented on src/main/java/wooteco/subway/docs/README.md
> +# 스프링 - 협업 미션 👻
요구사항 분석 👍

2021-06-02 12:00 UTC, jaeyeonling commented on src/main/java/wooteco/subway/exception/SubwayException.java
> +    ErrorResponse errorResponse;
```suggestion
    private final HttpStatus httpStatus;
    private final ErrorResponse errorResponse;
```

접근제어자를 생략하신 것은 의도된 내용일까요!?

2021-06-02 12:00 UTC, jaeyeonling commented on src/main/java/wooteco/subway/exception/badrequest/BadRequestException.java
> +public class BadRequestException extends SubwayException {
```suggestion
public abstract class BadRequestException extends SubwayException {
```

BadRequestException은 상속으로만 사용하고 있는데, 계층을 위해서만 사용한다면 abstract를 통해 의도를 전달할 수 있습니다 :)
추가적으로 저는 모든 클래스를 abstract 또는 final로만 작성하는데 그 이유에 대해 고민해보면 좋을 것 같아요 ㅎㅎ

2021-06-02 12:00 UTC, jaeyeonling commented on src/main/java/wooteco/subway/exception/badrequest/DuplicateLineException.java
> +package wooteco.subway.exception.badrequest;
Q. 그리고 지금은 예외를 하나의 패키지에 모으고 세분화해서 처리를 하고 있는데
재연링을 예외 관리를 어떻게 하는지 궁금하네요!

A. 저는 SubwayException, BadRequestException과 같이 공통으로 처리되는 부분이 아닌, 도메인에 해당하는 exception은 도메인에 위치하는 것을 선호합니다!
도메인에 맞게 옮겨두면 코드를 파악하기도 쉽고, 추후 MSA 구조로 변경 시 패키지 단위로 다소 간편하게 옮길 수 있다는 장점도 존재합니다 :)

2021-06-02 12:00 UTC, jaeyeonling commented on src/main/java/wooteco/subway/line/application/LineService.java
> +    public SectionResponse addLineStation(Long lineId, SectionRequest request) {
해당 메서드 중간에서 에러가 발생한다면 어떠한 상황이 발생할 수 있을지 고민해보아요

2021-06-02 12:00 UTC, jaeyeonling commented on src/main/java/wooteco/subway/line/dao/LineDao.java
> +        jdbcTemplate.update(sql, new Object[]{newLine.getName(), newLine.getColor(), newLine.getExtraFare(), newLine.getId()});
```suggestion
        jdbcTemplate.update(sql, newLine.getName(), newLine.getColor(), newLine.getExtraFare(), newLine.getId());
```

이미 아시는 내용일테지만, Object 배열 없이 가변인자를 활용할 수 있답니다 :)

2021-06-02 12:00 UTC, jaeyeonling commented on src/main/java/wooteco/subway/line/domain/fare/Fare.java
> +    public int calculateTotalFare(int distance, int maxExtraLineFare) {
나이에 따른 금액 추상화를 잘 해주셨는데요!
거리에 따른 금액도 추상화는 진행하지 않으신 이유가 있을까요!?

2021-06-02 12:00 UTC, jaeyeonling commented on src/main/java/wooteco/subway/line/ui/LineController.java
> +    public ResponseEntity<List<LinesResponse>> findAllInfo() {
위 findAllLines와 어떠한 차이가 있을까요!?

2021-06-02 12:00 UTC, jaeyeonling commented on src/main/java/wooteco/subway/member/domain/LoginMember.java
> +    }
age가 19일 경우 모든 경우에 true가 나오는데 의도된 내용이 맞을까요!?

2021-06-02 12:00 UTC, jaeyeonling commented on src/test/java/wooteco/subway/path/PathDocument.java
> +public class PathDocument extends Documentation {
테스트코드가 탄탄하네요 👍

2021-06-03 01:57 UTC, sjpark-dev commented on src/main/java/wooteco/subway/exception/SubwayException.java
> +    ErrorResponse errorResponse;
아니요 😅 깜빡했네요!

2021-06-03 02:22 UTC, sjpark-dev commented on src/main/java/wooteco/subway/exception/badrequest/BadRequestException.java
> +public class BadRequestException extends SubwayException {
불변 클래스를 말씀하시는 거군요!
변경 가능성을 최소화하기 위한 의도로 클래스 앞에 final을 붙이는 것일까요?
그리고 변경 가능한 클래스는 명시적으로 표현 하기 위해서 abstract를 붙이는 것일까요?

2021-06-03 06:19 UTC, sjpark-dev commented on src/main/java/wooteco/subway/exception/badrequest/DuplicateLineException.java
> +package wooteco.subway.exception.badrequest;
다음에는 재연링의 방식대로 해보겠습니다!

2021-06-03 06:30 UTC, sjpark-dev commented on src/main/java/wooteco/subway/line/application/LineService.java
> +    public SectionResponse addLineStation(Long lineId, SectionRequest request) {
DB에서 기존의 section들을 지우고 다시 채우려고 할 때 에러가 발생한다면
DB는 이미 지워졌으니 난감하겠네요. 😅
@Transactional을 붙여줘야 할 것 같네요!
그런데 @Transactional은 메소드 단위로 붙이는게 좋을까요? 아니면 클래스 단위로 붙이는게 좋을까요?

2021-06-03 07:20 UTC, sjpark-dev commented on src/main/java/wooteco/subway/line/ui/LineController.java
> +    public ResponseEntity<List<LinesResponse>> findAllInfo() {
이 API는 프론트와 협의해서 만들었는데요
자세히 보면 위의 findAllLines는 LineResponse의 List를 반환하고
findAllInfo는 LinesResponse의 List를 반환합니다.
LinesResponse는 LineResponse에서 List<Station>필드를 뺐습니다.

2021-06-03 07:29 UTC, sjpark-dev commented on src/main/java/wooteco/subway/line/ui/LineController.java
> +    public ResponseEntity<List<LinesResponse>> findAllInfo() {
사실 LineResponse는 List<Station>만 갖고 LinesResponse는 List<Section>만 가졌는데
프론트의 요청으로 LineResponse에 List<Section>을 추가해서
둘의 차이가 애매해졌습니다.

2021-06-03 07:47 UTC, sjpark-dev commented on src/main/java/wooteco/subway/line/domain/fare/Fare.java
> +    public int calculateTotalFare(int distance, int maxExtraLineFare) {
생각을 못했네요 😅 시도해보겠습니다!

2021-06-03 07:51 UTC, sjpark-dev commented on src/main/java/wooteco/subway/member/domain/LoginMember.java
> +    }
수정해야겠네요.

2021-06-04 13:18 UTC, sjpark-dev commented on src/main/java/wooteco/subway/auth/ui/AuthFareArgumentResolver.java
> +public class AuthFareArgumentResolver implements HandlerMethodArgumentResolver {
기존 Resolver를 활용할 생각을 못했네요 😅

2021-06-04 13:31 UTC, sjpark-dev commented
안녕하세요 재연링! 😊

리팩토링 과정에서 두가지 주요 변경점이 있었습니다.

1. 나이에 따른 금액 로직에 `AuthenticationPrincipalArgumentResolver`를 활용
2. 거리에 따른 금액을 `DistancePolicy`로 추상화

소중한 시간 내주셔서 감사합니다. 👍

2021-06-05 05:09 UTC, jaeyeonling requested changes
코멘트를 잘 반영해주셨습니다 👍 
질문의 답변 남겨두었으니 확인해주시면 머지하겠습니다 :)

2021-06-05 05:09 UTC, jaeyeonling commented on src/main/java/wooteco/subway/line/application/LineService.java
> +@Transactional
Q. DB에서 기존의 section들을 지우고 다시 채우려고 할 때 에러가 발생한다면
DB는 이미 지워졌으니 난감하겠네요. 😅
@Transactional을 붙여줘야 할 것 같네요!
그런데 @Transactional은 메소드 단위로 붙이는게 좋을까요? 아니면 클래스 단위로 붙이는게 좋을까요?


A. 저는 개인적으로 클래스 레벨에 Transactional을 사용하는 것을 선호하지 않습니다 
트랜잭션은 굉장히 비용이 큰 작업이고, 불필요한 트랜잭션으로 성능이 낮아지는 문제도 있지만 더 큰 문제는 의도되지 않은 트랜잭션으로 인해 데드락이 발생할 수 있다 라는 것이 생각입니다 
실제 현업에서 대규모 트래픽을 처리하기 위해 데드락이 발생하지 않도록 설계하는 것이 굉장히 중요한데요 
개발하는 과정에서도 이 기능에 데드락이 발생할 요소가 있을까? 트랜잭션을 꼭 잡아야 가능한 기능일까? 구조를 변경하여 락이 필요 없는 구조로 바꿀 수 없을까? 에 대해 끊임없이 고민하게 되는데, 이러한 고민을 하는 시점이 저는 메서드에 Transactional 처리를 하는 시점에 가장 많이 하는 것 같습니다

또한 클래스마다 트랜잭션과 격리레벨이 정해지는 것이 아닌 기능(메서드)단위로 처리되기 때문에 클래스에 적용하여 공통으로 처리할 필요가 있을까? 라는 의문이 들었습니다 ㅎㅎ

2021-06-05 05:09 UTC, jaeyeonling commented on src/main/java/wooteco/subway/exception/badrequest/BadRequestException.java
> +public abstract class BadRequestException extends SubwayException {
Q. 불변 클래스를 말씀하시는 거군요!
변경 가능성을 최소화하기 위한 의도로 클래스 앞에 final을 붙이는 것일까요?
그리고 변경 가능한 클래스는 명시적으로 표현 하기 위해서 abstract를 붙이는 것일까요?

A. 내가 어떠한 의도로 해당 클래스를 설계하였는지 코드를 통해 의도를 나타내는 것이 가장 큰 이유라고 볼 수 있어요!
상속을 원하지 않는 클래스를 설계 하였을 때 final을 붙이지 않는다면 누군가 클래스를 의도하지 않은 방식으로 사용할 수 있는 문제가 있습니다 :)

2021-06-05 06:24 UTC, jaeyeonling approved these changes
수 많은 코멘트 반영하시느라 고생 많으셨어요💯
이만 머지하도 할게요!!!
다음 레벨도 화이팅입니다 😄

2021-06-05 06:24 UTC, merged

2021-06-15 05:50 UTC, sjpark-dev commented
# 학습 로그

## Spring IoC Container
- IoC는 Inversion of Control의 약자로 DI(dependency injection, 의존성 주입)로도 알려져 있다.
- Spring IoC Container는 BeanFactory 인터페이스와 ApplicationContext 서브 인터페이스로 이루어져 있다.
- BeanFactory는 모든 타입의 Object를 관리할 수 있는 configuration framework와 basic functionality를 제공하고, ApplicationContext는 이에 더해 enterprise-specific functionality를 제공한다.
- Spring에서 application의 핵심 토대를 이루는 object들을 bean이라 부른다.
- Bean은 Spring IoC Container가 인스턴스화하고, 조립하고, 관리하는 object이다.
- Spring IoC Container는 XML 또는 Java annotations의 metadata에 따라 object를 인스턴스화하고, 구성하고, 조립한다.
- https://docs.spring.io/spring-framework/docs/current/reference/html/core.html#beans
## 태그
- Spring, IoC, Container, Bean, BeanFactory, ApplicationContext