[스프링 - 협업 미션] 현구막(최현구) 미션 제출합니다.
woowacourse/atdd-subway-fare pull request #53
Opened 2021-06-04 14:46 UTC by Hyeon9mak

안녕하세요 데이브! 처음 뵙겠습니다!
테코톡에 많은 시간을 투자해서 제출이 많이많이많이많이 늦었습니다 😭 
적절히 시간을 분배하는 스킬이 절실하네요...

API 요청 주소 : ~~https://hyeon9mak-subway.o-r.kr/~~
REST DOCS 주소 : ~~https://hyeon9mak-subway.o-r.kr/docs/api-guide.html~~
(현재 서버가 일시적으로 내려가있습니다..! 6월 5일 오전중에 다시 올리겠습니다!)

프로젝트를 진행하는 동안 질문이 몇 가지 생겼습니다!

## 1. 패키지 구조에 따른 중복코드 생성
`Line`, `Station`, `Section` 객체들의 경우 `Id`, `Name`, `Color` 등의 필드 객체 가지고 있는데,
패키지가 서로 갈라져있다보니 완전히 동일한, 중복된 클래스파일들이 계속 생성됐어요. 현재와 같은 형태의 패키지 구조가 가진 단점인거 같아요.

별도로 `Common` 이름의 패키지를 개설해서 중복 코드를 최대한 줄이는게 나을지 고민도 해보았는데, 
현재 패키지 구조의 장점(기능별 응집도)이 희석되는거 같아서 고민입니다..! 
데이브는 어떻게 생각하시나요?!

## 2. DAO 쪽에 boolean 을 반환하는 메서드를 둬도 될까요?
`Dao.isExist(Some thing)` 형태의 boolean을 반환하는 메서드를 둬도 괜찮은지 고민입니다!
"DAO는 DB CRUD 역할에만 충실해야한다." 라는 생각 때문에 최대한 지양하고 Service 단에서 처리했는데, 
간혹 "지양하지 않았더라면 지금 코드가 더 깔끔해지지 않았을까?" 라는 생각이 들 때가 있더라구요... 🥵 

## 3. Fare Policy를 Enum화 시키는게 좋았을지 고민돼요
우선 현재는 Enum을 사용하지 않고 책임연쇄패턴을 적용해서 나이별/거리별 요금 정책을 관리하고 있습니다!

그런데 요금 관련된 정책은 언제든지 얼마든지 추가/변경 될 수 있고, 이것들을 한 눈에 볼 수 있게 해주는게 Enum의 장점이라고 생각들었어요.
그동안 Enum은 지양하는 편이었는데, "바로 이럴 때 Enum을 써야하나?" 라는 생각이 드네요.... 🙄 
데이브는 어떻게 생각하시는지 궁금합니다!

## 4. Optional 사용
(이 질문은 개인적으로 데이브의 의견이 궁금해서요!!)

중복된 이름으로 Station 신규 등록을 시도했을 때,

- Service 단에서 Dao.findByName 조회를 통해 Duplicate 임을 잡아내기
- Dao.insert 까지 시도한 후에 Uniq 옵션으로 인해 DuplicateKeyException 발생하면 이걸 Catch해서 별도 exception을 다시 던지기

개인적으로 후자는 DB Exception에 의존적인 구조를 가질거 같아서 전자로 시도해보려하는데, 혹시나 후자가 더 나은 방법일까 고민 됐었어요!
Optional이 DB 조회에 실패했을 경우에도 추가 로직을 수행할 가능성을 보여준다고 생각해서 최대한 사용을 지양하려 했거든요..
거기다가 “JPA가 Optional로 처리하기 때문에 더욱 Optional을 쓰면 안된다. JPA를 모방하기 위함인지, 별도로 조회 실패시에도 로직을 수행시키기 위해 사용한것인지 구별이 어렵다.” 라고 까지 생각을 했었습니다.

여러 크루들, 리뷰어분들과 이야기를 나눈 덕분에 현재는 "Optional 을 통해서 조회에 실패한 상황을 무조건 예외로 볼거냐, 비즈니스 로직으로 볼거냐 관점을 나누게 해준다." 로 생각하고 있습니다!

혹시 데이브는 Optional 을 채택하실 때 어떤걸 기준으로 사용하시는지 궁금해요!

---

질문은 여기까지 입니다!
리뷰 잘 부탁드리겠습니다! 🙇‍♂️ 
감사합니다!

2021-06-06 09:06 UTC, dave915 commented
>1. 패키지 구조에 따른 중복코드 생성
Line, Station, Section 객체들의 경우 Id, Name, Color 등의 필드 객체 가지고 있는데,
패키지가 서로 갈라져있다보니 완전히 동일한, 중복된 클래스파일들이 계속 생성됐어요. 현재와 같은 형태의 패키지 구조가 가진 단점인거 같아요.
별도로 Common 이름의 패키지를 개설해서 중복 코드를 최대한 줄이는게 나을지 고민도 해보았는데,
현재 패키지 구조의 장점(기능별 응집도)이 희석되는거 같아서 고민입니다..!
데이브는 어떻게 생각하시나요?!

각 도메인에 있는 같은 이름을 한 VO들이 중복 되는 것 같아 고민 하시는 것 같네요! 지금 같은 패키지 구조에서는 지금 현구막이 하신 것 처럼 각 도메인 별로 VO 를 만들어 놓는게 좋을 것 같아요. 같은 이름을 가진 VO더라도 도메인에 따라 다른 기능을 갖을 수도 있기 때문에 중복코드라고 보지 않는 시선도 있더라구요! 

>2. DAO 쪽에 boolean 을 반환하는 메서드를 둬도 될까요?
Dao.isExist(Some thing) 형태의 boolean을 반환하는 메서드를 둬도 괜찮은지 고민입니다!
"DAO는 DB CRUD 역할에만 충실해야한다." 라는 생각 때문에 최대한 지양하고 Service 단에서 처리했는데,
간혹 "지양하지 않았더라면 지금 코드가 더 깔끔해지지 않았을까?" 라는 생각이 들 때가 있더라구요... 🥵

저는 DAO 에서 단순 CRUD만 하는 것이 아니라, DB와 관련된 역할을 한다고 생각하고 있기 때문에 DB의 데이터 유무를 판별하는 `Dao.isExist(Some thing) 형태의 boolean을 반환하는 메서드` 는 괜찮다고 보고 있습니다 :) 

>3. Fare Policy를 Enum화 시키는게 좋았을지 고민돼요
우선 현재는 Enum을 사용하지 않고 책임연쇄패턴을 적용해서 나이별/거리별 요금 정책을 관리하고 있습니다!
그런데 요금 관련된 정책은 언제든지 얼마든지 추가/변경 될 수 있고, 이것들을 한 눈에 볼 수 있게 해주는게 Enum의 장점이라고 생각들었어요.
그동안 Enum은 지양하는 편이었는데, "바로 이럴 때 Enum을 써야하나?" 라는 생각이 드네요.... 🙄
데이브는 어떻게 생각하시는지 궁금합니다!

저도 여러 조건들에 따라 동작이 달라지는 기능은 Enum이 한눈에 보기 좋더라구요! 그래서 이런 부분에는 Enum을 적극 사용하고 있습니다 ㅎㅎ 

>4. Optional 사용
(이 질문은 개인적으로 데이브의 의견이 궁금해서요!!)
중복된 이름으로 Station 신규 등록을 시도했을 때,
Service 단에서 Dao.findByName 조회를 통해 Duplicate 임을 잡아내기
Dao.insert 까지 시도한 후에 Uniq 옵션으로 인해 DuplicateKeyException 발생하면 이걸 Catch해서 별도 exception을 다시 던지기
개인적으로 후자는 DB Exception에 의존적인 구조를 가질거 같아서 전자로 시도해보려하는데, 혹시나 후자가 더 나은 방법일까 고민 됐었어요!
Optional이 DB 조회에 실패했을 경우에도 추가 로직을 수행할 가능성을 보여준다고 생각해서 최대한 사용을 지양하려 했거든요..
거기다가 “JPA가 Optional로 처리하기 때문에 더욱 Optional을 쓰면 안된다. JPA를 모방하기 위함인지, 별도로 조회 실패시에도 로직을 수행시키기 위해 사용한것인지 구별이 어렵다.” 라고 까지 생각을 했었습니다.
여러 크루들, 리뷰어분들과 이야기를 나눈 덕분에 현재는 "Optional 을 통해서 조회에 실패한 상황을 무조건 예외로 볼거냐, 비즈니스 로직으로 볼거냐 관점을 나누게 해준다." 로 생각하고 있습니다!
혹시 데이브는 Optional 을 채택하실 때 어떤걸 기준으로 사용하시는지 궁금해요!

저는 Optional을 값이 있다는 가정 하에 `이런 일련의 과정들을 처리 할거야 아님 이 로직 or 오류!` 이런 관점에서 사용하고 있어요. 
말씀 주신 조회에대한 실패 상황을 예외로 볼것인가 비즈니스로직을 볼것인가는 Optional 사용 여부보단 Dao에서 값이 없을때 오류를 발생 시킬 것인가 아닌가에 관련된 고민이 아닌가? 라는 생각이 드네요! 🤔 
만약 고민이 `Dao에서 값을 Optional로 값을 반환 할 것인가?`라면 저는 Optional로 반환하지 않고 사용하는 쪽에서 필요한 경우에만 Optional로 값싸서 처리하고 있어요 :)

2021-06-06 09:26 UTC, dave915 requested changes
현구막 안녕하세요! 
구현 잘 해주셨네요 👍 
질문에 관한 코멘트와 피드백 남겼어요. 확인 부탁드려요! 
궁금한 점 있으면 언제든지 질문 주세요 :)

2021-06-06 09:26 UTC, dave915 commented on src/main/java/wooteco/subway/path/application/PathService.java
`LineService` 에 `SectionService` 가 있는데, `PathService` 에서 이 작업을 해줄 필요가 있을까요?

2021-06-06 09:26 UTC, dave915 commented on src/main/java/wooteco/subway/path/application/FareService.java
> +        teenagerAgePolicy.setNextPolicy(childAgePolicy);
음.. 말씀주신대로 Enum을 사용하는 편이 좋지 않을까 생각이 들어요 ㅠㅠ 
그리고 하나의 Policy가 다음 Policy를 꼭 알고 있어야 할까요? 이 부분도 고민해보면 좋을 것 같아요!

2021-06-06 09:26 UTC, dave915 commented on src/main/java/wooteco/subway/auth/ui/AuthenticationPrincipalArgumentResolver.java
>          }
👍

2021-06-06 09:26 UTC, dave915 commented on src/main/resources/logback-access.xml
> +  <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
다른 크루들은 빌드 스크립트 파일이 있어서 거기다 남겼는데, 현구막은 없어서 여기다 남길게요!
혹시 jar파일 실행할때 로그파일을 만들어 주기 위해 1>log.out 2>&1 이런 식으로 실행 시켜주지 않았나요?
logback fileappender 한번 찾아보면 좋을 것 같아요 :)

2021-06-06 09:26 UTC, dave915 commented on src/main/java/wooteco/subway/exception/ExceptionAdvice.java
> +    @ExceptionHandler(SubwayException.class)
개발자가 예상하지 못하는 에러도 처리 할 수 있게 `Exception.class` 처리하는 handler도 한번 만들어보세요 :)

2021-06-06 09:26 UTC, dave915 commented on src/test/java/wooteco/subway/path/FareServiceTest.java
> +        assertThat(fareService.calculateFare(new Distance(67))).isEqualTo(new Fare(1250 + 1100));
junit5 Parameterized Tests 를 이용해보면 어떨까요?

2021-06-09 05:02 UTC, Hyeon9mak commented on src/main/java/wooteco/subway/path/application/PathService.java
'`List<Section>`이 아니고 `Sections` 일급컬렉션을 리스트로 가지는 `List<Sections>`니까 헷갈리지 말고 잘 처리하자!'
라는 생각에 정신이 팔려서 불필요한 작업을 `PathService`에서 진행시키고 있었네요 😭 👍 

짚어주신 부분을 `LineService` 쪽으로 숨기면, `PathService`가 `SectionService`에 의존할 필요도 없어지는거 같아요!

2021-06-09 05:14 UTC, Hyeon9mak commented on src/test/java/wooteco/subway/path/FareServiceTest.java
> +        assertThat(fareService.calculateFare(new Distance(67))).isEqualTo(new Fare(1250 + 1100));
헉!! 레벨1 때 배웠던거 같은데... 생각도 못하고 있었어요..!! 😨 
자연스럽게 떠올릴 수 있도록 계속 계속 써봐야겠네요 😭 👍

2021-06-09 07:20 UTC, Hyeon9mak commented on src/main/resources/logback-access.xml
> +  <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
빌드 스크립트 파일을 아예 추가해보았습니다!! 👍 👍 👍 

말씀해주신대로 http access 관련 로그 파일을 남기도록 xml 파일을 수정했습니다!
또, 다른 크루들의 PR을 보니 application 의 로그도 남기면 좋을거 같아 추가해보았습니다! ([참고내용](https://kouzie.github.io/spring/logback/#appender-%EC%A2%85%EB%A5%98))

2021-06-09 10:24 UTC, Hyeon9mak commented on src/main/java/wooteco/subway/path/application/FareService.java
> +        teenagerAgePolicy.setNextPolicy(childAgePolicy);
Policy 끼리의 의존도도 생각해야하겠네요..!
Enum으로 변경해보았습니다!

2021-06-09 10:43 UTC, Hyeon9mak commented
안녕하세요 데이브!! 피드백 주셨던 부분 반영해보았습니다!!

반영하면서 질문이 몇 가지 생겼습니다!

## 1. 일급 컬렉션의 리스트도 한 차례 더 포장해야할까요?
현재 `PathService` 에서 `List<Sections>` 가 생성되는데, 일급 컬렉션의 리스트도 한 차례 더 일급 컬렉션으로 포장하는가에 대해 고민이 생겼어요. 

'일급 컬렉션을 한 번 더 포장하는건 너무 과하지 않은가?' 라는 생각에 주저하게 되네요 🤔...

현재 제 코드에서는 forEach 말고 크게 하는 일이 없어 포장하지 않았는데, 수행할 동작(역할)이 더 많아지면 포장하게 되는지 궁금합니다!!

## 2. 예외 핸들링 우선순위
피드백 주신대로 `Exception.class` 핸들링 메서드를 추가했어요!
그런데 `SubwayException.class`도, `MethodArgumentNotValidException.class` 도 결국 `Exception.class` 를 상속받는 관계인데 
ControllerAdvice가 이들을 구별할 수 있는 이유가 궁금합니다! (어노테이션을 타고 들어가봐도 잘 모르겠어요... 😵..)

예외가 발생하면, 자식 클래스부터 한 단계씩 부모 클래스로 올라가며 비교하기 때문에 이와 같은 동작이 가능한 것일까요?!

## 3. @ParameterizedTest에 @MethodSource를 사용했습니다!
@CsvSource로 더 짧고 간결하게 테스트 값들을 표현할 수도 있었지만, 요금 정수값을 `1350`이 아니라 `1250 + 100`처럼  기본 요금과 추가 요금을 별개로 표현하고 싶어서 @MethodSource를 사용해보았습니다! 이런식으로 별개의 값을 표현하기 더 적절한 방법이 있는지 궁금합니다!

<br>

이번 리뷰도 잘 부탁드리겠습니다!
감사합니다! 🙇‍♂️ 🙇‍♂️ 🙇‍♂️

2021-06-11 01:00 UTC, dave915 approved these changes
현구막 안녕하세요! 
피드백 반영 확인했어요! 
몇가지 코멘트도 남겨놨으니 확인 부탁드릴게요 :) 
그동안 고생 많으셨습니다. 이만 머지할게요! 
궁금한 점 있으면 언제든 DM주세요!

2021-06-11 01:00 UTC, dave915 commented on src/main/java/wooteco/subway/path/application/PathService.java
> +            List<Sections> sectionsList = lineService.findAllSections();
>'일급 컬렉션을 한 번 더 포장하는건 너무 과하지 않은가?' 라는 생각에 주저하게 되네요 🤔...
현재 제 코드에서는 forEach 말고 크게 하는 일이 없어 포장하지 않았는데, 수행할 동작(역할)이 더 많아지면 포장하게 되는지 궁금합니다!!

음.. 아파트로 비유했을때 호, 동, 단지 처럼 각 단위별로 역할이 있다고 생각해요!  그렇기 때문에 Sections의 일급컬렉션에게 역할이 생긴다면 묶어줘도 좋을 것 같아요!

2021-06-11 01:00 UTC, dave915 commented on src/main/java/wooteco/subway/exception/ExceptionAdvice.java
> +public class ExceptionAdvice {
오류처리 순서에 관해서는 조금 더 찾아보고 DM드릴게요!

2021-06-11 01:00 UTC, dave915 commented on src/test/java/wooteco/subway/path/FareServiceTest.java
> +    @MethodSource("inputDistanceAndExpectFare")
`ParameterizedTest` 말씀 드리면서 `MethodSource` 도 말씀드리려 했는데 잘 쓰셨네요 👍

2021-06-11 01:00 UTC, dave915 commented on src/main/java/wooteco/subway/exception/ExceptionAdvice.java
> +            .body(new ExceptionResponse(e.getMessage()));
보통 Exception.class을 처리하는 handler인경우 개발자가 의도하지 않은 오류를 처리하기때문에 `e.getMessage()`를 그대로 사용하면 어플리케이션 패키지 정보나 사용하고 있는 기술들이 노출 될 수 있어요. 
에러메세지는 `서버에 오류가 발생했습니다` 정도로 내보내 주고 `e.getMessage()`는 로그로만 남겨놓는게 좋을 것 같아요 :)

2021-06-11 01:00 UTC, dave915 commented on src/main/java/wooteco/subway/path/domain/DistancePolicy.java
> +public enum DistancePolicy {
👍

2021-06-11 01:00 UTC, dave915 commented on src/main/resources/logback.xml
> +<configuration debug="true">
안그래도 access log 설정만 하시면 코멘트 남겨놓으려고 했는데, 잘 해주셨네요!

2021-06-11 01:00 UTC, merged

2021-06-11 04:48 UTC, Hyeon9mak commented on src/main/java/wooteco/subway/exception/ExceptionAdvice.java
> +public class ExceptionAdvice {
넵! 감사합니다!

2021-06-11 04:50 UTC, Hyeon9mak commented on src/main/java/wooteco/subway/path/application/PathService.java
> +            List<Sections> sectionsList = lineService.findAllSections();
아! 좋은 비유 감사합니다!!
`Sections` 컬렉션에게 복잡한 명령을 수행시키기 시작한다면 `Sections`를 한 차례 더 감싸는게 충분히 의미가 있겠네요!!!

2021-06-11 04:51 UTC, Hyeon9mak commented on src/main/java/wooteco/subway/exception/ExceptionAdvice.java
> +            .body(new ExceptionResponse(e.getMessage()));
`예상하지 못한 오류 - 어떤 메세지가 노출될지 모름 - 패키지 정보나 사용 기술들이 노출될 수 있음`
거기까지 생각이 닿지 못했습니다!! 좋은 피드백 감사합니다!!!

2021-06-11 08:08 UTC, Hyeon9mak commented
# 학습로그
##  ReverseProxy - WAS - MySQL 서버 만들기
- https://github.com/Hyeon9mak/WIL/blob/main/infrastructure/reverse-proxy-was-mysql.md

## 태그
- 리버스프록시, WAS, mysql

---

## 책임 연쇄 패턴
- https://github.com/Hyeon9mak/WIL/blob/main/oop/chain-of-responsibility-pattern.md

## 태그
- 책임 연쇄 패턴, 디자인 패턴

---

## DAO 에서의 Optional
- https://github.com/Hyeon9mak/WIL/blob/main/oop/optional-in-dao.md

## 태그
- DAO, Optional

---

## SimpleJdbcInsert
- https://github.com/Hyeon9mak/WIL/blob/main/spring/simple-jdbc-insert.md

## 태그
- jdbc

---

## SqlParameterSource
- https://github.com/Hyeon9mak/WIL/blob/main/spring/sql-parameter-source.md

## 태그
- jdbc