[스프링 - 협업미션] 웨지(성시형) 미션 제출합니다.
woowacourse/atdd-subway-fare pull request #8
Opened 2021-05-28 08:41 UTC by sihyung92

안녕하세요 닉!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
또 뵙네요 반갑습니당!

이번 미션에서는 배포에 대해 배웠습니다! 뭐가뭔지 몰라 따라치기만 해보는 경험이었습니다! 눈물이 조금 맺힌 것도 같습니다.
부단히 연습해서 배포 마스터가 되도록 해보겠습니당! 서버환경 구성은 여전히 어렵지만 이제 서버에서 프로젝트 부팅 하나는 기가막히게 합니다.

협업 미션이라는 상황 속이라 브랜칭 전략을 적용해 볼 수 있어서 재밌었습니다! step1은 main 브랜치로 삼고, 요금 관련기능은 feature브랜치로 분리하여 작업하였습니다! 협업 중 이슈가 생기면 main브랜치에서 수정하여 재배포하고, feature 브랜치에선 요금관련한 새로운 기능을 추가하는 경험을 해보았습니다. 

PR을 작성하며 생각해보니 이슈 대응은 main브랜치로부터 hotfix 브랜치를 만들어 작업해 main과 feature로 merge시키는 과정을 거쳤으면 더 좋았을거라고 생각합니다! 아쉽네여! 다음엔 그렇게 해보겠습니다!

그리고 api에 대해 자동 문서화를 적용해보았습니다! 이건 이전에 asciidoctor와 restdocs 경험이 있는 @나봄 크루의 도움을 크게 받았습니다! 함께 학습한 코다, 크로플, 소롱, 오즈에게도 감사를 전합니다. 
저는 잘 갖춰진 문서를 사랑하지만 동시에 그런 문서를 생산하는데 드는 비용과 노력은 아깝습니다. 그런 점에서 restdocs는 멋진 해법이라 정말 재밌었습니다!

또 spring-validation 관련 활용(@valid) 중 예외상황에서 원하는 메세지를 내려줄 수 있도록 Errors 객체에 대해 직렬화 코드를 작성해 보았습니다! jackson라이브러리에 직렬화 방법을 주입하는 커스텀 JsonSerializer 구현을 통해 컨트롤러의 중복코드를 상당히 줄일 수 있어 뿌듯했습니다!

profile 별 설정도 학습했습니다!
내부 구현이 어떤 식으로 되어있는지 궁금했는데, profile 세팅에 따라 원하는 빈 주입을 선택할 수 있는 방식이라는 걸 알게 되니 참 흥미로웠습니다! 이렇게 간편하게 개발 환경별 세팅을 할 수 있다니, DI Container의 장점이 극대화된 멋진 방법이라고 생각합니다!  

미션 할 때는 정신이 없어서 뭐 배운지도 모르는 데 돌이켜보면 새롭게 배운 게 많네요! 리뷰 잘 부탁드립니다!

2021-05-29 07:57 UTC, wbluke requested changes
안녕하세요 웨지! 🙌 
많은 것을 경험했던 마지막 미션이었네요 ㅎㅎ
잘 구현해 주셨고요, 몇 가지 코멘트 남겨보았으니 확인 부탁드려요 🙂

2021-05-29 07:57 UTC, wbluke commented on src/main/java/wooteco/subway/aop/exception/ExceptionController.java
> +public class ExceptionController {
네이밍은 `~ControllerAdivce` 가 나을 것 같아요 :)

2021-05-29 07:57 UTC, wbluke commented on src/main/java/wooteco/subway/path/domain/FarePolicy.java
> +    private final IntPredicate distancePredicate;
predicate 활용 잘 했네요 👍

2021-05-29 07:57 UTC, wbluke commented on src/main/java/wooteco/subway/path/domain/FarePolicy.java
> +        return new Fare(((distance - 1) / km + 1) * EXTRA_CHARGE_UNIT);
`km` 은 단위라서, 더 명확한 파라미터 이름은 없을까요? :)

2021-05-29 07:57 UTC, wbluke commented on src/main/java/wooteco/subway/member/domain/LoginMember.java
> +    }
여기도 많은 상수가 보이는데요, FarePolicy에서 해봤던 것처럼 Enum 등으로 표현해볼 수 있을까요? :)

2021-05-29 07:57 UTC, wbluke commented on src/main/java/wooteco/subway/member/dao/MemberDao.java
> +    public AuthorizationMember findByEmail(String email) {
기존 Member를 인터페이스로 수정해서 그런 것 같은데요, 
테이블과 엔티티명이 일치하지 않아서 혼란을 야기할 것 같아요!

2021-05-29 07:57 UTC, wbluke commented on src/main/java/wooteco/subway/member/domain/GuestMember.java
> +    }
UnsupportedOperation 을 사용하셨군요 ㅎㅎ 좋은 접근입니다 👍 
다만, 실제로 GuestMember가 할 수 있는 일은 외부에서 넣어준 (기본)요금을 반환하는 것 밖에는 없고,
Member 를 사용하는 서비스에서는 id, email, age 등을 런타임에 호출하기 전까지는 어떤 유저인지 확인하기가 어려울 것 같아요.
(지금은 id, email, age를 사용하는 로직이 없는 것 같지만요)

그리고 해당 exception이 터졌을 때 처리도 부가적으로 필요할 것 같고요. 
(서비스 특성상 로그인한 사용자보다 로그인 하지 않은 유저가 더 많을 수도 있는데, 매번 예외 발생으로 유저를 구분하는 것은 애플리케이션 입장에서 큰 부담일 것 같아요. 예외도 비용이기 때문입니다.)

이 객체나 LoginMember에 별도의 플래그를 두고 서비스에서 체크해서 사용해보는건 어떨까요?
쉽게는 boolean 컬럼을 둔다거나, 더 나아가면 권한 레벨에 따른 Enum을 활용할 수 있을 것 같아요 :)

2021-05-29 07:57 UTC, wbluke commented on src/test/java/wooteco/subway/TestDataLoader.java
> +public class TestDataLoader {
저는 테스트용 데이터(text fixture)를 공통으로 만들어 놓고 사용하는 것을 지양하고 있는데요 ㅎㅎ
이렇게 되면 다음과 같은 문제가 생깁니다.

1. 새로운 테스트를 작성할 때 기존에 어떤 데이터들이 존재하는지 반드시 알아야만 한다.
2. 하나의 테스트에서 공통 데이터를 조작하는 테스트를 진행하는 경우, 동시에 수행되는 다른 테스트에서 영향을 받을 수 있다. (잘못하면 전체 테스트를 돌릴 때, 언제는 성공하고 언제는 실패하는, 디버깅이 아주 어려운 상황을 만날 수도 있다.)
3. 2번 등의 이유로 테스트 간 의존관계가 생기고, 독립적 수행이 불가능한 구조로 점차 발전한다. 모든 테스트 클래스(메서드)가 데이터로드 클래스에 의존한다.
4. 애플리케이션이 커지면 데이터 로드 클래스도 점차 관리하기 어려워지며, 프로젝트에 신규 참여자가 생기는 경우 허들이 생길 수 있다.

위와 같은 이유로 저는 테스트 데이터를 각 테스트 메서드의 given절, 그게 어렵다면 최대 클래스 선에서 만드는 것을 지향합니다.
한번 고민해보시고, 제 의견에 동의하신다면 리팩토링 해보면 좋을 것 같아요 :)

2021-05-29 07:57 UTC, wbluke commented on src/main/java/wooteco/subway/path/domain/Fare.java
> +public class Fare {
Fare, FarePolicy 같은 핵심 도메인 객체의 단위 테스트도 있으면 좋을 것 같아요 :)

2021-05-29 09:23 UTC, sihyung92 commented on src/main/java/wooteco/subway/aop/exception/ExceptionController.java
> +public class ExceptionController {
예외를 처리하는 컨트롤러다! 라는 느낌으로 작성하였는데, Advice인 것에 중점을 둔다면 ControllerExceptionAdvice (컨트롤러에서 발생하는 Exception을 컨트롤하는 Advice) 라는 네이밍이 더 적절할 것 같아 `ControllerExceptionAdvice` 로 수정하였습니다!

2021-05-29 09:27 UTC, sihyung92 commented on src/main/java/wooteco/subway/path/domain/FarePolicy.java
> +    private final IntPredicate distancePredicate;
히힛

2021-05-29 09:34 UTC, sihyung92 commented on src/main/java/wooteco/subway/path/domain/FarePolicy.java
> +        return new Fare(((distance - 1) / km + 1) * EXTRA_CHARGE_UNIT);
저는 무언가의 "단위"나 "기준" 을 네이밍 하는게 넘 어렵더라구요🥲 닉은 이런 상황에서 어떤 표현을 사용하시나요??

2021-05-29 09:56 UTC, sihyung92 commented on src/main/java/wooteco/subway/path/domain/FarePolicy.java
> +        return new Fare(((distance - 1) / km + 1) * EXTRA_CHARGE_UNIT);
kmUnit으로 수정하였습니당당당

2021-05-29 13:33 UTC, sihyung92 commented on src/main/java/wooteco/subway/member/domain/LoginMember.java
> +    }
넵 리팩토링 해야지 하고 까먹은 부분입니당 부끄부끄
수정하여 커밋하겠습니다!

2021-05-29 13:38 UTC, sihyung92 commented on src/main/java/wooteco/subway/member/dao/MemberDao.java
> +    public AuthorizationMember findByEmail(String email) {
오오 테이블과 엔티티명이 맵핑되는 것도 신경써야하는 부분이군요!! 또 하나 배워갑니다.
interface명을 User로 수정하고 Member와 Guest로 리팩토링 하도록 하겠습니다!
리뷰 감사합니당당

2021-05-29 13:44 UTC, sihyung92 commented on src/main/java/wooteco/subway/member/domain/GuestMember.java
> +    }
기존 로직이 로그인 하지 않은 유저인 경우 각 필드에 null을 주입하여 활용하는 것에 불편함을 느껴 일종의 Null 객체 처럼 GuestMember를 만들었는데, 서비스 특성에 따라 더 많은 비용이 발생할 만한 부분을 고려하는 관점이 신선하게 느껴지네요!!
LoginMember가 로그인 했는지 여부를 LoginMember객체로부터 얻어내어 판단하여 별도의 정책이 적용될 수 있는 방향으로 리팩토링 해보겠습니다.
감사합니당당당~~~

2021-05-29 23:52 UTC, sihyung92 commented on src/test/java/wooteco/subway/TestDataLoader.java
> +public class TestDataLoader {
오오 좋은 리뷰 감사합니다!! 다 일리있는 말씀이고, 읽어보며 깊이 공감했습니다. 하지만 다음과 같은 이유로 리팩토링은 하지 않겠습니다 :) 한번 읽어보시고 의견 남겨주시면 넘넘 감사할 것 같아요!!

1. 1번과 4번에 대해 => 이번 미션처럼 현실에 있는 개념과 픽스쳐 간에 연관성이 존재하는 경우(실제로 있는 지하철 노선도의 반영), "2호선", "역삼역" 등으로 픽스쳐를 만들고 현실의 구조와 동일하게 생성하면 (ex. 2호선에 강남,역삼,삼성역이 포함된다) 타 개발자가 어떤 데이터가 있는지 직관적으로 이해할 수 있다. 예컨데 원하는 테스트에서 TestDataLodaer 인스턴스를 생성하고 IDE의 도움을 받아 어떤 메소드들이 있는지 살펴보면, `TestDataLoader.2호선`은 2호선을 가리키고 그 안엔 2호선에 포함된 역이 있음을 픽스쳐 클래스를 열어보지 않고도 짐작할 수 있다.

2. 2번에 대해 -> 테스트 데이터를 static 생성하지 않고 lazy loading한 방식으로, 호출할 때 생성하여 반환하는 방식으로 작성하면(리팩토링 하겠습니당!) 각 테스트는 다른 인스턴스를 활용하므로 병렬 스레드에서 동시수행될 때 문제를 방지할 수 있다. 그러면 공통 테스트 데이터 객체의 메모리적인 이점은 사라지겠지만 중복코드를 제거한다는 측면에서 여전히 이점이 있다고 생각한다.

3. 3번에 대해 -> 모든 클래스의 데이터로드 클래스의 의존여부는 테스트를 작성하는 개발자의 선택이다. 테스트 로더를 이용할 수도, 개별 테스트에서 픽스쳐를 생성할 수 도 있다. 

테스트용 데이터를 공통으로 만들어 놓고 활용하니 테스트를 작성하는 시간을 많이 아낄 수 있었습니다. 하지만 말씀해주신 리뷰 덕분에 내가 활용할 테스트 픽스쳐가 뭔지 확인하기 위해 데이터로더 클래스를 까봐야하는 상황이라면, 공통 테스트 데이터 로더를 활용하는 것에 대해 고민해봐야 겠다는 생각을 추가로 가지게 되었습니다!!!! 

또 의견 남겨주세요 꼭꼭꼭 꼭이요!!!

2021-05-29 23:54 UTC, sihyung92 commented on src/main/java/wooteco/subway/path/domain/Fare.java
> +public class Fare {
>_< 인수테스트가 먼저 작성되어 있으니 인수테스트에서 해결보려고 하는 버릇이 생기더라구요 부끄럽습니당
도메인 테스트 작성하겠습니당당당당

2021-05-31 14:41 UTC, wbluke commented on src/main/java/wooteco/subway/path/domain/FarePolicy.java
> +        return new Fare(((distance - 1) / km + 1) * EXTRA_CHARGE_UNIT);
네에 저도 unit 많이 씁니다. distanceUnit 이런 식으로 지었을 것 같아요 :)

2021-05-31 14:52 UTC, wbluke approved these changes
웨지~ 리팩토링 해주신 부분과 의견 남겨주신 것 잘 보았어요 👍 
고생 많으셨습니다 🙂

2021-05-31 14:52 UTC, wbluke commented on src/main/java/wooteco/subway/member/domain/AgeFarePolicy.java
> +    DEFAULT(age -> false, UnaryOperator.identity());
깔끔하게 잘 정리해 주셨네요 👍

2021-05-31 14:52 UTC, wbluke commented on src/test/java/wooteco/subway/TestDataLoader.java
> +public class TestDataLoader {
오 좋은 의견 감사합니다 ㅎㅎ 저도 제 의견이 무조건 맞다는 입장은 아니어서요 !
웨지처럼 좋은 반론을 주신 분은 처음이네요 👍 
특히 `현실에 있는 개념과 픽스쳐 간에 연관성이 존재하는 경우` 이 부분의 설명이 많이 와닿았어요 :)

테스트 구조/방식 등에 대한 결정은 정답이 있는게 아니라, 본인이 속해 있는 팀 내에서 충분히 논의하고 다같이 컨벤션으로 결정하는 것이 맞다고 생각해요ㅎㅎ (다 장단이 있기 때문에)
도메인에 따라 명확해지는 부분이 있을 수 있다는 점이 신선했어요 ㅎㅎ 의견 감사해요 !

2021-06-01 00:18 UTC, merged

2021-06-23 14:59 UTC, sihyung92 commented
# RSA + SSL
- [개인 노션](https://www.notion.so/RSA-SSL-aeef063813f2494baca034c8d84d3d6c)
## 태그 
- 암호화

# 쓰레드 풀
- [개인 노션](https://www.notion.so/Thread-Pool-dbbcb8d55489402d9999bbb33bc9f773)
## 태그
- 톰캣

# 객체지향 설계와 의존성 분리
- [우아한 객체지향 동영상 노션 정리](https://www.notion.so/989dcb708ce44a5db0475e8e89da07bd)
## 태그
- 설계

# 필터와 인터셉터의 차이
- [개인 노션](https://www.notion.so/eae57c6924064eb4a6672ed78b1ce98d)
## 태그
- 설계

# DB 인덱스
- [개인 노션](https://www.notion.so/DB-7b0d61fff2b4485f932f817b4426befa)
## 태그
- DB

# DB 고립 레벨
- [개인 노션](https://www.notion.so/DB-isolation-level-953c1a510a05418d8078675e9ed06d12)
## 태그
- DB

# DB LOCK
- [개인 노션](https://www.notion.so/DB-Lock-inno-db-9918b89c5eb242e49c9d1c49659904cb)
## 태그
- DB

# AOP
- [개인 노션](https://www.notion.so/AOP-4be7af45c1464d708682f0aa9807de13)
## 태그
- AOP

# 프록시와 빈
- [개인 노션](https://www.notion.so/Proxy-78708fac6cb44f0da361487f4901b338)
## 태그
- 프록시패턴, 스프링